### PR TITLE
Menu Option Disappears Completely On Certain Screen Size

### LINKED ISSUE #3850: [Bug]: Menu Option Disappears Completely On Certain Screen Size
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

On Screens of width in the range of roughly 668px - 750px wide, the menu dropdown on the account view page dissapears visually, leaving no way clicking unless you find it by hovering over it.
The menu missing from the right side:
image

The menu seen by hovering:
image

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by ericji1326**
Fixes #3850

### CODE REVIEW

**Review by jfdoming — CHANGES_REQUESTED** [review]
Thanks for the PR! We generally don't use raw CSS where possible. Instead, `View` has a `style` prop that works similarly.

**Comment by ericji1326** [comment]
> Thanks for the PR! We generally don't use raw CSS where possible. Instead, `View` has a `style` prop that works similarly.

I'll get a fix up ASAP

**Comment by ericji1326** [comment]
Hey @jfdoming, I have made the change as you requested! Let me know what you think! 😄

**Review by jfdoming — APPROVED** [review]
Thanks! Looks good. If you have time, would be nice to add a screenshot test for this—you can follow [this template](https://github.com/actualbudget/actual/blob/master/packages/desktop-client/e2e/transactions.mobile.test.js#L17). Otherwise happy to merge as is

**Comment by ericji1326** [comment]
> Thanks! Looks good. If you have time, would be nice to add a screenshot test for this—you can follow [this template](https://github.com/actualbudget/actual/blob/master/packages/desktop-client/e2e/transactions.mobile.test.js#L17). Otherwise happy to merge as is

Hey @jfdoming! Thanks for the PR approval! I think I'm pretty low on time due to exams. May I get this just merged as is?

Thanks!

**Pull request merged**
