### PR TITLE
Fix loading of mobile/desktop page on window resize

### PR DESCRIPTION
**Pull request by joel-jeremy**
Closes https://github.com/actualbudget/actual/issues/3707

Also moved `ResponsiveProvider` to the correct `responsive` feature folder so there are some import path changes but the actual change in is `ResponsiveProvider` and `LoadComponent`

### CODE REVIEW

**Comment by joel-jeremy** [comment]
@MatissJanis FYI I had to remove the module cache since it's only caching the first module that is loaded and re-uses that even when the `importer` prop has changed due to a resize and is now supposed to load a different module

**Review by matt-fidd — APPROVED** [review]
This is brilliant! Code looks fine to me (pending Matiss approving the cache change you highlighted) and it works functionally. This'll make rotating for a desktop feature much nicer.

**Comment by MatissJanis** [comment]
TBH I've been considering removing the lazy loading. I've found it to be quite buggy on fly.io Also: does the app really benefit from it? Does it make it load faster? I don't think so - the size of the app is relatively small already, so we might just be splitting hairs with lazy loading parts.

**Comment by MatissJanis** [comment]
But my above comment shouldn't block this PR. The `LoadComponent` changes LGTM :+1:

**Comment by joel-jeremy** [comment]
> TBH I've been considering removing the lazy loading. I've found it to be quite buggy on fly.io Also: does the app really benefit from it? Does it make it load faster? I don't think so - the size of the app is relatively small already, so we might just be splitting hairs with lazy loading parts.

What is the bug you are seeing? We can test it out first when we decide to remove the code splitting since I believe if we remove it's going to load all the desktop components when using mobile. One good thing about that is it will no longer need to load the desktop files from the server when the user switches to landscape mode.

**Comment by MatissJanis** [comment]
> What is the bug you are seeing? We can test it out first when we decide to remove the code splitting since I believe if we remove it's going to load all the desktop components when using mobile. One good thing about that is it will no longer need to load the desktop files from the server when the user switches to landscape mode.

It happens semi-frequently, but I've not been able to figure out what exactly is going on. From a users perspective - the lazy-loaded component just loads forever. Which prompts me to do a refresh of the page (at which point things work OK). There are no console errors, so I'm oblivious as to where things might be stuck.

**Comment by MatissJanis** [comment]
> Ive seen the reports page not load after an update, and requires a refresh. Its fairly consistent after an update has happened. Is that the kind of thing you are seeing?

Reports page is indeed the most frequently failing. Probably because that's the only noticeable part we lazy-load within the desktop experience (I know mobile is lazy-loaded too if you use desktop exp, but that's not really noticeable.. as you I don't generally switch between desktop <-> mobile while using the app). Happens sometimes after an update, sometimes without updates. Pretty randomly.

**Comment by joel-jeremy** [comment]
I also get that sometimes when loading the reports page but haven't really dug into it. Should we merge this PR for now?

**Comment by youngcw** [comment]
> I also get that sometimes when loading the reports page but haven't really dug into it. Should we merge this PR for now?

Seems like you are good to merge and can look at the lazy loading separately.

**Pull request merged**
