### PR TITLE
Template: Apply schedule template only on needed month

### PR DESCRIPTION
**Pull request by youngcw**
Add option to schedule templates to budget the full amount only in the needed month.  Default behavior stays the same of spreading the expense out over the available range.

To use the option, use a template like `#template schedule full SCHEDULE_NAME`

Also some minor cleanup.

### CODE REVIEW

**Comment by shall0pass** [comment]
@youngcw  I think this commit causes the 'schedule' keyword to not work (at least without the 'full' option).  Could you double check?

**Comment by youngcw** [comment]
Uh oh.  I think my cleanup of the parser is the problem.  It works for me if I include a priority, but no priority breaks the parsing.  I must have not tested it enough.

**Comment by youngcw** [comment]
Its looking like some of the other templates fail if there isn't a priority set, not just the schedule ones.  Ill undo the clean up I did since that seems to be messing up things

**Comment by shall0pass** [comment]
Thanks for taking a second look!

**Pull request merged**
