### PR TITLE
Read-only Responsive view

### PR DESCRIPTION
**Pull request by trevdor**
A PR will keep the build preview current for anyone testing.
👉🏻  Please report bugs, propose changes, etc. in discussion https://github.com/actualbudget/actual/discussions/433

Prior to releasing this particular version...
### Awaiting Fix
- [x]  Settings screen layout issues on mobile
    * @j-f1 fixed in https://github.com/actualbudget/actual/pull/434
- [x] "Close budget" button broken on mobile
    * https://github.com/actualbudget/actual/discussions/433#discussioncomment-4602003 
    * @j-f1 fixed in https://github.com/actualbudget/actual/pull/434
- [x] Styles not recomputing correctly in some cases on window resize 
    * also applies to mobile users rotating from portrait to landscape

- [ ] UI fix ups
    - [x] Budget screen bottom margin
        * https://github.com/actualbudget/actual/discussions/433#discussioncomment-4603877
    - [x] Budget screen Offline label color
        * https://github.com/actualbudget/actual/discussions/433#discussioncomment-4603885    
    - [x] Account view search: Empty results state
        * https://github.com/actualbudget/actual/discussions/433#discussioncomment-4603889
    - [ ] Server config screen: overlap in footer text
        * https://github.com/actualbudget/actual/discussions/433#discussioncomment-4605317
    - [x] Budget/Accounts/Settings header consistency
        * https://github.com/actualbudget/actual/discussions/433#discussioncomment-4603898

### Won't Fix
0. Bah. I fixed the only won't-fix I had so far...

### CODE REVIEW

**Comment by MatissJanis** [comment]
Would you mind squashing all the commits starting from Jed's? That would help me at least review commit-by-commit.

Originally I thought we would be sending subsequent PRs against the new branch so they could be properly reviewed. But now we're back to the start with one massive PR.

**Comment by trevdor** [comment]
> Would you mind squashing all the commits starting from Jed's? That would help me at least review commit-by-commit.
> 
> Originally I thought we would be sending subsequent PRs against the new branch so they could be properly reviewed. But now we're back to the start with one massive PR.

That's a reasonable concern. Just not a workflow I've ever tried, so didn't occur to me. Maybe I'll try that next time.
Squashed it up nice into tidy commits.

**Comment by MatissJanis** [comment]
No problem.

Reviewed the commits up until https://github.com/actualbudget/actual/pull/435/commits/e1683c82291acaeb698b5985d5e552e08d8ec7d5 (inclusive). All look reasonable. For the most part just styling changes.

Good job :+1:

Do you want to run a second bug-busting session or would you be happy to merge & release?

**Comment by trevdor** [comment]
I'm feeling ready to merge & release and address anything that comes up in separate bug reports.

**Review by MatissJanis — APPROVED** [review]
Sounds good to me! Lets push it in master and continue iterating as things come up.

**Comment by trevdor** [comment]
Oh wait, there's that nasty [text overlap on the File chooser screen](https://github.com/actualbudget/actual/discussions/433#discussioncomment-4605317) (my last noted todo item in the Description here).
I can get to that in several hours ("this evening", where I'm at). 

Do you think that's tolerable enough to fix later? 
Otherwise, I can merge that once it's fixed and you can do a release whenever convenient. Thoughts?

**Comment by MatissJanis** [comment]
IMO it's fine to merge as-is and then work on the footer improvement while we finalize some final things in this release.

**Pull request merged**
