### PR TITLE
:bug: (ynab4) transaction cleared state in imports

### LINKED ISSUE #399: [Bug]: Importing YNAB4 budget forces transaction to cleared status
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

When importing a YNAB4 budget with uncleared transactions (e.g. a scheduled transaction that hasn't yet occurred), they import as cleared. 

### What error did you receive?

None.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

### PR DESCRIPTION
**Pull request by MatissJanis**
Fix YNAB4 importer: the `cleared` state was not being read from the import file.

Closes #399

### CODE REVIEW

**Review by j-f1 — APPROVED** [review]
Code LGTM, can’t test it though.

**Comment by biohzrddd** [comment]
The budgeted values still do not import with the same budget from #88. Shall I raise another bug for that? The below image is using https://deploy-preview-88--actualbudget.netlify.app/budget and the same result for https://deploy-preview-490--actualbudget.netlify.app/budget

image

**Comment by MatissJanis** [comment]
> The budgeted values still do not import with the same budget from #88. Shall I raise another bug for that? The below image is using https://deploy-preview-88--actualbudget.netlify.app/budget and the same result for https://deploy-preview-490--actualbudget.netlify.app/budget
> 
> image

Yes, please open a new issue for the budgeted amount problem. This PR should solve only the `cleared` state issue you reported.

Could you please verify if the `cleared` issue is solved with the preview deployment of this PR?

**Comment by biohzrddd** [comment]
Copying comment from #88 

`Thanks for the work merging @MatissJanis ! I tried importing my test file from #399 and confirmed the cleared status now imports.`

**Comment by MatissJanis** [comment]
> Copying comment from #88
> 
> `Thanks for the work merging @MatissJanis ! I tried importing my test file from #399 and confirmed the cleared status now imports.`

Great, thanks a mil!

**Pull request merged**
