### PR TITLE
Account Categories/Grouping for Side bar

### PR DESCRIPTION
**Pull request by Midgetwombat**
This PR Adds account grouping. its been overhauled from the original simple concept, to adding a new column to the database and adding UI elements.

How to set Up a Category:

Go to the account you wish to add to the category and you'll see the badge icon above the account name.
image

Click the edit pencil and type in a group name 
image

image
Now the group name appears above the account name.

image
The group is also in the side panel with the accounts that are apart of it under the title.
if you want to quickly add another account to the same group. Just drag and drop onto an account already in that group. As long as the accounts are apart of the same broader type of On/Off Budgeted. They can be grouped together.

image
You will notice that 'For budget' total is going down as we move accounts out of it, and it will even disappear if we move all the accounts out. This is to make it less confusing the amounts in each group title will only show the total of the accounts apart of said group.

If you prefer to know your on budget total and also see the total of a group then there are settings for that.
image
You will find these two setting in the first settings page. The first option 'Nested Accounts on Sidebar' will add an additional level to the group nesting. You will have to main groups Off/On budget. Then nested under those groups will be your account groups. The amount in the off/on budgets will now show the total amount of all on/off budget accounts. While the group titles will only show the total amount of the groups accounts. 

EXAMPLE:
image

The Next Option 'Show group name with Account name' Will add the group name in front of the account name, everywhere the account name shows.

Example Without Option:
image

Example With Option:
image

Finally, You can also search for groups in the search box within the accounts page.

### CODE REVIEW

**Comment by MatissJanis** [comment]
Re-sharing the message I sent on Discord so it wouldn't get lost:

```
My 2cents:
- a new DB field should be used for the group (which also requires setting up different UI controls for adding/removing items within said group)
- the sidenav UI looks visually unappealing with the proposed grouping. I wonder if we should instead consider the top-level groups (on/off budget) as the defaults, but allow mutating them (ie adding more top level groups, renaming them, etc)
```

I'm quite opinionated about the 1st point (new DB field), but not so much about the 2nd (open to various creative solutions here). :)

**Comment by Midgetwombat** [comment]
> Re-sharing the message I sent on Discord so it wouldn't get lost:
> 
> ```
> My 2cents:
> - a new DB field should be used for the group (which also requires setting up different UI controls for adding/removing items within said group)
> - the sidenav UI looks visually unappealing with the proposed grouping. I wonder if we should instead consider the top-level groups (on/off budget) as the defaults, but allow mutating them (ie adding more top level groups, renaming them, etc)
> ```
> 
> I'm quite opinionated about the 1st point (new DB field), but not so much about the 2nd (open to various creative solutions here). :)

I'm looking into the database. there is a lot more work to put in for it since it also requires API update and UI changes. I'm treading lightly as I don't want to break anything while I poke about. I think if i manage to get the DB done will just be a string field. And then later that can be used as an ID field if a new table is created for account grouping.

At the moment, if i don't manage that in time. This is usable for people who want to get a feel for account grouping. It's a day off today so i do need some type of puzzle to keep me going around house work. XD

**Comment by MatissJanis** [comment]
Couple of issues:

1. how can I rename "for budget" and "off budget" groups?
2. how can I change the ordering of the groups?
3. when I select the "for budget" category - the resulting table has transactions from the "for budget" group + some other groups; I would have expected to see only the transactions that are linked to the specific group visible in the side-nav (I get why technically it is implemented as-is right now, but from a users perspective that is confusing)
4. there should not be two modes for account groupings; there should not be a setting toggle - lets stick with just one opinionated solution - as per [Actual design strategy](https://actualbudget.org/docs/contributing/#the-design-strategy-of-actual)
5. the new grouping is not visible in the account selection autocomplete (screenshot 1)
6. the "blank group" icon is confusing (looks like some sort of achievement badge) - can we instead use the default group name there (i.e. "for budget / off budget"); that way we always show an account group (which is technically also correct - there is always a group for an account)
7. when I select a specific group - multiple groups get highlighted and the transaction table shows multiple groups - that's unexpected (screenshot 2)
8. I can't combine off-budget and on-budget account into the same group - it forces me to create a new group (with identical name)

Screenshot 2024-08-18 at 16 50 45

Screenshot 2024-08-18 at 16 53 54

**Comment by Midgetwombat** [comment]
> Couple of issues:
> 
> 1. how can I rename "for budget" and "off budget" groups?
> 2. how can I change the ordering of the groups?
> 3. when I select the "for budget" category - the resulting table has transactions from the "for budget" group + some other groups; I would have expected to see only the transactions that are linked to the specific group visible in the side-nav (I get why technically it is implemented as-is right now, but from a users perspective that is confusing)
> 4. there should not be two modes for account groupings; there should not be a setting toggle - lets stick with just one opinionated solution - as per [Actual design strategy](https://actualbudget.org/docs/contributing/#the-design-strategy-of-actual)
> 5. the new grouping is not visible in the account selection autocomplete (screenshot 1)
> 6. the "blank group" icon is confusing (looks like some sort of achievement badge) - can we instead use the default group name there (i.e. "for budget / off budget"); that way we always show an account group (which is technically also correct - there is always a group for an account)
> 7. when I select a specific group - multiple groups get highlighted and the transaction table shows multiple groups - that's unexpected (screenshot 2)
> 8. I can't combine off-budget and on-budget account into the same group - it forces me to create a new group (with identical name)
> 
> Screenshot 2024-08-18 at 16 50 45 Screenshot 2024-08-18 at 16 53 54

Sure lets go over a few of the issues.

1) The on/off budget groups are defaults since a budget will always be either on budget or off budget. They cannot be renamed instead disappear when all accounts are removed. And if an account is removed from all groups it will default to the on/off budget.

2) The accounts can be reordered as normal and the groups will move up or down (excluding on/off budget) depending on how high the order is of its topmost account. I will admit this needs work to make it flow better, since it would be fiddly to move a whole group up.

3) So clicking the For budget would show you all the account transactions that are for on budget. Same as for off budget, it would show you all the off budget transitions. Now i wanted to have it so if another group header was clicked, you would see only that groups transactions. But i didn't manage to do that as of yet.

4) That's fair i did just re-read that, but there are two aspects of the current implementation. 1st is testing the design, so we can all play and fiddle with the two designs to strengthen our opinions. And 2nd i wanted to give choice, Same as for the naming conventions for the account titles. there is a setting that will put the group name with the account name or turn that off. 

5) There is a setting to enable that once clicked it should display <group name> - <account name> (again i'll need to work on the settings, i got a little carried away on giving users choice).

6) So as discussed there is no group on an account its just null, But i have no issues with changing the badge to anything else at all. Including just off/on budget, its really just a place holder for something better.

7) No not unexpected again each one will take you to the on budget transactions so technically all those groups would be in that list. Now that I think of it I may defiantly have a bug with off budget groups also highlighting and showing on budget transactions. I'll check that out soon, but if i can work out how to display only the grouped accounts in the transaction list. That problem will be solved.

8) Correct i have not mixed the two, I've seen off budget and on budget as two different systems that need some type of separation.

So defiantly open to more discussion and input, this is still a WIP and thought it was time to show what I've come up with so far.

**Comment by MatissJanis** [comment]
1. I would classify this as a bug. Any group label should be editable. The "on/off budget" grouping is just the default we provide.
2. drag-n-drop of group is the way to go I think (with the group title being the drag-handle)
3. I would classify this as a bug as well. When clicking on a group - I expect to see only that group. And nothing else.
4. No problem experimenting around. Just let me know when I should do a proper final review - by that time only a single solution should remain. We're not going to merge multiple competing solutions to `master` :)
5. -
6. see point 1
7. see point 3
8. see point 1

**Pull request closed without merging**
