### PR TITLE
Increase minimum cleared column width (Fix #2341)

### LINKED ISSUE #2341: [Bug]: Sort by cleared status overlapping UI
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### Is this related to GoCardless, Simplefin or another bank-sync provider?

- [ ] I have checked my server logs and could not see any errors there
- [ ] I will be attaching my server logs to this issue
- [ ] I will be attaching my client-side (browser) logs to this issue
- [ ] I understand that this issue will be automatically closed if insufficient information is provided

### What happened?

The cleared status icon in the transactions table overlaps with the `Deposit` column:
image

### What error did you receive?

_No response_

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by dangrous**
Fixing https://github.com/actualbudget/actual/issues/2341 - decided that the easiest course of action was to increase the minimum width of that column, but definitely open to other suggestions!

### CODE REVIEW

**Comment by dangrous** [comment]
Okay so the visual regression tests failed, understandably, since I made a visual change. What's the best way to update those? I haven't dealt with that kind of test before. Thank you!

**Comment by joel-jeremy** [comment]
Thank you for looking into this! You will need to update the test screenshots to show the new UI. You can follow steps provided here: https://github.com/actualbudget/actual/tree/master/packages/desktop-client#visual-regression

**Comment by dangrous** [comment]
Cool! I've given that a shot and am struggling a bit with Docker, I should have it sorted out in a day or so though! Anything I need to do to "claim" the issue or anything in the meantime?

**Comment by dangrous** [comment]
Welp, I'm stuck. I'm running the server and my dev build loads in my browser nicely at https://localhost:3001. But when I follow the instructions and try to run the tests (from the Docker container), i get `Error: page.goto: net::ERR_CONNECTION_REFUSED at https://localhost:3001/` any time it tries to connect. I'm not sure what I'm doing wrong... I'll keep trying but if you have any suggestions that would be lovely! I'm sure I'm missing a step somewhere.

**Comment by youngcw** [comment]
> i get `Error: page.goto: net::ERR_CONNECTION_REFUSED at https://localhost:3001/`

Have you tried using the full IP address of your machine?  Since docker acts like its own machine localhost probably wont work inside the docker container.

**Comment by dangrous** [comment]
Oooh that was it, thank you @youngcw!

I think this is good to go now; please let me know any suggestions/edits - including reviewing the new snapshots to make sure they don't look weird to you. They look different but not bad, I don't think!

**Review by youngcw — APPROVED** [review]
Looks good

**Pull request merged**
