### PR TITLE
Hide mobile nav tabs on scroll

### PR DESCRIPTION
**Pull request by joel-jeremy**

### CODE REVIEW

**Comment by youngcw** [comment]
My initial reaction is that I wish the transition was a little faster. I'm fine as is though if other people like it.

**Comment by joel-jeremy** [comment]
@youngcw I've made the transition a bit faster

**Comment by tjfinlinson** [comment]
Cool enhancement @joel-jeremy! I like it and works great on my Pixel

**Comment by MatissJanis** [comment]
Pretty cool! Found a bug though: scrolling to the bottom always opens the footer back up. And then scrolling to the very top closes it.

https://github.com/actualbudget/actual/assets/886567/f366e0e4-3663-438b-89d9-b2928b4922e7

**Comment by joel-jeremy** [comment]
Hmm, I don't seem to encounter it on my phone (Chrome on Android). What is the browser you are using?

**Comment by joel-jeremy** [comment]
@MatissJanis I've done some updates. Could you check again if the issue still persists?

**Comment by MatissJanis** [comment]
Sadly still the same issue. Tested on OSX + Safari (desktop) and IOS + Safari (mobile). Both have the same problem.

**Comment by MatissJanis** [comment]
Chrome works fine though. I think it has to do with the "bounce" scroll effect that safari has.

**Comment by joel-jeremy** [comment]
@MatissJanis Unfortunately I don't have a proper device to be able to test it out. Do you think merging it is still worth it or do you think it's a deal breaker for Safari users? Maybe we can merge and then create an issue so someone else can pick up on fixing it?

Can you try and see if the issue is also present in: https://github.com/actualbudget/actual/pull/1758?

**Comment by MatissJanis** [comment]
Fixed the issue in: https://github.com/actualbudget/actual/pull/1745/commits/d01956a84dbc5818424d98fc79fd09e682f10374

I'll try to do a code review later today. :)

**Comment by joel-jeremy** [comment]
Awesome! Thanks for fixing that. I just noticed a bug, it doesn't hide the navbar when you quickly scroll to the bottom.

**Review by MatissJanis — APPROVED** [review]

**Comment by youngcw** [comment]
@joel-jeremy Is there more you would like to do on this or is ready to merge?

**Comment by joel-jeremy** [comment]
I wanna check first the issue where navbar does not hide unless it reached the bottom atleast once.

**Comment by joel-jeremy** [comment]
Merging this. The scrolling issue will be addressed in https://github.com/actualbudget/actual/pull/1758.

**Comment by ioslife** [comment]
Can this be turned into an option? I would prefer the bar not to be hidden

**Pull request merged**
