### PR TITLE
Storing start month in user prefs

### LINKED ISSUE #1039: [Feature] Retain months viewed range
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When viewing multiple months in the budget window I like to set the view to last/current/next month. Ex. at time of writing I would look at the budgets for April/May/June.

The next time I open the browser window I still can view 3 months, but it starts at the current month instead of remembering the last used range.

### Describe your ideal solution to this problem

Save the viewed months in the cached data along with the number of months viewed so a user can jump back in to the same setup as the last time.

### Teaching and learning

_No response_

### PR DESCRIPTION
**Pull request by Miodec**
Remembering the state of start month (selected month in budget)

Closes #1039

### CODE REVIEW

**Comment by j-f1** [comment]
It looks like you have the code with the updated UI in this PR?

Also, I tested it out and starting from scratch `prefs.startMonth` appears to be null which causes the budget page to error out.

**Comment by Miodec** [comment]
> It looks like you have the code with the updated UI in this PR?
> 
> Also, I tested it out and starting from scratch `prefs.startMonth` appears to be null which causes the budget page to error out.

Whoops, one sec.

**Comment by MatissJanis** [comment]
Hmm.. so lets say I see only one month of budget. Currently it's June. My local pref will store it as June.

I will open it up tomorrow. I would expect to see July. But I will still see June?

**Comment by Miodec** [comment]
> Hmm.. so lets say I see only one month of budget. Currently it's June. My local pref will store it as June.
> 
> I will open it up tomorrow. I would expect to see July. But I will still see June?

We would need to store the current month of the last visit in prefs or localstorage and then check on load if its different to the current month - if it is, set the selection to the current month otherwise use prefs. 

Any examples in the codebase where something similar happens?

**Comment by youngcw** [comment]
Could you store the preference as an offset instead of an absolute month?

**Comment by j-f1** [comment]
Alternatively:

- store `null` when looking at the current month so that it can auto follow as the month changes
- close this PR, keep existing logic
- store the current month in app state, rather than prefs. This would retain the month as you flip back and forth between pages, but would reset to this month when you close & reopen the app

**Comment by Miodec** [comment]
> * but would reset to this month when you close & reopen the app

I think the main idea of #1039 is to keep the month state even when you reopen the app

> Could you store the preference as an offset instead of an absolute month?

This might work..

**Comment by MatissJanis** [comment]
> Could you store the preference as an offset instead of an absolute month?

This contradicts #1039. You navigate to Jan. Close the page. Open it tomorrow (a new month has arrived). You expected to see Jan, but you now see Feb. So IMO the current solution is better than storing an offset index.

> > but would reset to this month when you close & reopen the app

> I think the main idea of https://github.com/actualbudget/actual/issues/1039 is to keep the month state even when you reopen the app

Another option would be to store the month ONLY if it is in future or past. And if the selected month === current month - then do not store it (delete). Thus when a new month comes - the correct month stays visible.

**Comment by Miodec** [comment]
> > Could you store the preference as an offset instead of an absolute month?
> 
> This contradicts #1039. You navigate to Jan. Close the page. Open it tomorrow (a new month has arrived). You expected to see Jan, but you now see Feb. So IMO the current solution is better than storing an offset index.

Well, i dont think it contradicts #1039 - @youngcw mentions it would be nice to always see previous/current/future months. With the offset that would be possible, and it will work even when switching months.

**Comment by youngcw** [comment]
> Well, i dont think it contradicts #1039 - @youngcw mentions it would be nice to always see previous/current/future months. With the offset that would be possible, and it will work even when switching months.

Personally I would be ok if the view shifted as the month changed. That may not be the general consensus though.

**Comment by Kidglove57** [comment]
> > Well, i dont think it contradicts #1039 - @youngcw mentions it would be nice to always see previous/current/future months. With the offset that would be possible, and it will work even when switching months.
> 
> Personally I would be ok if the view shifted as the month changed. That may not be the general consensus though.

As indeed would I

**Comment by j-f1** [comment]
> Personally I would be ok if the view shifted as the month changed.

Agreed, worst case you’ll only need to move a month or 2 over

**Review by MatissJanis — APPROVED** [review]

**Comment by Miodec** [comment]
FYI I have not added the offset change. It still has the behavior @MatissJanis mentioned:

> Hmm.. so lets say I see only one month of budget. Currently it's June. My local pref will store it as June.
> I will open it up tomorrow. I would expect to see July. But I will still see June?

**Comment by MatissJanis** [comment]
That's fine. I don't need to agree with all the changes for things to get merged. If others like how it is, then it's totally fine to release :)

**Comment by j-f1** [comment]
Oh, didn’t realize that. I don’t feel super strongly either way but if you want to open another PR to make that change I would be happy to merge it.

**Pull request merged**
