### PR TITLE
Indicate Hidden Categories in autocomplete dropdown

### PR DESCRIPTION
**Pull request by Shazib**
### **CHOSEN SOLUTION**

On the transactions table, the hidden categories are not shown at all.

When used via `GenericInput` for filtering and reporting, the hidden transactions are shown in their own group

### **I could use some help figuring out why the tests are failing. I've tried replicating them in the browser and the data-id tags are present etc**

image

### CODE REVIEW

**Comment by shall0pass** [comment]
May be a dumb question..... Is there an elegant way to NOT show hidden categories in the account ledger/schedule/rules pages... But DO show them in the reports pages?

Reasoning :  I wouldn't expect to have hidden categories as options in the normal day-to-day pages, but I can definitely see the desire to be able to include them in reports.

**Comment by Shazib** [comment]
Exploring some of these options right now too.

I guess my concern is that older transactions that are tagged with hidden categories, if you accidentally change the category there isn't an easy way to get it back without un-hiding the category etc.

There is also the possibility that people just hide cateegories to 'de-clutter' the budget page vs using it to deprecate categories.

**Comment by shall0pass** [comment]
>There is also the possibility that people just hide cateegories to 'de-clutter' the budget page vs using it to deprecate categories.

Maybe... I find that idea foreign.

When the lock/reconciliation transactions PR is merged, it should be less likely to accidentally change categories since it will offer a warning to click past.

**Comment by joel-jeremy** [comment]
Not sure how easy it would be to implement , but another idea is to initially show a collapsed `Hidden` group on the bottom of auto complete and only show the hidden categories when the `Hidden` group is clicked.

**Comment by Shazib** [comment]
> Not sure how easy it would be to implement , but another idea is to initially show a collapsed `Hidden` group on the bottom of auto complete and only show the hidden categories when the `Hidden` group is clicked.

Probably outside my wheelhouse! We could go for an easy-win option 1/2 and open a separate feature ticket for the more advanced solution, as one of those options won't be a 'breaking' change

**Comment by youngcw** [comment]
> There is also the possibility that people just hide cateegories to 'de-clutter' the budget page vs using it to deprecate categories.

I think I would categorize this as bad behavior and not try to make it easier to get away with. 

Of the options you have up currently my favorites are 3 then 1. I also like @joel-jeremy idea with the possible addition of opening up the hidden list if there are no longer any valid non hidden options left.

**Comment by rich-howell** [comment]
> May be a dumb question..... Is there an elegant way to NOT show hidden categories in the account ledger/schedule/rules pages... But DO show them in the reports pages?
> 
> Reasoning : I wouldn't expect to have hidden categories as options in the normal day-to-day pages, but I can definitely see the desire to be able to include them in reports.

This was pretty much what I said over on discord, I don't know why hidden categories are even shown in the picker, there must be a flag somewhere to tell Actual they are hidden as they don't appear on the budget sheet, why can't that logic just be applied to this dropdown?

**Comment by Shazib** [comment]
I think what I will do is hide them entirely by default, with an optional flag to show them in the format of option number 4. 

I'll check that version in soon.

**Comment by ioslife** [comment]
> I think what I will do is hide them entirely by default, with an optional flag to show them in the format of option number 4.

Just realized this PR exists. This option is good. I made a PR to go ahead and hide them by default. #1914

**Comment by Shazib** [comment]
> > I think what I will do is hide them entirely by default, with an optional flag to show them in the format of option number 4.
> 
> Just realized this PR exists. This option is good. I made a PR to go ahead and hide them by default. #1914

I have already done this as part of this PR. I just haven't checked it in yet!

**Comment by Shazib** [comment]
Putting the legacy ideas here to keep the top PR comment clean now that an option has been chosen

### Previous Options

A number of options were discussed. I'm still working on trialing them all so watch this space!

Please comment your preferred view or other ideas you have. I hope to add screenshots of some other options shortly including a separate group at the bottom for all hidden categories.

1. Grey it out
image

2. Add '_(hidden)_' text
image

3. Separate section for all hidden categories at the bottom. 
image

4. As above with different styling? We can grey/italic etc.
image

There is technically nothing stopping you adding a category group called 'Hidden' so that might be confusing. Maybe we shoulse use an alternate text or something.

6. Just don't show them at all.

6. Show via one of the above options, but only on certain screens with an optional prop, otherwise default to not shown.

**Comment by youngcw** [comment]
Some thoughts:
1. It looks like this doesn't handle hidden category groups.  Those still show up as normal
2. Im conflicted on if its needed to treat the transaction edit drop down different.  By putting the hidden categories at the bottom of the list they are already mostly out of sight.  What if we just used the same organization in both the filter dropdown and transaction dropdown?

**Comment by shall0pass** [comment]
I would vote for option 7 with the view of option 2 in the reports.

I can't rationalize why someone would want to hide a category and then actively budget with it. I think hidden should mean hidden.

**Comment by Shazib** [comment]
> Some thoughts:
> 
>     1. It looks like this doesn't handle hidden category groups.  Those still show up as normal
> 
>     2. Im conflicted on if its needed to treat the transaction edit drop down different.  By putting the hidden categories at the bottom of the list they are already mostly out of sight.  What if we just used the same organization in both the filter dropdown and transaction dropdown?

RE your point 2, the general consensus seemed to be that people wanted them entirely gone on that screen. Happy to change it if people want to.

**Comment by youngcw** [comment]
> I would vote for option 7 with the view of option 2 in the reports.
> 
> I can't rationalize why someone would want to hide a category and then actively budget with it. I think hidden should mean hidden.

I like the idea of being able to see the hidden categories without needing to unhide them, but that is likely not that useful in practice, so Im ok either way on this.  I do think showing them in the options for reports and filters makes sense though because you may have used that category earlier in the year for example.

**Comment by Shazib** [comment]
From a coding POV, option 2 is much simpler to implement that the current option creating a totally separate heading, but people seemed to prefer 4 at the time.

Happy to make a change to option 2.

**Comment by youngcw** [comment]
fixes #1829

**Comment by carkom** [comment]
> I would vote for option 7 with the view of option 2 in the reports.
> 
> I can't rationalize why someone would want to hide a category and then actively budget with it. I think hidden should mean hidden.

I'd caution against making assumptions on other's usage of the software just because it doesn't match your usage. Example: someone may have a category that is the same every month. They aren't concerned about seeing it because it never changes. They want it calculated into the budget but don't need to see it. Their solution could be to hide it but still actively budget with it calculated in.

**Comment by carkom** [comment]
I'd agree with the "option 2" concensus. Would it make sense to combine option one and two? Gray it out and write (hidden) next to it?

Is the plan to apply this to hidden groups as well?

**Comment by shall0pass** [comment]
> I'd caution against making assumptions on other's usage of the software just because it doesn't match your usage. Example: someone may have a category that is the same every month. They aren't concerned about seeing it because it never changes. They want it calculated into the budget but don't need to see it. Their solution could be to hide it but still actively budget with it calculated in.

I see. In my case I have some categories I used years ago, for example a Baby category. I have no intentions of using this category again, but yet it still exists. When the option to hide a category was introduced, it was presented in a way that you wouldn't have to move your category out of the group and it would still reflect in the proper place in the reports. I have no wish to see the category in the normal picker, but with only option 2 being selected it will always be there. If this is the path chosen, I'll have to make a choice and I'll probably opt to move those categories back into a 'hidden' group at the bottom and deal with the reports differently. I think it's going to feel like a half finished idea that needs a workaround to feel right. My 2¢.

**Comment by carkom** [comment]
> On the transactions table, the hidden categories are not shown at all.

Wait is there some setting I'm missing? My local is not behaving as above. They all appear the same to me.

Budget List:
image

Transactions List:
image

Edit Transaction Dropdown:
image

Filter Dropdown:
image

**Comment by carkom** [comment]
> I see. In my case I have some categories I used years ago, for example a Baby category. I have no intentions of using this category again, but yet it still exists. When the option to hide a category was introduced, it was presented in a way that you wouldn't have to move your category out of the group and it would still reflect in the proper place in the reports. I have no wish to see the category in the normal picker, but with only option 2 being selected it will always be there. If this is the path chosen, I'll have to make a choice and I'll probably opt to move those categories back into a 'hidden' group at the bottom and deal with the reports differently. I think it's going to feel like a half finished idea that needs a workaround to feel right. My 2¢.

Do you not currently see those hidden categories in the category dropdown autocomplete for the transactions list? I can currently see all my hidden categories and groups in the autocomplete dropdowns for every place they are used in the app.

**Comment by shall0pass** [comment]
> Do you not currently see those hidden categories in the category dropdown autocomplete for the transactions list? I can currently see all my hidden categories and groups in the autocomplete dropdowns for every place they are used in the app.

I do see them in the drop down list.  Personally, I think that's design mistake.  If I hide a category, with special exceptions (reports), I would expect those categories to be hidden throughout the app.  Leaving them in the picker list seems like we can't decide if we are really committed to hiding something, which is kind of silly since it's easy to unhide it.

**Comment by carkom** [comment]
> I do see them in the drop down list. Personally, I think that's design mistake. If I hide a category, with special exceptions (reports), I would expect those categories to be hidden throughout the app. Leaving them in the picker list seems like we can't decide if we are really committed to hiding something, which is kind of silly since it's easy to unhide it.

I agree with you. However, we need to enable a way to find those transaction easily and I think the proposed solution is trying to do that.

In your budget, you've hidden a "Baby" category you don't use anymore. What would you do if, for some reason, you needed to look up a transaction from a year ago that is in that category. You'd have to go to budget list, unhide it then go to the transaction list and filter to find it then back to budget list to re-hide it.

**Comment by carkom** [comment]
> > I do see them in the drop down list. Personally, I think that's design mistake. If I hide a category, with special exceptions (reports), I would expect those categories to be hidden throughout the app. Leaving them in the picker list seems like we can't decide if we are really committed to hiding something, which is kind of silly since it's easy to unhide it.
> 
> I agree with you. However, we need to enable a way to find those transaction easily and I think the proposed solution is trying to do that.
> 
> In your budget, you've hidden a "Baby" category you don't use anymore. What would you do if, for some reason, you needed to look up a transaction from a year ago that is in that category. You'd have to go to budget list, unhide it then go to the transaction list and filter to find it then back to budget list to re-hide it.

Wait, hold on. I was just tinkering with this statement and noticed you can just use the search bar to find hidden items in the transactions list.

So I'll update my opinion, I think it should be hidden everywhere (filter list and reports).

Reports can enable a choice to show/hide if we so choose but that can be decided upon for each report (not part of this PR).

**Comment by Shazib** [comment]
So, the approach of, hidden by default (not shown at all), with a prop flag to enable them, in the style of option 2:

279205576-00e9d6c1-520f-4891-a5e2-293b1ebb9185

Is this something we can all get behind.

They won't be shown at all anywhere, unless a specific screen or report passes a flag to the autocomplete control to show them, in which case they get the '_(hidden)_' text?

**Comment by youngcw** [comment]
> Is this something we can all get behind?

I believe there is a general consensus on that style and to have everything hidden by default.  It may be beyond the scope of this PR to decide where to show the hidden ones.

**Comment by Shazib** [comment]
> > Is this something we can all get behind?
> 
> I believe there is a general consensus on that style and to have everything hidden by default. It may be beyond the scope of this PR to decide where to show the hidden ones.

Yep, I will include the ability to show but won't turn it on anywhere

Thanks

**Comment by ioslife** [comment]
Looks great. Thanks for doing the work here, @Shazib!

**Comment by carkom** [comment]
> So, the approach of, hidden by default (not shown at all), with a prop flag to enable them, in the style of option 2:
> 
> Is this something we can all get behind?
> 
> They won't be shown at all anywhere, unless a specific screen or report passes a flag to the autocomplete control to show them, in which case they get the '_(hidden)_' text?

What do you think about making the category name gray as well? This would help support the visual that these categories are hidden.

**Comment by ioslife** [comment]
@Shazib are the tests the only thing holding this up?

**Pull request closed without merging**
