### PR TITLE
make BudgetTable Budgeted value positive on mobile

### PR DESCRIPTION
**Pull request by tim-smart**
To match the desktop behaviour.

### CODE REVIEW

**Comment by tim-smart** [comment]
Hmm vrt should have failed.

**Comment by joel-jeremy** [comment]
> Hmm vrt should have failed.

Agreed Do you mind checking the VRT why it's not failing? It should be in `budget.mobile.test.js` file.

**Comment by youngcw** [comment]
My guess is that since the change is so small it came in under the threshold of allowed difference.

**Comment by tim-smart** [comment]
Temporarily dropping the threshold did the trick.

**Review by joel-jeremy — APPROVED** [review]

**Pull request merged**
