### PR TITLE
Add a netlify.toml file with the COOP/COEP headers

### LINKED ISSUE #596: [Bug]: old budget files getting deleted
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

https://actualbudget.netlify.app/

1. create a test file (with demo data)
2. close
3. create a new EMPTY file
4. close
5. open the new DEMO file
6. it's empty 🤔

**This issue might exist only in the offline version of the product. It _might_ not exist in the versions that sync files with a backend server.** Either way - this is a pretty bad bug that we should address ASAP.

### What error did you receive?

Previous budget files get deleted when a new one is created.

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

_No response_

### Operating System

None

### PR DESCRIPTION
**Pull request by j-f1**
Does not fix #596, but we should definitely have these headers

### CODE REVIEW

**Comment by rich-howell** [comment]
This didnt fix #596

**Review by MatissJanis — APPROVED** [review]
Looks like the change fixed it for Netlify. Thanks Jed

**Comment by j-f1** [comment]
@rich-howell Can you re-verify? I didn’t actually fix it the first time since Netlify didn’t pick up the config file.

**Comment by j-f1** [comment]
This should be fixed on future Netlify builds.

**Pull request closed without merging**
