### PR TITLE
SpendingReport: Fixing some display issues

### PR DESCRIPTION
**Pull request by carkom**
Fixing display issues in spending report and adding a legend.

### CODE REVIEW

**Review by matt-fidd — DISMISSED** [review]

**Review by matt-fidd — DISMISSED** [review]
LGTM!

**Comment by matt-fidd** [comment]
Retriggered VRT just to make sure it's a flake

**Comment by matt-fidd** [comment]
> Retriggered VRT just to make sure it's a flake

Doesn't look like it, is VRT passing locally?

**Comment by carkom** [comment]
> > Retriggered VRT just to make sure it's a flake
> 
> Doesn't look like it, is VRT passing locally?

Fixed

**Pull request merged**
