### PR TITLE
:recycle: (reports) unify selectedCategories and conditions

### PR DESCRIPTION
**Pull request by MatissJanis**
TODO:
- [x] migration to move existing filters from `selectedCategories` to `conditions`
- [x] hide simple category selector if complex category filters are used

### CODE REVIEW

**Comment by MatissJanis** [comment]
Demo budget with 3x custom reports (to test if the migration works as expected):

[2024-08-03-Test Budget.zip](https://github.com/user-attachments/files/16482913/2024-08-03-Test.Budget.zip)

**Review by carkom — APPROVED** [review]
This looks pretty thorough. From the functionality and UI to the migration that catches existing reports, it LGTM!

Very well done bit of code - thanks for tidying up my mess!

**Comment by psybers** [comment]
image

I would probably drop the word `simple` from that message.

Is it possible to make 'remove active category filters' into a link, that would remove those filters (so you don't have to go click the X, or possibly several X's)?

**Comment by MatissJanis** [comment]
> I would probably drop the word `simple` from that message.

Makes sense. Updated :+1:

> Is it possible to make 'remove active category filters' into a link, that would remove those filters (so you don't have to go click the X, or possibly several X's)?

It's certainly possible and would be nice, but for such destructive actions we should also have the ability to easily perform a "undo". Adding such logic would be quite a bit of overhead, so I will leave that out of scope for now.

**Review by carkom — APPROVED** [review]

**Pull request merged**
