### PR TITLE
Change method of calculating 'by' matches to use averaging

### PR DESCRIPTION
**Pull request by shall0pass**
I've changed the method of calculating the budgeted amount.  There may be a more efficient way of writing the loop, so I'm looking forward to the review.

This change implements the mathematics of (Target1+Target2+TargetN-Last_months_category_balance) / (MonthsRemaing1 + MonthsRemaining2 + MonthsRemaingN) * N.  This is an averaged approach for multiple templates in the same category.  It will appear to overbudget or underbudget some months compared to multiple single targets in different categories, yet there should always be enough saved in the category to satisfy the target due.

Setting a target, it's assumed that money will be spent in the appropriate month, When a target reaches maturity, the money in the category associated with that target should be spent or moved so the remaining targets continue to be funded.  I don't see an easy way of fixing that, but I hope this change will be of some help.

Current method:
Notice how the Bills (flexible) category reduces each month, resulting in larger budgeted amounts later in the goal cycle.

Templates-now

Proposed method:
**Note: The fact that the initial fill in this example equals the expected fill is a coincidence based on the template values I chose.  The initial fills can be different from expected fill.

Templates-proposed

### CODE REVIEW

**Comment by Kidglove57** [comment]
Thanks for doing this so quickly. Most of the examples I gave at #860 now seem to work as I would expect. 
Here are a couple of examples to illustrate one I was not so sure about. In each case I am doing my fill in May '23:
**Example 1:**
#template 1200 by 2024-04
#template 600 by 2024-04
This correctly gives my expected fill of 150pm and does so consistently as I fill subsequent months. Additionally, if I put 120 in April, to bring forward, the fill correctly reduces from May onwards to 140pm.

**Example 2**
#template 1200 by 2023-10 
#template 1200 by 2024-04
Here I expected a monthly fill of 300 (200 for six fills and 100 for twelve fills)
However, instead, I am given 266.67

As you mentioned elsewhere the accumulated funds need to be spent, or moved out in the target month, for the ongoing fills to work.

I also started some testing using the "repeat every year" in the template and so far this worked on simple examples as expected - again so long as the funds are spent or moved out in the target month so as to start accumulating for the new year

**Comment by shall0pass** [comment]
You are again correct.  This method tends to "even out" all of the budgeted amounts.
The 'before this PR' math looks like this  (and example of 2 templates):

original

This works great for the 1st month, but quickly falls apart in subsequent months.  I put the 'f' in there as a factor.  The currently implemented version uses a factor of 1.  In your example of 1200 over 6 months and 1200 over 12 months, it's obvious that the two factors should be 1/3 and 2/3 to achieve the 200 and 100 components to get 300.  We can easily derive this in the first month from 6/(12+6) and 12/(12+6) using months remaining variables.  But, in the 2nd month our months remaining are 5 and 11.  It's no longer obvious how to determine what the factors should be using the information available of 2x 1200 spending goals of terms 5 and 11 months with 300 currently saved.  Maybe you'll see something I don't here?

The proposed method in this PR uses (an example of 2 templates):

new

Here we don't need to know the ratio of the components added and we aren't over correcting with the category balance since it is applied to the sum of the targets rather than each individual target.  As I said earlier, it tends to even out the budgeted amounts.  If there is a difference in target amounts and target dates, it will slightly underfund during part of the year and overfund in the remainder when the 1st target is met (or vice versa depending on which amount is due first).

I'm not sure this is the answer, but I think it's better than what is currently implemented.  Happy to hear more opinions and I won't be upset at all if everything gets reverted back to sequential.  Maybe someone will see the pattern I can't put my finger on to solve this in an expected way.

**Comment by Kidglove57** [comment]
"_As I said earlier, it tends to even out the budgeted amounts. If there is a difference in target amounts and target dates, it will slightly underfund during part of the year and overfund in the remainder when the 1st target is met (or vice versa depending on which amount is due _first)_"
Ah got it! Light bulb moment. I have to really think hard about the maths, it does not come naturally to me. Using my example, and filling forward i.e.:
#template 1200 by 2023-10
#template 1200 by 2024-04
I can see that we get to 1200 in April 2024 (having transferred out 1200 in Oct 23) and I agree that the "uneven" funding is still much better than what we have at the moment! It also works well in a "repeat every year" template.

Nice one - I will be interested in other views but this certainly seems to be as good as we are going to get (and, very importantly, better than other apps have managed to achieve!!)

**Comment by shall0pass** [comment]
I think I found it!   If I subtract N in the denominator only if N>1, the amounts are what you would expect.  It'll be tonight (~12 hours) before I can try it in the code, but it looks promising on my calculator.

**Comment by Kidglove57** [comment]
Well done! Im on UK time so will test in the morning.

**Comment by shall0pass** [comment]
Foiled again.  It worked for some templates, but not others.  The current version is still the best result I've gotten.  It's interesting that it works properly if both templates contribute the same amount per month to the target but not if the individual contribution is different.  I know that's a clue.

**Review by j-f1 — APPROVED** [review]

**Pull request merged**
