### PR TITLE
Warning Color Consolidations

### PR DESCRIPTION
**Pull request by carkom**
Consolidating and making more consistent the warning and upcoming colors.

### CODE REVIEW

**Comment by youngcw** [comment]
The warning notification seems harder to read now.  Was that change intentional?

**Comment by carkom** [comment]
> The warning notification seems harder to read now. Was that change intentional?

No, not intending to make anything harder to read...

I only changed any given warning text/background by one shade in either direction in order to try to normalize it across the app. But I can see that in the case you mention the background was one shade darker and the text was one shade lighter, decreasing contrast in both situations, this is not desirable. I've adjusted it a bit. Can you see if it's better? If not, how do you think we should change it? Darker text? Lighter background?

**Comment by carkom** [comment]
@youngcw, can you see if my changes work better? Cheers!

**Comment by youngcw** [comment]
Its better.  I think I'll still defer to @MatissJanis since its a visual change

**Comment by MatissJanis** [comment]
👋 Sorry for the slow review.

Would you mind updating the VRT screenshots to make CI pass? The updated screenshots will make reviewing this a bit easier since I'll be able to catch most of the changes by just looking at the images instead of manually looking at them in the app.

**Comment by carkom** [comment]
> 👋 Sorry for the slow review.
> 
> Would you mind updating the VRT screenshots to make CI pass? The updated screenshots will make reviewing this a bit easier since I'll be able to catch most of the changes by just looking at the images instead of manually looking at them in the app.

Hey, I tried to update VRT screenshots a bunch of times but couldn't get it to work. Realized I wasn't getting any VRT errors on my local. Re-ran checks on github and they all passed. So this one is ready to go!

**Comment by MatissJanis** [comment]
The new yellow color blends too much with the background. What if we swapped it the other way around: make the darker tone the one we use instead of the faded?

| before | after |
|--------|--------|
| Screenshot 2023-11-05 at 14 50 59 |Screenshot 2023-11-05 at 14 51 04 |
| Screenshot 2023-11-05 at 14 50 54 | Screenshot 2023-11-05 at 14 50 50 |

**Comment by carkom** [comment]
I agree, seems off. I've adjusted the background back to the darker one and changed the text areas that were experiencing poor contrast issues. Have a look!

**Comment by carkom** [comment]
> The new yellow color blends too much with the background. What if we swapped it the other way around: make the darker tone the one we use instead of the faded?

I agree, seems off. I've adjusted the background back to the darker one and changed the text areas that were experiencing poor contrast issues. Have a look!

**Review by MatissJanis — APPROVED** [review]
LGTM!

**Comment by carkom** [comment]
Fixes #1870

**Comment by carkom** [comment]
Fixes #1869

**Comment by carkom** [comment]
Fixes #1807

**Comment by carkom** [comment]
Fixes #1806

**Comment by carkom** [comment]
Fixes #1805

**Pull request merged**
