### PR TITLE
Allow schedules to skip weekends

### PR DESCRIPTION
**Pull request by pole95**
This PR adds a toggle to allow schedules to skip weekends, and define a solution strategy when a schedule next occurs during the weekend.

### CODE REVIEW

**Comment by pole95** [comment]
Yep, forgot to add the logic in the upcoming dates function as well, should be working now.

**Review by shall0pass — COMMENTED** [review]
This is awesome!  It's definitely I'll feature I'll be using.  I'll let someone else do the code review, but I'm very excited this will be a feature of Actual!🎉

**Comment by joel-jeremy** [comment]
This is an awesome feature! I'm looking forward to use it myself.

Just a few comments: 
- The `Skip Weekends` checkbox resizes/moves when checked

- What do you think about changing the option from `Skip weekends` to `Move schedule [before/after] weekends` with the `[before/after]` being a dropdown/radio buttons e.g.
  image

- With the number of checkboxes growing, the schedule modal is starting to look crowded, how do feel about grouping all these options together? Maybe hide them initially in a `Options...` dropdown menu and show the checkboxes (maybe in a popover) when clicked?
image

**Comment by pole95** [comment]
Thanks, I'm really not great in terms of UI/UX. I've implemented your suggestions: 
image
image

If anyone else has other suggestions/improvements for the UI, I'm glad to implement them to the extent of my mediocre frontend capabilities

**Comment by kyrias** [comment]
I feel like it would make more sense if that option was in the actual date selection modal.  Other than that I like it!

**Comment by joel-jeremy** [comment]
I agree that having the option in the date selection modal/popover is a great idea! In that case, you can disregard my comment about hiding the options.

One last thing, I believe Actual uses sentence case throughout the app. Can you update the option to sentence case?

**Comment by pole95** [comment]
Thanks for your suggestions, I integrated the switch into the `RecurringSchedulePicker`.

**Comment by shall0pass** [comment]
Amazing 🎉

**Comment by joel-jeremy** [comment]
This is awesome. Thank you!

**Review by joel-jeremy — APPROVED** [review]

**Pull request merged**
