### PR TITLE
🌶️ Emojis 💲

### PR DESCRIPTION
**Pull request by biohzrddd**
Let's spice things up a bit. 

Add emojis to the test budget: budget and account names. 🚀🚀🚀

Besides the dollar signs (which I think is fairly universally known) these are pretty generic emojis so should make everyone happy.

### CODE REVIEW

**Comment by biohzrddd** [comment]
FYI the snapshot checks are failing because I changed the name of categories. We'll need to update the snapshot somehow.

**Comment by joel-jeremy** [comment]
Just a small nit: maybe add a space between the emoji and the name? :smile:

**Comment by TomAFrench** [comment]
@biohzrddd If you run the tests with the `--updateSnapshot` then that should update the snapshots. You can commit those to get CI passing.

**Comment by biohzrddd** [comment]
> @biohzrddd If you run the tests with the `--updateSnapshot` then that should update the snapshots. You can commit those to get CI passing.

@TomAFrench sorry I'm a bit new to testing, I need more explicit instructions. I tried `yarn test --updateSnapshot` but that didn't work (and hung after crdt tests).

**Comment by biohzrddd** [comment]
> @biohzrddd If you run the tests with the `--updateSnapshot` then that should update the snapshots. You can commit those to get CI passing.

@TomAFrench sorry I'm a bit new to testing, I need more explicit instructions. I tried `yarn test --updateSnapshot` but that didn't work (and hung after crdt tests).

**Comment by MatissJanis** [comment]
👋 Hey!
Just checking if if there are plans to pick this up again. Currently the CI checks are failing.

**Pull request closed without merging**
