### PR TITLE
Switch to dnd-kit for drag and drop

### PR DESCRIPTION
**Pull request by joel-jeremy**
Main goal of the switch is to have a usable drag-and-drop functionality in mobile.

### CODE REVIEW

**Comment by joel-jeremy** [comment]
Yeah, also hoping this fixes drag and drop in mobile as well.

**Comment by Teprifer** [comment]
Firefox 121.0.1 (64-bit) (on desktop)
Imported my budget from latest live.

Easily reproduced error doing dragging and drop of categories although I'm not sure on the *exact* steps as there seems to be some volatility..
I was grabbing a category, waving it around a bit, and then would grab another and it'd frequently crash then. Sometimes after reloading the page after a crash it'd crash as soon as I grabbed a category.

Show error from actual: 

`A@https://deploy-preview-2239.demo.actualbudget.org/static/js/wide.XKheaPwd.chunk.js:1:20791 Hye</</<@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:202:30058 U1@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:36944 Hye</<@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:202:30025 Cg@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:24270 yl@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:42398 Kk@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:36612 Ta@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:49:3279 gB@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:41273 La@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:40265 SD@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:35722 I@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:36:1545 R@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:36:1903 `

Browser console:
image

Same idea but crashing as soon as I moved a category after reloading:

`A@https://deploy-preview-2239.demo.actualbudget.org/static/js/wide.XKheaPwd.chunk.js:1:20791 Hye</</<@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:202:30058 U1@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:36944 Hye</<@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:202:30025 Cg@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:24270 yl@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:42398 Kk@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:36612 Ta@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:49:3279 gB@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:41273 La@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:40265 SD@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:51:35722 I@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:36:1545 R@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:36:1903 EventHandlerNonNull*@https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:36:2069 @https://deploy-preview-2239.demo.actualbudget.org/static/js/index.-47GFWev.js:36:3805 `

image

**Comment by joel-jeremy** [comment]
Thank you @Teprifer for catching that! The screenshots were also very helpful. I have pushed a commit which hopefully fixes the issue :)

**Comment by youngcw** [comment]
something is weird with the sidebar account sorting.  If I try to move an account by one place it usually doesn't move to the right location.  Moving up seems to work better than moving down.  Moving categories seems to work perfect

**Comment by joel-jeremy** [comment]
@youngcw Accounts sorting should be working fine now :)

**Comment by youngcw** [comment]
@joel-jeremy Im still seeing the same issue.
To recreate
1. make a test file
2. try to move the "Ally Savings" account down 1.  Nothing happens
3. Try to move it somewhere else, it moves to the bottom
4. It can now be moved anywhere higher than the current position
5. try to move down again, it goes to the bottom

**Comment by joel-jeremy** [comment]
The same problem seem to exist in the latest release version of Actual Budget and only happens with a fresh test budget. We might need to look at how the test file inserts the sort order of the accounts, but we should probably fix that in a separate PR.

**Comment by youngcw** [comment]
> The same problem seem to exist in the latest release version of Actual Budget and only happens with a fresh test budget. We might need to look at how the test file inserts the sort order of the accounts, but we should probably fix that in a separate PR.

I do see it if I import one of my budget files, but it is less broken.  I can move the accounts around a bit before they decide to jump to the bottom.  Since this issue is existing, I think its fine to ignore in this PR.

**Comment by rich-howell** [comment]
> @joel-jeremy Im still seeing the same issue. To recreate
> 
> 1. make a test file
> 2. try to move the "Ally Savings" account down 1.  Nothing happens
> 3. Try to move it somewhere else, it moves to the bottom
> 4. It can now be moved anywhere higher than the current position
> 5. try to move down again, it goes to the bottom

I can replicate this on the demo file in the deploy PR

- Move Ally Savings down 
- Nothing Happens
- Move Ally Savings down
- It goes to the bottom
- Move it back to the top
- It goes to the top
- Move it down one row
- it now moves down one row

**Comment by joel-jeremy** [comment]
Upon further investigation, it looks like importing / creating test budget incorrectly sets the `sort_order` to the same value on all the imported accounts. This exists in the latest release version / edge. We should create a separate issue to track the fix for that.

**Comment by Teprifer** [comment]
Seeing the same weird behaviour with Ally Savings in the demo budget as per above steps.

Minor/irrelevant notes:
When dropping a dragged category or account it does a weird hoppy animation. Groups don't do this if they're collapsed first - you can't tell if this occurs when they start as expanded since there's an animation as they return to being expanded.

Is it meant to have "Group:" prepended when dragging a group around? (if not, wouldn't bother fixing)
image

Groups staying collapsed if they start collapsed when dragging begins, and staying expanded if expanded originally is good.

I can't think why you'd even look at fixing this, but for fun:
1) Grab a group, they all collapse (presumably to make it easier to move around 👍)
2) Alt-tab or otherwise lose focus from the browser window.
3) Click on another tab.
4) The group is placed where it last went due to mouse movements, but the groups stay collapsed.

**Comment by joel-jeremy** [comment]
@Teprifer I have added a bit of delay before expanding back the category groups. Animation should be smoother now.

I also have updated the accounts in the mobile accounts page to be sortable.

**Comment by joel-jeremy** [comment]
Created https://github.com/actualbudget/actual/issues/2264 for the account sorting bug.

**Comment by Teprifer** [comment]
> @Teprifer I have added a bit of delay before expanding back the category groups. Animation should be smoother now.
> 
> I also have updated the accounts in the mobile accounts page to be sortable.

It wasn't what I meant, but that added delay feels really good, creates a nice continuity feeling from drop -> see placement -> UI restores to expanded view, so keep it. :)

I was referring to when you let go of a category or account, the one you're holding jumps up and down a bit, before it settles in to place. This weird hopping animation doesn't happen with groups.
Mobile moving accounts has the same hopping animation.

Seems to be it tries to go where it originally was, then immediately goes to where you'd placed it.

Minor visual issue on mobile accounts, the account that is moved retains the selected/mouse-over highlight after being moved.
Oddly sometimes it doesn't happen, and sometimes I've been able to drag and drop, that one retains the highlight, then I could drag and drop another one, while the highlight remained on the first.

This only occurred on an actual mobile device using a finger to tap & hold, when resizing on desktop to the mobile size this doesn't happen because the mouse cursor is over the one that was moved.

**Pull request closed without merging**
