### PR TITLE
chore: enforce proper types in `sync/index`

### PR DESCRIPTION
**Pull request by TomAFrench**
I've updated the return values in `sync/index` to  sensible values based on how they're being called.

I've updated the type of `msg.value` to be `string | number | null` to match the values expected by `serializeValue`

### CODE REVIEW

**Comment by MatissJanis** [comment]
👋 Looks like the e2e tests are failing. Smells like this is not just a type change, but some functionality has changed too. Would you mind taking a look?

**Comment by MatissJanis** [comment]
Hey! Just checking in: how's this going? Did you see my last message?

I'd be very excited to get this merged as long as it doesn't break things and CICD passes.

**Comment by TomAFrench** [comment]
Hey @MatissJanis, sorry I only saw these messages recently (I'm travelling currently plus github notifications tend to be a bit of an unending stream). I've merged in the changes from master and the e2e tests seem to have fixed themselves. I'm not sure if they were just being flakey or some of the changes from master helped fix it.

Unfortunately, I've only got my laptop with me so I can't do a huge amount of extra investigation (If I run the debug builds on my laptop then it starts really chugging).

**Review by j-f1 — APPROVED** [review]

**Review by MatissJanis — APPROVED** [review]

**Comment by MatissJanis** [comment]
Thanks!

**Pull request merged**
