### PR TITLE
Forcibly reload app from server when API is redirected

### PR DESCRIPTION
**Pull request by TimQuelch**
This adds a wrapper around fetch so the application is reloaded when an API request is redirected. The motivation for this is as a workaround for the bug in #2793.

This issue occurs when using forward authentication with something like authentik with a proxy (e.g. caddy, traefik). The proxy checks with the auth service whether all requests to the host are valid, if they are they are forwarded onto the backend server (in this case actual server). If the request is invalid e.g. the cookie has expired or the user has not authenticated yet, then the proxy redirects the user to the authentication page. After authenticating they are redirected back to what they were originally requesting.

For a more standard application; after a authenticatoin cookie has expired the next time the page is reloaded it would redirect to the auth page in order for the user to re-authenticate. However actual uses a service worker pattern where the application code is cached and all requests are served by the worker. This means that reloading the page in the browser does not actually result in a http request to the backend server; which means that that request cannot be redirected to authenticate. This results in an invalid authentication session and API queries to the backend failling because they are redirecting to auth pages.

~This PR adds a button in the advanced settings section that un-registers the service worker handling the routing and then reloads the page. This forces the page to be requeried from the backend server which is then able to be redirected to the authentication page.~

I've tested this functionality on web, mobile browser, and also iphone PWA and it works as expected.

I've got a couple things I want to check on my implementation:
- ~This functionality isn't relevant on electron. I have followed the pattern that the [ResetSync](https://github.com/actualbudget/actual/blob/af5fd5b3efeef1628ad583b661fa0539d4d0f63e/packages/desktop-client/src/components/settings/Reset.tsx#L65-L77) follows by disabling the button if we're on electron. I considered also completely hiding the setting when on electron. Which would be preferable?~
- [this page](https://actualbudget.org/docs/contributing/project-details/advice) mentions that changes to global.Acutal are somewhat fragile. Basically what I've done is defined the new reload function only in the browser version and typed it as maybe undefined. We check if it is defined before trying to call it; this means that on electron it won't be called. Is this the correct way to go about this?

~I couldn't think of a solution that was less of a workaround than this. Maybe this reloading could be triggered if an API query gets a 302 to a configurable path? e.g if `/sync/sync` gets redirected uselessly to `auth.mydomain.com` then we trigger reloading the whole app so that the user can re-auth? I feel I don't know the full consequences of this solution though. Does anyone have any thoughts on a more automatic solution that will work in a general and/or configurable way?~

Edit: After feedback I re-implemented the solution to wrap the API fetch so that if any API call is redirected the application is reloaded.

### CODE REVIEW

**Comment by StefanFabian** [comment]
I found this because I have the same issue with Authelia and Actual.
Why did you decide against just handling every 302 on API requests and executing the 302?
I would assume that the user is in control of the server hosting Actual, so all 302 requests will probably happen for a reason, and IMO, that would be a cleaner way of handling that than having to do it manually.

**Comment by alexyao2015** [comment]
Could we do something like this? I run silverbullet as well and it seems like they were able to solve the issue by just setting `location.href` to the redirected url.

https://github.com/silverbulletmd/silverbullet/blob/main/common/spaces/http_space_primitives.ts#L42-L65

**Comment by TimQuelch** [comment]
Reloading when an API query gets a 302 would work for my setup (and I'd guess many other people's), however there are probably many valid setups where a 302 is normal and the correct action is to just follow the redirect.

Can we be confident that any time a 302 is returned that we need to reload? Maybe I a configuration setting which has this automatic reloading as an optional feature?

**Comment by TimQuelch** [comment]
Maybe an option where you can configure hosts that if we get redirected to one of those hosts we reload?

In this case any time I get a redirect to auth.mydomain.com I want to reload

**Comment by alexyao2015** [comment]
I don't see why any config would be necessary. If you make a request to a trusted destination and the request is calling for you to be redirected, you should redirect. You don't even need to handle redirects I think. As long as your proxy sends a redirect call, it should just directly redirect you without prompting. That's how normal webpages without service workers would react anyways.

**Comment by StefanFabian** [comment]
> Reloading when an API query gets a 302 would work for my setup (and I'd guess many other people's), however there are probably many valid setups where a 302 is normal and the correct action is to have the API follow the redirect and return the redirected response normally.
> 
> Can we be confident that any time a 302 is returned that we need to reload? Maybe a configuration setting which has this automatic reloading as an optional feature?

A whitelist would also be an option but as this is a common problem with reverse proxies + auth, I think having to first figure out what's wrong and then find the solution would be a bit annoying to users.

As I see it, there are two common behaviors that can happen when you get a 302:

1. Your browser sends an options request and the reply doesn't have the correct CORS headers
  * Should you redirect to the page in that case? I think this will be the default case unless someone already configured their auth server to return `Access-Control-Allow-Headers: *` since actual will send the following access control request `Access-Control-Request-Headers: x-actual-token` with the options request.
2. The options request passes and the API follows the 302 successfully
  * If it is just an API redirect, the data should still be valid JSON. For an auth server, the JSON parsing would fail and we could use that as an indication that we should redirect to the 302 page.
    Maybe first verify that the returned data is HTML?

**Comment by jfdoming** [comment]
> I'm happy to implement doing this automatically when an API request gets a 302 if maintainers agree that is appropriate. My initial design was erring on the side of not breaking existing setups.
> 
> > If you make a request to a trusted destination and the request is calling for you to be redirected, you should redirect. You don't even need to handle reloading I think. As long as your proxy sends a redirect call, it should just directly redirect you without prompting. That's how normal webpages without service workers would react anyways.
> 
> The problem is only api requests get redirected. GET requests for the page itself get served by the service worker with cached code and therefore do not get redirected.
> 
> > Another point to consider is that some auth solutions pass the return URL to the auth page.
> > If we just set the location to the redirect URL, after authentication, it would redirect the user to the result of an API call, which doesn't make sense.
> 
> I agree, we do not want to follow the 302 that originates from the API request because after authentication finishes we'd be redirected back to the api call; not the app. Instead we'd want to force a uncached GET the current page and follow the resulting redirect.
> 
> > Is there a way to fetch the current URL without the service worker catching the request and serving it from the cache?
> > In that case, we could use that after determining that authentication is required.
> 
> The way I've figured out how to do that is by unregistering the navigation service worker and reloading. This is what I do in my `reload` function now. I'm open to other suggestions on how to do this. My understanding of service workers is fairly limited.

I think the approach needed here would be to change the service worker logic to stale-while-revalidate, which causes it to still fetch in the background if there is a connection. That way we can handle the background fetch and redirect if it returns 302. I'm on board with just redirecting unconditionally for now; if someone does start using a setup where the redirect isn't an auth request, we can help them at that time.

Another thing worth noting is that IIRC one of the first things the app does when it loads is make an API request to check if the server has been initialized. Assuming my memory is correct, maybe handling only API requests is fine?

**Comment by alexyao2015** [comment]
> Your browser sends an options request and the reply doesn't have the correct CORS headers

In this case, nothing happens since the redirect url cannot be determined.

> change the service worker logic to stale-while-revalidate
It's probably better to use network first. Stale while revalidate would work but only on the second request since it pulls from the cache first.

**Comment by alexyao2015** [comment]
Looking at the config, it seems like no runtime caching is being performed right now. Presumably, all you would need to do is handle the redirect that the service worker returns. A slight disadvantage is the return url would likely be an API call. I suppose if you unregister the service worker and remake the request, that will direct the user to the right place. I'm just not sure of the implications of unregistering the service worker.

https://github.com/actualbudget/actual/blob/master/packages/desktop-client/vite.config.mts#L155

**Comment by TimQuelch** [comment]
I've added functionality to automatically reload when an API call gets redirected. Please let me know if there's anything to improve

**Comment by alexyao2015** [comment]
Is the reload button on settings even needed still? Can that be removed?

**Comment by TimQuelch** [comment]
Yes. I've now removed the setting and updated the release notes.

**Comment by alexyao2015** [comment]
LGTM but I'll let someone with more familiarity take a look at the code. The PR description also need an update as well.

**Comment by AWare** [comment]
hi, this pr would be incredibly useful to me as I also run mine behind an authenticated gateway.
the implementation looks sensible, but I'm not a contributor.

if I can be of help here, I'd be happy to- but otherwise I'm just chiming in with thanks to @TimQuelch

**Comment by TimQuelch** [comment]
At this point it is ready for review and just waiting for a maintainer to have the time to take a look. 

I've been running this branch on my instance for several weeks now with no issues.

**Comment by alexyao2015** [comment]
Is there an easy way to run this in container or do you need to run an entire build process to get that?

**Comment by TimQuelch** [comment]
> Is there an easy way to run this in container or do you need to run an entire build process to get that?

This is the dockerfile that I use to run the actual server with specific versions of actual https://gist.github.com/TimQuelch/8f794cf187eeabb24d6eaee278e3ba38

It is somewhat based on the the actual server edge images https://github.com/actualbudget/actual-server/blob/master/docker/edge-alpine.Dockerfile

**Comment by matt-fidd** [comment]
@coderabbitai full review

**Comment by jfdoming** [comment]
One concern I thought of with this approach is that the user could get stuck in a reload loop if the server sends a 302 to only API resources (if someone forgets to put the JS bundle behind a proxy). Maybe that is not a realistic scenario but thought it was worth mentioning the possibility

**Comment by TimQuelch** [comment]
> user could get stuck in a reload loop if the server sends a 302 to only API resources (if someone forgets to put the JS bundle behind a proxy).

I agree this would likely be quite a rare scenario, but not impossible. 

Do you (or anyone else!) have any thoughts on mitigating cases like this? 

What's the risk appetite for potential issues like this? Maybe it's best to wait to see if anyone actually has this issue before we try to fix it?

**Comment by jfdoming** [comment]
> > user could get stuck in a reload loop if the server sends a 302 to only API resources (if someone forgets to put the JS bundle behind a proxy).
> 
> I agree this would likely be quite a rare scenario, but not impossible.
> 
> Do you (or anyone else!) have any thoughts on mitigating cases like this?
> 
> What's the risk appetite for potential issues like this? Maybe it's best to wait to see if anyone actually has this issue before we try to fix it?

One option we've used in the past is an experimental feature that defaults to on. That way, if folks run into any problems, they can turn off the redirects, disable the feature, and then report the issue.

**Comment by alexyao2015** [comment]
That doesn't seem like a bug worth fixing. Say a user encounters an infinite reload. They disable the automatic reload feature (which they're unlikely to disable without clearing browser cache because now the page is reloading constantly). Would we expect the server to function at all in this case? The user would still continue to experience redirects when attempting to reach the API. I think if someone did have this issue, having it loop like this would show them that something is wrong with the configuration.

**Comment by youngcw** [comment]
I agree its probably not worth worrying about an edge case that is unlikely to happen, especially since this will help a bunch of people as is.  The issue of needing to reauthenticate trips people up all the time.

**Comment by jfdoming** [comment]
> I agree its probably not worth worrying about an edge case that is unlikely to happen, especially since this will help a bunch of people as is. The issue of needing to reauthenticate trips people up all the time.

Alright, I'm fine to address it later if someone runs into it 👍

**Review by jfdoming — APPROVED** [review]

**Comment by youngcw** [comment]
This doesn't seem to be working for me anymore on edge.  I wonder if something broke this.

**Comment by StefanFabian** [comment]
Same, I'm on 24.10.1 and it does not reload even though all the API requests are redirected to my auth page.

**Comment by alexyao2015** [comment]
I realize we can change the service worker to not capture the sync API call to avoid this issue entirely.

**Comment by xxxarmitagexxx** [comment]
I am on 24.11.0 and am still experiencing a sync issue when going through Authentik after the auth token expires.

**Comment by gcoremans** [comment]
I recently installed Actual 24.11.0 and this is also not working for me.

**Comment by xxxarmitagexxx** [comment]
> I am on 24.11.0 and am still experiencing a sync issue when going through Authentik after the auth token expires.

To clarify, the issue presents itself independently from the Authentik expiry. I have set it to 52 weeks last time I had the issue and had to delete all browser data to force a reload and had again the issue today, a week later. 

A fix would be greatly appreciated as this makes Actual difficult to transition to in a family setting. I intend to get my wife to move off YNAB in favor of Actual and certainly don’t see her clearing her browser data on a frequent basis.

**Comment by TimQuelch** [comment]
What browser are you using? What errors are you seeing? What do the redirects look like?

**Comment by xxxarmitagexxx** [comment]
I am using Firefox normally on Desktop but have the same issue with Chrome and also on Mobile (Samsung Internet, Chrome, Firefox).

When the issue happen, the sync would stop working, I would see the server as offline. If I close the file and delete it, I cannot see the server at all, it would say that actual-fqdn.com cannot be reached, please check SSL configuration. 

I will check my redirections next time the problem occurs.
Under normal circumstances, the redirections looks like actual-fdqn.com --> actual-fdqn.com//outpost.goauthentik.io/start?rd=/ -> authentik-fdqn.com//if/flow/default-authentication-flow/....

I was not aware of the differences between session expiry and token expiry, thanks for pointing it out. 
The token validity for the actual provider is set as weeks=52.
The session validity for the user login authentication stage is set as 0 (session expires when browser closes). Looking in the list of sessions against my user in Authentik, I can see that the most recent session created today has a 14 days expiry so I guess there is a maximum regardless of the browser being closed or not. 

Considering those two parameters, I don’t see how the Actual token would expire before the session itself expires. 

So I am not clear on what exactly is happening. 
Any tips on what to look for/investigate, next time the problem reoccurs?

**Comment by xxxarmitagexxx** [comment]
I have the issue currently with my phone. 
I have deleted all sessions in Authentik.

Going to actual-fdqn.com, it simply loads the offline file showing the server offline.
If I go to one other service being Authentik, I immediately get the Authentik sign in page before being redirected to that service.

Once logged in Authentik, if I try to reload actual-fdqn.com or open a new tab in the same browser exhibiting the issue, it loads immediately the offline file, with the server shown offline...

Is there a better way to force a redirection to Authentik? So far the only I found to get around the issue in any browser is to clear all data which gets old every time.

When the issue occurs, the browser does not even attempt to reach Authentik, the offline file is loaded. It is clear as day, as I can unmap the actual-fdqn.com in Nginx proxy manager and it would still resolve loading the offline file....

**Comment by gcoremans** [comment]
Here is the request sequence that's tripping it up for me, if it helps:
image

**Comment by TimQuelch** [comment]
Ah interesting. Ultimately the request fails because it is blocked by CORS. I doubt the current check is detecting this as a redirected request and instead only seeing a CORs error.

**Comment by paumove** [comment]
Same problem here with v24.11.0 and Authentik. 

image

**Comment by TimQuelch** [comment]
There's a couple of fixes here
1. Configure your auth server and/or proxy  to send the appropriate CORS headers (Access-Control-Allow-Origin, Access-Control-Allow-Methods, etc.) to allow responses from your auth server to be allowed in Actual. How this is done will be entirely dependent on your setup. (this is how my setup is configured which is why I wasn't aware this was an issue)
2. Update the check that was added in this PR to also detect if a CORs error was encountered. I think this is quite difficult, because as far as I can tell a CORS error is pretty much indistinguishable from any other network error. We may end up in refresh loops if there's some other network problem.
3. Change how service workers behave so that this check isn't necessary. I'm out of my depth on what those changes would need to be.

**Comment by gcoremans** [comment]
Telling people to set the necessary CORS headers seems like a sufficient solution, but perhaps the docs should be updated to indicate that this might be necessary?

**Comment by alexyao2015** [comment]
The cors headers was definitely the fix! I think we should just notify people about this in the documentation. I'm running nginx ingress with authentik and this config did it for me. Working flawlessly now.

```        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            set $$allowed_origin "";
            if ($$http_origin = "https://actual.${SECRET_EXTERNAL_DOMAIN_NAME}") {
              set $$allowed_origin $$http_origin;
            }
            if ($request_method = OPTIONS) {
              add_header "Access-Control-Allow-Origin" $$allowed_origin;
              add_header "Access-Control-Allow-Headers" "*";
              add_header "Content-Type" "text/plain; charset=utf-8";
              add_header "Content-Length" "0";
              return 204;
            }
            if ($request_method = GET) {
              add_header "Access-Control-Allow-Origin" $$allowed_origin;
            }
```

**Comment by xxxarmitagexxx** [comment]
Thanks, it took me a while to figure out how to adapt it in Nginx proxy manager, but I got it working eventually.

As a note for those in the same case: edit the authentik proxy in NPM, create a custom location for /, click the cog wheel and paste the code from alexyao2015 from "set $allowed_origin"";.

**Comment by rgoldfinger** [comment]
I'm running into similar issues and am happy to submit a fix if I can get guidance on the right direction. 

My instance is running behind a Cloudflare Tunnel using Cloudflare Access, and when the Access token expires, the client is unable to reach the server. This is especially problematic on mobile Safari which seems to have no way to force a hard reload. 

When this happens, requests to the Actual server are 302 redirected to the Cloudflare login page, but the redirected url hits a CORS error. 

```
Access to fetch at 'https://<cf-account-name>.cloudflareaccess.com/cdn-cgi/access/login/<fqdn>?kid=<redacted>&redirect_url=%2Fsync%2Fsync&meta=<redacted>' (redirected from 'https://<fqdn>/sync/sync') from origin 'https://<fqdn>' 
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I've been looking into fixing this on the Cloudflare side, but from my understanding (and I could be missing something) I'd need to set the CORS headers on the response from `https://<cf-account-name>.cloudflareaccess.com`. There does not seem to be any way to do so based on their [docs](https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/cors/). From my understanding, their docs concern the requests to the protected server, not `https://<cf-account-name>.cloudflareaccess.com`. 


I've also been looking into fixing this from the Actual side. Based on an approach I came across [here](https://github.com/silverbulletmd/silverbullet/issues/1091), there's a potential solution to detect this scenario.

This approach looks for `response.type === 'opaqueredirect'`. 

[From MDN](https://developer.mozilla.org/en-US/docs/Web/API/Response/type):
> `opaqueredirect`: The fetch request was made with redirect: "manual". The Response's status is 0, headers are empty, body is null and trailer is empty.
 
The obvious downside is that this would require changing all fetches from `redirect: 'follow'` to `redirect: 'manual'`, and I have no idea what the implications of that are. 

But, this does seem to solve the immediate problem:

```
export const fetch = async (
  input: RequestInfo | URL,
  options?: RequestInit,
): Promise<Response> => {
  const newOpts: RequestInit = { ...(options ? options : {}), redirect: 'manual' };
  const response = await globalThis.fetch(input, newOpts);

  // Detect if the API query has been redirected to a different origin. This may indicate that the
  // request has been intercepted by an authentication proxy
  const originalUrl = new URL(input instanceof Request ? input.url : input);
  const responseUrl = new URL(response.url);
  if (response.redirected && responseUrl.host !== originalUrl.host) {
    connection.send('api-fetch-redirected');
    throw new Error(`API request redirected to ${responseUrl.host}`);
  }

  if (response.type === 'opaqueredirect') {
    connection.send('api-fetch-redirected');
    throw new Error(`API request redirected to unknown destination`);
  }

  return response;
};
```

Is this approach, or something like it, viable? Perhaps there's one api call (`sync`?) that might be safe to not follow redirects on?

**Comment by Shazib** [comment]
@rgoldfinger i'm running the exact same flow (cloudflare tunnels + cloudflare access), have you made any headway with this at all? Thanks

**Pull request merged**
