### PR TITLE
Color Consolidations

### PR DESCRIPTION
**Pull request by carkom**
Consolidating colors so they are more consistent across the app from one page to the next. This also helps with staging dark theme colors.

### CODE REVIEW

**Comment by carkom** [comment]
Only one small regression here. The rest of the work is re-naming and re-organizing the theme colors.

A slight visual regression in the settings page as it was using a border color that wasn't being used anywhere else in the app. I choose to match the color standardization that is used everywhere else in the app rather than have this be an entirely unique element not used anywhere else. Cheers!

**Comment by youngcw** [comment]
Ill approve this once the conflicts are cleared up.  We probably should get another approval though because of the small change.

**Review by youngcw — APPROVED** [review]

**Review by youngcw — APPROVED** [review]

**Comment by MatissJanis** [comment]
Just looking at the screenshots: it seems the border for checkboxes is now wrong. Looks like it always highlights them as "active" even if the user is not actively using them.

**Comment by carkom** [comment]
> Just looking at the screenshots: it seems the border for checkboxes is now wrong. Looks like it always highlights them as "active" even if the user is not actively using them.
> 
> Also - I'm not really a fan of the removal of the border. Could we instead use a different color for it from the existing palette instead of removing them entirely?

Fixed both, thanks for the review. Let me know if ready to merge or if there's any other changes needed.

**Comment by MatissJanis** [comment]
New warning color looks much better! Thanks for taking care of that too!

> Also - I'm not really a fan of the removal of the border. Could we instead use a different color for it from the existing palette instead of removing them entirely?

This one isn't done yet. The new border for settings block is either transparent or just too light (in lightmode) compared to before.

**Comment by carkom** [comment]
> This one isn't done yet. The new border for settings block is either transparent or just too light (in lightmode) compared to before.

I made it a shade darker in light mode. LMK!

**Comment by MatissJanis** [comment]
Settings page card border now looks good.

But the checkbox border issue is back.

**Comment by carkom** [comment]
> Settings page card border now looks good.
> 
> But the checkbox border issue is back.

Yep, I see what I did there. Accidently reverted the fix. It's back in now. 😬

**Review by MatissJanis — APPROVED** [review]
Thanks!

**Pull request merged**
