### PR TITLE
Enforce a sort order for imports

### PR DESCRIPTION
**Pull request by TomAFrench**
I personally find the imports quite hard to manage (particularly in `desktop-client`) as we have a jumble of external imports, imports from other workspaces in the monorepo and local imports all mixed together. This means it's quite hard to see what what's going on and what exactly the open file depends on. Now that Actual is OSS, there's more cooks in the kitchen so it will likely deteriorate further.

To fix this I've added a plugin to the linter which enforces that imports are sorted consistently and will automatically fix deviations from this.

Specifically, we now sort imports as:
1. React related packages
2. External packages
3. Monorepo packages
4. Local imports

Each group is separated with a newline and within each group the imports are sorted alphabetically.

### CODE REVIEW

**Comment by TomAFrench** [comment]
@jlongster This is a fairly opinionated PR so I'd like to flag it up rather than just merging in case you have any strong opinions on this sorting.

Also @trevdor I imagine is going to cause all kinds of trouble in terms of merge conflicts with #79. On the plus side, the fixes would be automated but I want to run it by you first. I could handle the merge issues for you if you'd prefer.

**Comment by trevdor** [comment]
This is precisely how I prefer to sort, but I was *this close* to learning not to care anymore. My new team at work is entirely freeform about it. Feels a little like taking a sober friend out for drinks. Don't help me fall off the easy breezy wagon! 😆 

I too would like to hear @jlongster weigh in--I appreciate that Actual code often feels technically tight while loose about formalities. However, your "more cooks in the kitchen" argument has merit similar to why we would TypeScript.

I don't mind tidying up my branch if you merge this.

**Comment by TomAFrench** [comment]
Will likely merge on Monday assuming no objections from @jlongster

**Comment by jlongster** [comment]
Sorry I missed this; I like enforcing the order! If I can request one change though: can we not force alphabetical sorting in each group? A lot of times it's nice to import similar things next to each other within the group, like if I'm importing a bunch of stuff related to dates or something.

How strongly do you all feel about the alphabetical sorting?

**Comment by TomAFrench** [comment]
My feeling is that related functions are/should be close to each other in the directory structure and so will be sorted near to each other. It's pretty easy to make another PR which doesn't perform alphabetical sorting so we can compare though.

**Comment by TomAFrench** [comment]
Closing in favour of #237 and #238

**Pull request closed without merging**
