### PR TITLE
Converting Privacy Filter Blur Intensity to change DOM value

### PR DESCRIPTION
**Pull request by Crazypkr1099**
Converted privacyfilter blur to instead change the DOM original content. When privacy filter is on, all hidden values converted to "???". When hovering, the ??? changes back to original content.

This prevents others from seeing how many digits are in your data.

Please let me know what you think, or if you have any suggestions how to make it look better :)

### CODE REVIEW

**Comment by Crazypkr1099** [comment]
@joel-jeremy Considering you were the original creator of the privacy filter, please let me know what you think of this "enhancement" or if you have any suggestions to make it look better. Thanks :)

**Comment by joel-jeremy** [comment]
I think this needs some polishing: 
- The `???` are not honoring the styling of the original content e.g. hover the amount in the accounts page
- The style of the budget table's `Budgeted` column seem to be broken when hovered
- When deposit column in hovered in the transactions page, it just keeps displaying `???` instead of showing the original content

What if instead of a blur/`???`, we replace the elements with something similar to the status column in the Schedules page? But instead of schedule icons, we use an eye icon.

**Comment by Crazypkr1099** [comment]
I'm good with that. I also agree with the suggestion in the discord chat
that not every number needs to be on privacy filter. It should be the main
numbers (acc balance, net worth, running total etc.) And the rest should be
visible.

Maybe the budget page should be hidden completely though.

**Comment by joel-jeremy** [comment]
I was planning to add some more buttons that control the privacy filter on the budget table, accounts side bar, and transactions table but haven't got the time to implement them at the moment. It would be great improvement if those can be added.

Another thing I had in mind before was to improve the hover behavior where instead of only revealing the hovered element, the entire row will be revealed.

**Pull request closed without merging**
