### PR TITLE
Show sync indicator in account header

### PR DESCRIPTION
**Pull request by psybers**
Currently, sync indicators are only shown for desktop in the accounts list on the left sidebar.  If you select a single account and ask to sync it, the indicator on the left is not visible for that account (since it is selected):

image
image

Thus you will not know if the sync failed (until you click to another account):

image

This PR updates to show the indicator in the header next to the account name:

image

For any accounts not sync'd (or "All Accounts" etc.) it simply shows no indicator:

image\
image

### CODE REVIEW

**Comment by MatissJanis** [comment]
Cool idea. But we have a small problem: when clicking "edit" the account name jumps to the left. Could we make the edit box stay in the same position as the account name? I believe we could just move the sync indicator outside the /edit/ boundaries and that would solve it.

**Comment by psybers** [comment]
I was aware it 'jumped' left.  I assumed, since the box is not sized to the string (try editing a name that is long), that it's moving would be ok.  Even with short names, the box is not lined up perfectly with the label so there is a bit of wiggle.

If you think that is a problem though, I can easily fix it.

**Comment by psybers** [comment]
This is the current behavior:

image

image

**Comment by psybers** [comment]
(And just to clarify, the behavior I implemented *hides* the indicator while editing. It is not that the box is on top of it.)

**Comment by psybers** [comment]
I fixed that issue so the indicator stays put and the edit box does not 'jump'.

As a side effect, I also fixed the slight 'wiggle' the box had when showing/hiding (even for accounts without an indicator).

While I am in here would it also make sense to try and have the edit box enlarge to fit its contents for longer names?

**Comment by psybers** [comment]
I could set the input `width: accountName.length + "ch"` or something similar.  Since the font is variable-width, we can't pick a perfect number that sizes it directly to the contents, so I went with the `ch` unit (the width of a `0` in the font).

Most will have some extra space at the end, as many characters are not as wide as a `0`.  But it does ensure it is at least as wide as the text.

**Comment by psybers** [comment]
Without changing the width:
image

With changing the width:
image

**Comment by psybers** [comment]
It might make sense to ensure minimum width, e.g. 10 characters `width: Math.max(10, accountName.length) + "ch"`.

**Comment by MatissJanis** [comment]
Sorry for the slow answer.

I think this sample is ideally what we would want: https://github.com/actualbudget/actual/pull/2560#issuecomment-2041200999

If it's not technically overengineered to implement it - would you mind doing it? Otherwise your current solution is also OK and I'm happy to merge it as-is.

**Comment by psybers** [comment]
@MatissJanis No it is a very simple fix. Just pushed.

**Review by MatissJanis — APPROVED** [review]
Thanks! This is great

**Pull request merged**
