### PR TITLE
Fix titlebar transparent background

### PR DESCRIPTION
**Pull request by carkom**
Not much to this. Turns title bar from transparent to coincide with new theme coloring.

### CODE REVIEW

**Comment by MatissJanis** [comment]
Screenshot 2023-08-04 at 18 39 30

And there is no way to scroll to see the month names.

Also: I'm not entirely sold on the idea that this title bar should have a background that overlays the content. Is there another solutions we could explore? Maybe some responsive styling (i.e. making the titlebar a "static" element instead of floated on smaller resolutions)?

**Comment by carkom** [comment]
> Also: I'm not entirely sold on the idea that this title bar should have a background that overlays the content. Is there another solutions we could explore? Maybe some responsive styling (i.e. making the titlebar a "static" element instead of floated on smaller resolutions)?

I agree, this change isn't quite right. I think it best to keep transparent back ground and change title bar to static as you suggest. Do you think it needs to only be static for smaller resolutions or couldn't we just always make it static and have the same effect?

**Comment by carkom** [comment]
I'm happy with this implementation. Let me know what you think.

It shows no change to large format resolutions(eg no scrollbars) and just keeps title bar at the top for smaller resolutions. Applies to all pages with a titlebar.

**Review by MatissJanis — APPROVED** [review]
Smart! I'm ok with this solution, but would really like at least another person to review.

**Review by shall0pass — APPROVED** [review]
This has bugged me on small screens for a while.  And you've fixed it!  Thanks!

**Comment by MatissJanis** [comment]
Thanks!

**Pull request merged**
