### PR TITLE
[WIP] Category Group selectable in Category Autocomplete to filter

### LINKED ISSUE #2873: [Feature] Category Group selectable in Category Autocomplete to filter
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When categorizing transactions manually you know the name of the category group, but you don't remember the category exactly. 

### Describe your ideal solution to this problem

The proposal is that you can type the category group inside the autocomplete then press enter show only the group categories inside that group

### Teaching and learning

_No response_

### PR DESCRIPTION
**Pull request by lelemm**
fix #2873

### CODE REVIEW

**Comment by Crazypkr1099** [comment]
Hey, just checked it out. Your missing the category when searching for the subcategory. 

If I have multiple subcategories with the same name, there's nothing to show what category it is...

Screenshot_20240612_155728_Chrome

**Comment by lelemm** [comment]
> Hey, just checked it out. Your missing the category when searching for the subcategory.
> 
> If I have multiple subcategories with the same name, there's nothing to show what category it is...
> 
> Screenshot_20240612_155728_Chrome

Thanks for the feedback, I didn't noticed it

**Comment by Crazypkr1099** [comment]
> > Hey, just checked it out. Your missing the category when searching for the subcategory.
> > If I have multiple subcategories with the same name, there's nothing to show what category it is...
> > Screenshot_20240612_155728_Chrome
> 
> Thanks for the feedback, I didn't noticed it

Also just one more personal comment... I don't like how subcategories are hidden as well. I get you made the category clickable but when im searching category its nice to see all the subcategories. I think the best way to have this implemented is like the discussion in actual discord dev chat: show subcategories first, and then afterwards show matching categories.

Personal opinion, but I feel like it would be a bit of a pain clicking on the category and then selecting the sub cat.

**Comment by lelemm** [comment]
I'll change according your suggestions. After playing around a little more I don't like the behavior atm

**Comment by lelemm** [comment]
Pushed the changes

https://github.com/actualbudget/actual/assets/15043428/35aeac27-d16d-4002-b942-a77f5b88726e

**Comment by lelemm** [comment]
@Crazypkr1099 check what you think about this new version.
The groups are selectable after you start a filter, before that not. I reverted the change where the categories were filtered without the group name too.

**Comment by Crazypkr1099** [comment]
> @Crazypkr1099 check what you think about this new version.
> The groups are selectable after you start a filter, before that not. I reverted the change where the categories were filtered without the group name too.

I appreciate all the work you've done, but I very much dislike having to click the group to see the sub category. 


I think it's best if it's such shown underneath, like my #2861 PR.

**Comment by lelemm** [comment]
I must pay more attention. Didn't saw your PR about the same feature. this was driving me crazy lately so I just coded lol.
I will close my PR cuz there is no point on this

**Pull request closed without merging**
