### PR TITLE
fix: csv import deduplication

### LINKED ISSUE #3416: [Bug]: CSV duplicate matching no longer showing in the import window.
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The CSV importer is supposed to show matching transactions so the user can decide to force import or allow matching and deduplication.  That is no longer happening in the current version.  It quit happening somewhere between 24.8 and 24.9.

The quickest way to test is to either use a existing csv and import it twice, or to make an export of a test budget account, then to reimport it and see that its not matching any of the transactions.  Compare against the deploy for v24.8 to see the difference. https://deploy-preview-3179.demo.actualbudget.org/

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

_No response_

### Operating System

None

### PR DESCRIPTION
**Pull request by UnderKoen**
fixes #3416

### CODE REVIEW

**Comment by MatissJanis** [comment]
👋  Thanks for working on this! Would you have an example CSV file I could use for testing the patch? That would help me greatly 🙏

**Comment by UnderKoen** [comment]
[Vanguard-401k.csv](https://github.com/user-attachments/files/17034819/Vanguard-401k.csv)
This is just an export of one of the accounts in the demo file

**Comment by MatissJanis** [comment]
@coderabbitai review

**Comment by MatissJanis** [comment]
Thanks! I noticed another bug here (introduced by me). We'll need to merge [this PR](https://github.com/actualbudget/actual/pull/3460) first and then I'll return back to your PR. Apologies about the delay.

**Review by MatissJanis — APPROVED** [review]
Thanks! Now we just need to patch the checkboxes in the CSV import modal not working as expected. But that's a separate issue I believe.

**Pull request merged**
