### PR TITLE
[WIP] :bug: fix the app randomly navigating back (closing)

### LINKED ISSUE #2596: [Bug]: Site closes when opening
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The web app closes when attempting opening. It occurs very frequently to me. It is just a plain instance with zero data. I've attached a clip of it happening. This has happened for me on Firefox (desktop) and on Brave (mobile).

Something similar to `history.back()` seems to be happening. I'm willing to open a PR if you could guide where it is happening.

https://github.com/actualbudget/actual/assets/50770114/2ab8b271-c4bd-493f-a4ad-76d5d82fd848

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #2596

Reproduction:

1. open demo link and create an empty budget
2. close the tab
3. open demo link /accounts
4. close the tab
5. open demo link /accounts
6. 💣

### CODE REVIEW

**Review by carkom — APPROVED** [review]
LGTM!

**Comment by joel-jeremy** [comment]
Removing this code will regress into the old bug where if you press back, it will appear as if nothing is happening. Steps to reproduce:

1. Go to an account
2. Add a transaction using the top right + button
3. Press back
4. Nothing happens - app stays on the same page

Maybe we could instead add a check to only do the `navigate(-1)` if there is still a previous path or history stack still has entries.

**Comment by MatissJanis** [comment]
Hey @joel-jeremy . Sorry for taking such a long time to get back at this PR.

So I tried to reproduce your bug on desktop (using this hash), but was not able to. So I tried on mobile - was able to reproduce there (after adding transaction you need to click 2x "back" to actually go back). However, I was also able to reproduce the same bug on `edge`. Can you double-check if you can reproduce the bug on edge? If yes - then this PR wouldn't be introducing the regression.

But maybe I'm testing incorrectly.

**Review by joel-jeremy — APPROVED** [review]
LGTM. I am also able to reproduce on the latest release build.

**Pull request merged**
