### PR TITLE
Spending Report: Header update

### PR DESCRIPTION
**Pull request by carkom**
Fixing header so that any month can be compared to any other month. Also adds budget as an optional comparison.

### CODE REVIEW

**Comment by matt-fidd** [comment]
I was initially unsure what "budget" comparison meant, do you think it would be less ambiguous as "all time" instead?

In the process of a code review now

**Comment by matt-fidd** [comment]
or even, just reduced to "average"? The existing "average" could be "3 month average" instead to differentiate.

I suppose the natural extension of this PR (out of scope for this one of course) is a dynamic average selector:

Compare [SEP 24] to ["3"] [month] average
Compare [SEP 24] to [all time] [average]

**Comment by matt-fidd** [comment]
Sorry, you can ignore my previous comments - I misunderstood the new option.

I'm getting a fatal error when I upload my existing budget to the deploy
image

**Comment by carkom** [comment]
> I'm getting a fatal error when I upload my existing budget to the deploy
>

Good shout, I need to clear that...

**Comment by carkom** [comment]
> I'm getting a fatal error when I upload my existing budget to the deploy ![image](https://private-user-

Fixed!

**Review by matt-fidd — APPROVED** [review]
Looks good!

**Review by matt-fidd — DISMISSED** [review]

**Comment by carkom** [comment]
Sorry @matt-fidd, had a couple other visual issues.

**Comment by matt-fidd** [comment]
No problem, all looks good!

**Review by matt-fidd — APPROVED** [review]

**Pull request merged**
