### PR TITLE
fix(#2562): Prevent transaction deduplication for imported transactions

### LINKED ISSUE #2562: [Bug]: Transaction deduplication happens even if transactions have different `imported_id`s
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I'm using a custom script to add transaction to Actual. The script uses the `importTransactions` function of the actual API. If I import two "similar" transactions, albeit with different `import_id`s, Actual's deduplication function merges the two transactions even if it should not.

As an example, I imported the following transaction:

```json
{
    "account": "73157c52-9179-4d3b-85c1-01dd5db1cf28",
    "date": "2024-04-05",
    "amount": -1239,
    "imported_payee": "Acme Inc.",
    "payee_name": "Acme Inc.",
    "imported_id": "b85cdd57-5a1c-4ca5-bd54-12e5b56fa02c",
    "notes": "TEST TRANSACTION",
    "cleared": true
}
```

Import was successful and the transaction appeared on Actual. Then, I imported the following transaction, which differs in `date` and `imported_id`, but has the same amount and other properties of the previous one:

```json
{
    "account": "73157c52-9179-4d3b-85c1-01dd5db1cf28",
    "date": "2024-04-06",
    "amount": -1239,
    "imported_payee": "Acme Inc.",
    "payee_name": "Acme Inc.",
    "imported_id": "ca1589b2-7bc3-4587-a157-476170b383a7",
    "notes": "TEST TRANSACTION",
    "cleared": true
}
```

The second import was also successful, but the transaction did not get added to Actual. Instead, the date of the first transaction got updated to match the second one (or the second transaction was added and the first disappeared, depending on how you want to see it).

As a sanity check, I changed the amount and tried importing the transaction again (with a fresh `imported_id`):

```json
{
    "account": "73157c52-9179-4d3b-85c1-01dd5db1cf28",
    "date": "2024-04-06",
    "amount": -9876,
    "imported_payee": "Acme Inc.",
    "payee_name": "Acme Inc.",
    "imported_id": "3497767b-3d28-4887-bb9d-80fb7f113d4e",
    "notes": "TEST TRANSACTION",
    "cleared": true
}
```

This time, a separate transaction was added to Actual.

This behavior suggests that the deduplication feature does not take different `imported_id`s into account, while it should to avoid unintentionally merging different transactions.

This issue was previously discussed on [Discord](https://discord.com/channels/937901803608096828/1226164998871580782).

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by strazto**
Resolves #2562 

Based on #2618 , with comments by @MatissJanis and others applied

### CODE REVIEW

**Comment by MatissJanis** [comment]
I'm trying to wrap my head around the difference between #2618 and this PR, but I can't seem to really get it.

Would you mind creating a unit test case that passes in this PR, but would fail in #2618?

**Comment by pmoon00** [comment]
> I'm trying to wrap my head around the difference between #2618 and this PR, but I can't seem to really get it.
> 
> Would you mind creating a unit test case that passes in this PR, but would fail in #2618?

From my interpretation @strazto is implying that if the imported transaction doesn't have an `imported_id` then it should **include** existing transactions that either have or don't have an `imported_id`. 

The PR #2618 [excludes all existing transactions with an `imported_id` in the fuzzy search](https://github.com/actualbudget/actual/pull/2618/files#diff-686fc94775444483c551d99e96c7bc92175543a53600f050fa2cdbe119b10523R402).

I'm not super confident in what is technically correct here as you've mentioned some complex scenarios in comments in #2618, I'll let you be the judge @MatissJanis 

I believe the test case that would pass in this PR but not in #2618 would be something like the below. I have tested this test fails in #2618 as the assertion for the number of transactions fails, receiving 2, when expecting 1.

```ts
  test(
    'given an imported tx with no imported_id, ' +
      'when an existing transaction that has an imported_id and matches amount and is within 7 days of imported tx,' +
      'then imported tx should reconcile with existing transaction from fuzzy match',
    async () => {
      const { id } = await prepareDatabase();

      let payees = await getAllPayees();
      expect(payees.length).toBe(0);

      const existingTx = {
        date: '2024-04-05',
        amount: -1239,
        imported_payee: 'Acme Inc.',
        payee_name: 'Acme Inc.',
        imported_id: 'b85cdd57-5a1c-4ca5-bd54-12e5b56fa02c',
        notes: 'TEST TRANSACTION',
        cleared: true,
      };

      // Add transaction to represent existing transaction with imoprted_id
      await reconcileTransactions(id, [existingTx]);

      payees = await getAllPayees();
      expect(payees.length).toBe(1);

      let transactions = await getAllTransactions();
      expect(transactions.length).toBe(1);

      // Import transaction similar to existing but with different date and no imported_id
      await reconcileTransactions(id, [
        {
          ...existingTx,
          date: '2024-04-06',
          imported_id: null,
        }
      ]);

      payees = await getAllPayees();
      expect(payees.length).toBe(1);

      transactions = await getAllTransactions();
      expect(transactions.length).toBe(1);

      expect(
        transactions.find(
          t => t.imported_id === 'b85cdd57-5a1c-4ca5-bd54-12e5b56fa02c',
        ).amount,
      ).toBe(-1239);
    },
  );
```

**Comment by strazto** [comment]
> > I'm trying to wrap my head around the difference between #2618 and this PR, but I can't seem to really get it.
> > Would you mind creating a unit test case that passes in this PR, but would fail in #2618?

> I believe the test case that would pass in this PR but not in #2618 would be something like the below. I have tested this test fails in #2618 as the assertion for the number of transactions fails, receiving 2, when expecting 1.
> 
> ```ts
>   // ...
> ```
> 
> Edit: After making this comment I went and got this PR on my machine. The test needed a bit of tweaking to work but in essence asserted my thinking was correct.

@pmoon00 nailed it, thanks for the test case, didn't have time to touch it this weekend :) I'll put it in the PR, can add you to the author list in the release note 

> I did find an issue/side effect, where if you merge a transaction that doesn't have an `imported_id` with an existing transaction that does have an `imported_id`, the `imported_id` is removed from the existing transaction.

That sounds like a bug, probably the `imported_id` should be picked over the existing tx.
**That said** given this PR only touches the **selection criteria** for the fuzzy search, that bug is not really related to this PR.

Worth raising in its own ticket :)

**Review by MatissJanis — APPROVED** [review]
Ok, this seems to work as expected. Seeing no problems and the extra test case works as expected (fails in `master` and in the previous PR, but passes here).

LGTM on my end, but I'd like another maintainer to review this too since it touches such an important part of the codebase.

**Comment by strazto** [comment]
@youngcw can i get you to also review this please?

**Pull request merged**
