### PR TITLE
Mobile balance cover/transfer/rollover overspending

### PR DESCRIPTION
**Pull request by joel-jeremy**
Add the following tooltip options in mobile balance:
- Transfer to another category
- Rollover overspending
- Cover overspending

### CODE REVIEW

**Comment by youngcw** [comment]
With this and the other mobile additions there is almost no dead space to click away from a dialog.  If its possible it would be nice to not open a new dialog if there is one currently open, or at least only open if nothing or one of the same type is open.  

The hit box (is that the right name?) for this new dialog seems weirdly big and includes part of the spent value section.

**Comment by joel-jeremy** [comment]
@youngcw I have pushed an update to fix the hit boxes. As for the first comment, that should have already been addressed in https://github.com/actualbudget/actual/pull/1781 once that gets merged.

**Comment by youngcw** [comment]
Would it look better to have the "you can click me" underline match the color of the balance value?  If we don't want to completely match the color then maybe just matching the dimmed "0" balance color would be nice since the bar really stands out when the balance is 0.

**Comment by joel-jeremy** [comment]
The layout changes made here also fixed the mobile report mode alignment issue as a bonus: https://github.com/actualbudget/actual/issues/1790

**Review by youngcw — APPROVED** [review]

**Comment by youngcw** [comment]
> With this and the other mobile additions there is almost no dead space to click away from a dialog.

@joel-jeremy this issue still isn't fixed. It is working for the name and budgeted edit views, but I can directly open the balance tooltip from those other two or vice versa.

**Comment by joel-jeremy** [comment]
@youngcw Issue should now be fixed :)

**Review by youngcw — APPROVED** [review]

**Pull request merged**
