### PR TITLE
Swipe up mobile navbar

### PR DESCRIPTION
**Pull request by joel-jeremy**
Swipe up mobile navbar to reveal more menus.

### CODE REVIEW

**Comment by shall0pass** [comment]
I really like this interaction!

**Review by shall0pass — APPROVED** [review]
It has my 👍.

**Comment by joel-jeremy** [comment]
@MatissJanis Any suggestions on how to implement swipe up in tests? I tried some solutions I found online but it doesn't drag the nav tabs up.

**Comment by MatissJanis** [comment]
Would this work? https://playwright.dev/docs/input#drag-and-drop

On a different note: what if we had the "+" icon in the middle? Maybe it's just me, but that's where budgeting apps usually have it. Not a blocker though.

**Comment by joel-jeremy** [comment]
Unfortunately, I have tried that and doesn't seem to work so I'm stuck :(

Yeah, putting the + in the middle makes sense. I'll update it tomorrow.

**Comment by MatissJanis** [comment]
Fixed the e2e tests for you: https://github.com/actualbudget/actual/pull/1758/commits/fe3a4e10a51b48fd585515752de4721d1af2a85a

Though you'll want to solve the lint issue and also merge the latest `master` branch in here before merging.

**Comment by joel-jeremy** [comment]
Thank you @MatissJanis! Rebased from master and tests are now passing.

**Pull request merged**
