### PR TITLE
Handle Null Org Domain in SimpleFIN for bank_id

### PR DESCRIPTION
**Pull request by duplaja**
SimpleFIN (currently) uses the org domain as the bank ID. According to SimpleFIN docs, this can possibly be a null value, as can the org name. However, at least one of the two must be present. (See: https://www.simplefin.org/protocol.html#organization )

In Actual, org name is set to "Unknown" if it comes in as null, but the bank_id (previously just set to the org domain) was not, resulting in a null bank_id value at times.

### CODE REVIEW

**Comment by psybers** [comment]
This seems to help if they have a single bank with a null domain.  But what if they have two banks with null domains?

Won't this just set both to the `bank_id` as `Unknown`?  Thus, it would consider them the same bank.

**Comment by psybers** [comment]
Although it is undocumented, I wonder if using `url` as the fallback before going to the institution might be better.

We could update the domain to use `url` as the fallback if `domain` is empty:

https://github.com/actualbudget/actual/blob/6d117f44de92e8777beb8c052d9483febc9d9e22/packages/desktop-client/src/components/modals/CreateAccountModal.tsx#L82

`orgDomain: oldAccount.org.domain ? oldAccount.org.domain : oldAccount.org.url,`

**Comment by duplaja** [comment]
@psybers Right now, bank_id is set to "domain". I've just modified it so that bank_id falls back to "name", if "domain" is null.

The SimpleFIN API docs say that one of the two must be sent. I'm hesitant to use an undocumented org url, especially if we can't be sure that it's a required field.

"Unknown" is only used for the Org name for the institution object (see: https://github.com/actualbudget/actual/blob/64821e6a64b5928755f1307f5d154a7502997ddd/packages/loot-core/src/server/main.ts#L656 ) , if one isn't set, but the ID will still be unique to the bank (bank_id will never be "Unknown")

**Comment by duplaja** [comment]
Switching this back to WIP, pending further information regarding the newly added 'id' parameter on each org, from SimpleFIN. 

From their docs:

> Optional ID for the financial institution. The ID must be unique per SimpleFIN server, but it is not guaranteed that IDs are globally unique. Prefer domain as a globally unique ID for each institution

**Comment by youngcw** [comment]
Is this updated to reflect your discussion with @psybers the other day?

**Comment by duplaja** [comment]
> Is this updated to reflect your discussion with @psybers the other day?

Yes, it is.

**Review by youngcw — APPROVED** [review]

**Pull request merged**
