### PR TITLE
remove the “…” menu on account pages, split actions between account name menu + balance menu

### PR DESCRIPTION
**Pull request by j-f1**
Screenshot_2023-01-13 18 48 27
Screenshot_2023-01-13 18 50 15

I definitely want to try this out for a bit on my end before merging to see how it feels, but the idea is to move the actions to more contextually relevant locations, and make it more clear that they’re available. In particular, the balance now shows a dropdown arrow that makes the option to toggle the cleared/uncleared totals visible without having to first hover over the balance to see that it is interactive.

### CODE REVIEW

**Comment by rich-howell** [comment]
I just had a look at this on the preview build, it feels so much more natural to me to have the name show a menu of items. This gets a vote 👍 from me

**Comment by j-f1** [comment]
I’m glad you like it! Do you think the split of actions between the 2 dropdowns make sense, or should I merge them all into one?

**Comment by rich-howell** [comment]
> I’m glad you like it! Do you think the split of actions between the 2 dropdowns make sense, or should I merge them all into one?

Personally I think they should stay as they are, it feels much more natural to me this way, if I want to see balance options I click the balance for example.

**Comment by TechwizEE** [comment]
Performed a review of this PR:
- Checked out this branch, compiled and ran 
  - Side question: Is the Netifly link updated as additional commits are made?  In the commit timeline above it appeared the Netifly was out of date.
- Created test file
- Clicked one of the accounts
- Confirmed "Rename Account", "Export All Transactions", and "Close Account" appear in the budget name drop-down
  - I ran through each of the menu entries and confirmed they performed the expected actions
- Confirmed the "Show Cleared/Uncleared Totals", "Show Running Balance Column" and "Reconcile" appear in the account balance drop-down
  - I also ran through each of the menu entries and confirmed they performed the expected actions

Anything else I can exercise or inspect to assist in closing this PR?

**Comment by MatissJanis** [comment]
👋 Sorry to take so long to review this PR.

I have very mixed feelings about this change, so I'd prefer to hear out some more opinions before merging/not merging this.

Reconciliation, exporting and hiding/showing columns felt more "natural" for me to be in the hamburger menu. I see these actions relating to the **transaction table** instead of the **account**. Hence why I think having them in the existing spot makes more sense.

Whereas renaming/closing account: I'm ok with the proposed change there. That makes sense.

**Comment by j-f1** [comment]
After having this open for a while and thinking about it, I feel like this isn’t much of an improvement. Will close for now but may come back later with a different proposal if I come up with something better.

**Pull request closed without merging**
