### PR TITLE
add support for auto theme

### PR DESCRIPTION
**Pull request by spezzino**
Add support for automatic theme switching based on system theme

### CODE REVIEW

**Comment by MikesGlitch** [comment]
Looks good. 
 
Is "Auto" the right name for this? Most places I've seen this type of functionality it has been called "System default" which I think gives more clarity. I think non techies might not understand "Auto" means it takes the system setting

**Comment by rich-howell** [comment]
@spezzino  If I have it set to System Default and my System Default is light the Dark Mode selector in the top right defaults to light 

image

**Comment by spezzino** [comment]
@rich-howell @MatissJanis 

Unless this is an existing bug in the stable version, I think the idea of that button is to cycle through the options. 
When you are in the light theme you see the moon to switch to dark theme
image

When you are in dark theme, you see the sun to switch to light theme
image

With this PR, the new cycle will be Light (shows Moon icon to switch to Dark theme) -> Dark (shows Screen icon to switch to system theme) -> System (shows Sun icon to switch to Light theme)

**Comment by youngcw** [comment]
I think it would be much more clear to have the system icon always show when in the "system default" setting for theme, or no theme indicator at all.  Currently its impossible to tell if you are using system default without looking at the settings page.

**Comment by spezzino** [comment]
what if that button opens a dropdown to choose the theme? It will show the current theme icon and give you the option to switch to another option

**Comment by spezzino** [comment]
changed the button to include a dropdown to allow theme selection
image

**Comment by MikesGlitch** [comment]
lgtm
test

**Comment by joel-jeremy** [comment]
This looks good! I think we should just remove the theme icon on the top of the page since I would imagine people would only select a theme they prefer once and would never change it again or at least for a long time. Thoughts?

**Comment by youngcw** [comment]
@joel-jeremy I like the option to flip back and forth on the theme based on where im at or time of day.  So I like the easy change, but Im not set on the current button behavior.

**Comment by spezzino** [comment]
> @joel-jeremy I like the option to flip back and forth on the theme based on where im at or time of day. So I like the easy change, but Im not set on the current button behavior.

@youngcw the button will now open a dropdown

**Comment by youngcw** [comment]
@spezzino Can you get this updated?  To pass the visual regression test you will need to update the screenshots.  One of the yarn commands should do that for you.

**Comment by spezzino** [comment]
> @spezzino Can you get this updated? To pass the visual regression test you will need to update the screenshots. One of the yarn commands should do that for you.

@youngcw, tried to update the snapshots by I still get errors. Seems that a font is different in my environment (I'm using the provided devcontainer to develop). What else can I do?

**Comment by youngcw** [comment]
> @youngcw, tried to update the snapshots by I still get errors. Seems that a font is different in my environment (I'm using the provided devcontainer to develop). What else can I do?

have you tried running locally instead of in the container?  I don't know if the other maintainers use the dev container

**Comment by MatissJanis** [comment]
FYI: here are the VRT instructions - https://github.com/actualbudget/actual/blob/master/packages/desktop-client/README.md#visual-regression

**Comment by MatissJanis** [comment]
You might also want to update your branch with latest changes in `master`.

**Review by youngcw — APPROVED** [review]

**Comment by youngcw** [comment]
@spezzino Can you merge master and get the vrt updated again?  Ill merge this in as soon as that is taken care of again.

**Review by youngcw — APPROVED** [review]

**Pull request merged**
