### PR TITLE
fix: Don't allow duplicate cat-groups in budget at renaming

### PR DESCRIPTION
**Pull request by FlorianLang06**
Checks:

 - UI Level check to check for checking duplicate group name (create and rename)
 - DB level check for the same (create and rename/update)

Inspired from PR #2262 
Fixes: #2428

### CODE REVIEW

**Comment by Teprifer** [comment]
Tested with test budget:
Add new group with the same name, prevented from doing so.
Attempted to rename a group to the same name as the other group, prevented from doing so.

Looks like the dupe check is running when trying to hide a group category as well, and is presenting an error when trying to do that.

image



This issue isn't present in the latest edge release(just pulled).

**Comment by FlorianLang06** [comment]
But the internal error message isn't good. The user didn't know what's the problem. 

I am not sure if I tested wrong but in the lasted edge version this only work at creating for me. At renaming it's done normally

**Comment by FlorianLang06** [comment]
I can look into this later

**Comment by Teprifer** [comment]
> But the internal error message isn't good. The user didn't know what's the problem.
> 
> I am not sure if I tested wrong but in the lasted edge version this only work at creating for me. At renaming it's done normally

Just to clarify, the hiding group error is what I tested for in edge to rule out it being an existing issue. 

The console message is from trying to hide the group and it was throwing the internal error notice at the same time.

**Comment by FlorianLang06** [comment]
> > But the internal error message isn't good. The user didn't know what's the problem.
> > I am not sure if I tested wrong but in the lasted edge version this only work at creating for me. At renaming it's done normally
> 
> Just to clarify, the hiding group error is what I tested for in edge to rule out it being an existing issue.
> 
> The console message is from trying to hide the group and it was throwing the internal error notice at the same time.

Now I understood what you mean. I try fix this. Thanks for reporting

**Comment by FlorianLang06** [comment]
@Teprifer pls try again if its fixed for now

**Comment by Teprifer** [comment]
Nice :)

Renaming existing to the same as another - prevented - OK
Add group to the same as another - prevented - OK
Hide group - OK
Show group again - OK
Hide category - OK
Show category again - OK

**Comment by Teprifer** [comment]
Sorry realised I should have a go on mobile, my previous comment was desktop only:

* Renaming existing to the same name as another - prevented - Error
While it doesn't apply the rename to the group, it does retain the invalid group name on the modal dialogue.
image



* Add group with the same name as another - prevented - Error 

image
_Note it clears the category name entry box automatically(this is good, just explaining the image)_

Hide group - OK
Show group again - OK
Hide category - OK
Show category again - OK

**Comment by FlorianLang06** [comment]
> Sorry realised I should have a go on mobile, my previous comment was desktop only:
> 
> 
> 
> * Renaming existing to the same name as another - prevented - Error
> 
> While it doesn't apply the rename to the group, it does retain the invalid group name on the modal dialogue.
> 
> image
> 
> 
> 
> 
> 
> 
> 
> * Add group with the same name as another - prevented - Error 
> 
> 
> 
> image
> 
> _Note it clears the category name entry box automatically(this is good, just explaining the image)_
> 
> 
> 
> Hide group - OK
> 
> Show group again - OK
> 
> Hide category - OK
> 
> Show category again - OK

It sounds like the database check is applied(this is the internal error message) but the check in the UI not. I look into this later.

It's very good that you are testing all of this stuff because I didn't consider all this possible problems.

**Comment by FlorianLang06** [comment]
It's my first PR. But actually it makes fun to fix a issue. I decided to contribute to projects I personally use. So it's a benefit for many people including myself

**Comment by FlorianLang06** [comment]
@Teprifer do you think thats ok? Beause the * normally means that something is missing. But it don't have a better idea.
image

**Comment by youngcw** [comment]
> do you think thats ok? Beause the * normally means that something is missing. But it don't have a better idea. image

This would be good.  It may be better to be more expicit and say "Error" instead of just a *

**Comment by Teprifer** [comment]
Sorry I'm right proper tuckered out from work so haven't been able to look at this again. Taken a brief look at what you've done since.

I see you've picked up the rename group on mobile and resolved that.
Next up, the mobile internal error renaming an existing group? :)

**Pull request closed without merging**
