### PR TITLE
Remove duplicate migration and default-db.sqlite files

### PR DESCRIPTION
**Pull request by j-f1**
These files will be automatically recreated by `yarn build:api`, `yarn build:browser`, and `yarn start:browser`, so we don’t need them in the repo.

### CODE REVIEW

**Comment by MatissJanis** [comment]
Seems that there is a bug (thus e2e failing).

1. open netlify
2. click on "create test budget"
3. you're now in the password selection page 🤔

**Comment by j-f1** [comment]
The following error is present in the console:

> Error: no such table: __meta__

which is weird because all of the default databases appear to be identical.

**Comment by j-f1** [comment]
This seems to work now! Turns out macOS `cp` and Linux `cp` behave very differently. Fun!

**Comment by MatissJanis** [comment]
```
➜  actual git:(jed/rm-dupe-files) yarn build:browser
➤ YN0000: [@actual-app/api]: Process started
➤ YN0000: [@actual-app/api]: Process exited (exit code 0), completed in 4s 534ms

➤ YN0000: [@actual-app/web]: Process started
➤ YN0000: [@actual-app/web]: Process exited (exit code 0), completed in 12s 864ms

➤ YN0000: [Actual]: Process started
➤ YN0000: [Actual]: Process exited (exit code 0), completed in 3s 897ms

➤ YN0000: [eslint-plugin-actual]: Process started
➤ YN0000: [eslint-plugin-actual]: Process exited (exit code 0), completed in 2s 797ms

➤ YN0000: [@actual-app/import-ynab4]: Process started
➤ YN0000: [@actual-app/import-ynab4]: Process exited (exit code 0), completed in 2s 324ms

➤ YN0000: [@actual-app/import-ynab5]: Process started
➤ YN0000: [@actual-app/import-ynab5]: Process exited (exit code 0), completed in 2s 242ms

➤ YN0000: [loot-core]: Process started
➤ YN0000: [loot-core]: Process exited (exit code 0), completed in 9s 949ms

➤ YN0000: [node-libofx]: Process started
➤ YN0000: [node-libofx]: Process exited (exit code 0), completed in 2s 504ms
➤ YN0000: Done in 41s 130ms
realpath: /Users/matiss/repos/actual/actual/packages/loot-core/bin/../../desktop-client/public/data: No such file or directory
```

**Comment by j-f1** [comment]
Weird! Not seeing that on my end but pushed a change which should fix it.

**Review by MatissJanis — APPROVED** [review]
Sweet!

**Comment by j-f1** [comment]
Can you publish `@actual-app/api@v5.1.2` and deprecate v5.1.1?

**Pull request merged**
