### PR TITLE
Change month picker hover background color

### PR DESCRIPTION
**Pull request by pprimor**
This is just a quick fix for https://github.com/actualbudget/actual/issues/2090. It's my first time contributing to the project so I thought I'd start with something simple.

### CODE REVIEW

**Comment by youngcw** [comment]
Much better, thanks.  Can you look at getting the visual regression tests taken care of?

**Comment by youngcw** [comment]
I don't know if you have seen this but it walks through how to update just the snapshots that have changed. https://github.com/actualbudget/actual/tree/master/packages/desktop-client/README.md

**Comment by youngcw** [comment]
> For instance, I had to use `E2E_START_URL=https://192.168.1.79:3001 yarn vrt` to launch the visual regression tests.

Are you running the test server on a different machine than your local one?

It looks like the screen grabs that you updated don't have anything to do with the change you made.  Something must not have run right.

I'm not sure why the github tests are not running, but that may fix itself with a new commit to fix the merge conficts

**Comment by pprimor** [comment]
> Are you running the test server on a different machine than your local one?

I was not. I see you've updated the README.

Also, it seems the last merge commits fixed the issue with the failing tests.

**Review by youngcw — APPROVED** [review]
Looks good.  My guess is that the vrt doesn't actually see this change so the merge fixed everything.

**Pull request merged**
