### PR TITLE
Custom Reports: Include current

### PR DESCRIPTION
**Pull request by carkom**
Testing an option to add/remove current interval to "live" ranges.

WARNING: Do not use live budget files with this PR as it contains a migration. Please use a copy or a test budget ONLY.

~I still need to add a migration so that it can be saved as part of the report. Holding off on that right now as I don't want it to mess up anyone's budget file.~

### CODE REVIEW

**Comment by Teprifer** [comment]
The 'current interval' controlled by the option is 'month' rather than what is defined by the interval option? if so I'd suggest renaming it to _Include current **month**_ for clarity. e.g. interval is weekly, with a live range of last 3 months, this option toggles the 4 weeks starting this month.
How it is now vs making it go by the interval option both makes sense to me (as the budgeting is monthly).

Noticed option is disabled when using a static range(makes obvious sense). Were you thinking to disable it for the interval + live ranges that it doesn't make sense for, or not worry about that?

**Comment by carkom** [comment]
> The 'current interval' controlled by the option is 'month' rather than what is defined by the interval option? if so I'd suggest renaming it to _Include current **month**_ for clarity. e.g. interval is weekly, with a live range of last 3 months, this option toggles the 4 weeks starting this month. How it is now vs making it go by the interval option both makes sense to me (as the budgeting is monthly).
> 
> Noticed option is disabled when using a static range(makes obvious sense). Were you thinking to disable it for the interval + live ranges that it doesn't make sense for, or not worry about that?

It's not always monthly. It's based on the range interval. Example: choosing "Last week" and Interval = daily. The toggle would give you all the days from this week as well. 

If we changed it to match the interval instead and you chose "last month" and interval = weekly. You'd see all 4 weeks of March. Select the new toggle and you'd get the 4th week of April - the first three weeks would be missing. Not sure that makes sense to ever have a view like that. Also, it makes the code needlessly complicated.

I see your point with labeling, because it's not actually "current interval". I've changed the wording to follow the "range" selection. So it says "Include current month" when a monthly range is chosen and "Include current week" when a weekly range is chosen.

**Comment by Teprifer** [comment]
Ah! I see where I was getting confused, thanks. :) (there was an extra layer of misunderstanding on my part too)

**Comment by carkom** [comment]
@Teprifer, can you check this meets your expectations?

Make sure to only use a copied budget file or a test file as the migration in this PR will cause the budget file to not work with edge.

**Comment by Teprifer** [comment]
Awww <3

Yeah I always test in a browser data cleared chrome window with a freshly exported budget.

* Looks like the enable current month isn't interacting properly with the show activity clicks when trying out the options.

1. Create custom report
2. Change to data table
3. Change mode to Time
4. Change range to last1 2 months
5. Click a category total (overall, not monthly)
6. note the filter correctly ends at the end of the previous month
7. Click back to return to the data table
8. Enable include current month option
9. Click a category total  (overall, not monthly)
10. note the filter incorrectly ends at the end of the previous month, and not today's date(or end of this month).
11. Go back to the data table
12. Disable include current month option
13. Click a category total  (overall, not monthly)
14. note the filter incorrectly ends at the end of the current month, and not the end of last month.

15. Saving then leaving and re-opening the report at this point
16. Click a category total  (overall, not monthly)
17. note the filter correctly ends at the end of the previous month


* Year to Date, includes up to current date regardless of the include current option setting.
Not sure this is incorrect, since by definition 'to date' means, well, to the current day. But also there's the option to include/exclude the current X (see next point). Eh, thoughts? For what it's worth I can see it both ways reasonably equally.
Mayyyybe it could be a thing that if 'year to date' or 'all time' is selected this option is forced to On automatically(to keep the current behaviour), and then users could optionally turn it off? 

* The option 'include current \<week/month\>' has no time unit when using a range of 'year to date' 'last year' or 'all time', and so just reads 'include current', wonder if for these it should be 'month' for year to date, and 'year' for all time. For 'last year' eh, disable/grey out?? Have a think on this and the above and what you think makes sense - happy to discuss further  :)

* Might be unrelated to this PR, but I don't see this in edge(a few days old), activity click not filtering by date correctily for time mode bar and line graphs:
Create custom report
Change mode to Time
Click on a bar
Filter has:  date is (nothing)
image

Same on the line graph
_Ignoring the amount filtering you're fixing in another PR_

Besides those minor points it looks pretty good.

**Comment by carkom** [comment]
@Teprifer So there's a regression from a previous PR that broke filters. This PR is not focused on fixing those at all. You can check #2785 for the fix for filters corrections.

Can you edit your review (above) and take out anything that relates to filters or show activity clicks? It would be much easier if we could keep the issues separate. Cheers!

**Comment by Teprifer** [comment]
@carkom Sorry didn't realise the filter correction stuff included the dates bit (only aware of amounts) so thought maybe related as this has a date affecting option. And the first part was linked to the new option in this PR, anyway, removed.

**Comment by carkom** [comment]
> Awww <3
> 
> Yeah I always test in a browser data cleared chrome window with a freshly exported budget.
> 
>     * Year to Date, includes up to current date regardless of the include current option setting.
>       Not sure this is incorrect, since by definition 'to date' means, well, to the current day. But also there's the option to include/exclude the current X (see next point). Eh, thoughts? For what it's worth I can see it both ways reasonably equally.
>       Mayyyybe it could be a thing that if 'year to date' or 'all time' is selected this option is forced to On automatically(to keep the current behaviour), and then users could optionally turn it off?
> 
>     * The option 'include current <week/month>' has no time unit when using a range of 'year to date' 'last year' or 'all time', and so just reads 'include current', wonder if for these it should be 'month' for year to date, and 'year' for all time. For 'last year' eh, disable/grey out?? Have a think on this and the above and what you think makes sense - happy to discuss further  :)
> 
> 
> Besides those minor points it looks pretty good.

I think I've fixed both issues. Have a look. 

Making "Year to date" and "All time" function within the "include current" logic is messy because the interval type can change. Example: when interval = Monthly currentInterval would be current month, when interval = weekly currentInterval would be current week. Making this change dynamically adds complexity that I don't see as neccessary. 

"Year to date" is meant to be Jan 1st through today. If someone wants Jan of this year through this month minus one then they can utilize the static filters. Same with "All time" range. It's one extra click to use these static fields.

**Comment by Teprifer** [comment]
> I think I've fixed both issues. Have a look.
> 
> Making "Year to date" and "All time" function within the "include current" logic is messy because the interval type can change. Example: when interval = Monthly currentInterval would be current month, when interval = weekly currentInterval would be current week. Making this change dynamically adds complexity that I don't see as neccessary.
> 
> "Year to date" is meant to be Jan 1st through today. If someone wants Jan of this year through this month minus one then they can utilize the static filters. Same with "All time" range. It's one extra click to use these static fields.

Ah yep, I was thinking it'd be static as month for YTD and year for all time(regardless of interval setting), but as I mentioned I don't think there's an incorrect approach here, so the simplest makes sense. Besides which I imagine it's fairly niche anyhoo.

Had a look, seems fine, my brain is a bit fried, but if you're happy with it, onwards! :)

**Review by youngcw — DISMISSED** [review]

**Comment by youngcw** [comment]
I just realized, that the time range options probably need updated to consider this setting.  
For example, if you select last 6 months with "include current" you get 7 months in the report.

**Comment by carkom** [comment]
> I just realized, that the time range options probably need updated to consider this setting. For example, if you select last 6 months with "include current" you get 7 months in the report.

That's as intended right? "Last 6 months" (eg previous 6 months) would be the 6 full (completed) months before the current month. If you tick "include current" then you'd get those same 6 months plus this month (6 + 1 = 7).

The other option would be to make the "Last 6 months" (and other options like it) dynamic. So with includeCurrent selected it would give you Dec '23 to May '24 with it unselected you'd get Nov '23 to Apr '24.

It could make sense either way. I find it a bit confusing that the start date changes based on if "include current" is selected.  In my mind "last 6 months" is (current month - 7) through (current month - 1). The status of "includeCurrent" wouldn't change that.

**Comment by youngcw** [comment]
Your second option is what I expected to happen. For me the "6" part takes precedent and "last x months" could easily mean either before current or with current, so I then expect 6 months in the report.  Maybe we can see what others think.

**Comment by Teprifer** [comment]
With the option off by default the logic is correct. 
But I see the point of having it on by default as that matches current behaviour. 

I think it could also be approached as a discoverabilty thing, if the include current option was right under the range then it stopped be obvious what's going on. 

Or as you say, update the range text to reference there current month being included(or not), either by changing the number, or appending "(plus current X)" or some variation of.
Then users could discover the option in the options menu, is easy to find.

**Comment by twk3** [comment]
Just to add my opinion. It's currently working how I would expect. I think it's behaviour is clear when you use "last month" as the example.

If I select "Last month" from the live time range (and I'm graphing by time). And include current month is on. I see last month and this month. Not just this month (I think that would be worse). If I toggle current month off, I just see last month. This seems correct, and based on that, how it currently works for 'last 6 months' also makes sense to me. I get 7 months listed, just the current probably being incomplete. (Which I can remove thanks to this toggle).

**Comment by carkom** [comment]
> Just to add my opinion. It's currently working how I would expect. I think it's behaviour is clear when you use "last month" as the example.
> 
> If I select "Last month" from the live time range (and I'm graphing by time). And include current month is on. I see last month and this month. Not just this month (I think that would be worse). If I toggle current month off, I just see last month. This seems correct, and based on that, how it currently works for 'last 6 months' also makes sense to me. I get 7 months listed, just the current probably being incomplete. (Which I can remove thanks to this toggle).

Good explanation of how my mind was working. Thanks! @youngcw, are you okay to merge as is?

**Review by youngcw — DISMISSED** [review]
I guess if others like how it is then we can merge it and see what the community thinks.

**Review by twk3 — COMMENTED** [review]
@carkom I'm running into one issue with this currently

When jumping between 'last 6 months' and 'This month, (or one of the other disabled options). The include current get disabled (as expected, maybe it should be disabled but on for some of these, but that's not the issue). And then if I jump back to 'last 6 months' it stays disabled, which is unexpected.

As a user in this workflow, I may have never opened "Options" at all. So the fact that my initial "last 6 months" query, and my later one produced different results is unexpected.

**Comment by twk3** [comment]
A future improvement, that I've seen in some other graphing systems, is that when graphing by time, an incomplete month is often displayed visually differently than the others. (meaning the latest month when include current is on). Often this is just a slight colour shift, or maybe some masking.

**Comment by carkom** [comment]
This ready to go, can anyone offer a code review?

**Comment by carkom** [comment]
> @carkom I'm running into one issue with this currently
> 
> When jumping between 'last 6 months' and 'This month, (or one of the other disabled options). The include current get disabled (as expected, maybe it should be disabled but on for some of these, but that's not the issue). And then if I jump back to 'last 6 months' it stays disabled, which is unexpected.
> 
> As a user in this workflow, I may have never opened "Options" at all. So the fact that my initial "last 6 months" query, and my later one produced different results is unexpected.

Should be fixed.

**Review by youngcw — APPROVED** [review]

**Review by youngcw — APPROVED** [review]

**Pull request merged**
