### PR TITLE
Enable "Net" type for pie chart graphs

### PR DESCRIPTION
**Pull request by SimonSomlai**
This feature relates to this request: https://github.com/actualbudget/actual/issues/2804. It enables users to create a pie-chart overview of all their accounts' net balance and provides more insight into where they might be over/under-weighed; Something like;

Screenshot 2024-06-07 at 20 06 59

The caveat to this is that we'll now show negative balances, which is a bit confusing for pie-charts. Two solutions for this;

- Accept this option, since it provides more benefit than the downside of this edge case
- Automatically hide negative balances from pie-charts (set them to 0 before rendering the graph). But including an option to toggle negative balances:

Screenshot 2024-06-07 at 20 02 42

Let me know what you think!

### CODE REVIEW

**Comment by youngcw** [comment]
I think there should be some indication of a clamped category.  Your option 2 is a good option, or maybe a button that flips the chart to show the negative categories.  A list of categories that were clamped on the side could also work, with an amount listed.

**Comment by carkom** [comment]
Firstly, I agree that this needs a fix. Having a net value is imperitive. I've been toying with a fork that fixes this issue for all graphs (not just the donut).

I think you're using a very idealistic data set here that only matches certain use cases. Firstly, you're displaying Account Net which is much cleaner than something like Category Net where the values are much more mixed with regard to positives and negatives. If we're going to change this it needs to work for every option of the graph otherwise it becomes a support nightmare.

Many users are going to have accounts that are negative which makes things...well - you say confusing, I say impossible to display in a pie chart. Here's an example:

| BofA (green) overlaps multiple accounts  | 4th account that is never visible |
| ------------- | ------------- |
| image | image |

Option 1 is just never going to work correctly for all users data sets and for all of the graphs options. 
Option 2 is closer to where I've landed with my solution. I'm weary of the "show negative values" toggle because it doesn't make sense in the context of all graphs and all options available (eg. the Table Graph where negative values are already displayed). 

My thought was to add 2 additional "Types" under `Net`: `Net Payment` which  only displays splits that are negative and `Net Deposit` which only displays splits that are positive.

**Comment by carkom** [comment]
Or another alternative is to make the payments and deposits options to display net payments and net deposits and if the user wants payments with no inflow transactions or deposits with no outflow transactions they can use the filters to achieve that. 

I think I'm leaning toward this option.

**Comment by SimonSomlai** [comment]
> Option 2 is closer to where I've landed with my solution. I'm weary of the "show negative values" toggle

I agree that adding them in the global menu is confusing. But maybe there's a need for "a graph setting" beside the global chart settings? Something like a cog icon in the top left of the graph for example could cover graph-specific settings to show/hide negative values. Something like this, but less ugly. It would open a chart-specific dropdown and disable them/grey them out in the legend with a popover. This to me would be the simplest solution, but I'm aware the design system doesn't like over-cluttering the UI with more settings/icons.

Screenshot 2024-06-12 at 09 13 12


> Or another alternative is to make the payments and deposits options to display net payments and net deposits and if the user wants payments with no inflow transactions or deposits with no outflow transactions

This feels more like adding a filter in a setting that's trying to be a transaction type. Payments are outflows, deposits are inflows and net is the difference. I wouldn't add more sub-division to this. Alternative proposal: adding a "account net" filter option under the "Account" filter which gives you a numeric filter instead of the names

image

**Comment by carkom** [comment]
@SimonSomlai Can you check if #2871 works for your use cases?

**Comment by youngcw** [comment]
Closing this for now as the net option was just updated for all report types.  If there is still something missing please let us know or open a new PR

**Comment by SimonSomlai** [comment]
@carkom , will install and check this out tonight! But it probably fixes the problem :) Thanks for pushing this forward 💪

**Comment by miberecz** [comment]
Is this still not implemented? I cannot choose net for pie-chart
image

**Comment by youngcw** [comment]
> Is this still not implemented? I cannot choose net for pie-chart image

This PR was never merged because a different one was added.  Your screenshot shows the net options for pie charts.  A standard net wont work with pie charts, per the discussion above

**Pull request closed without merging**
