### PR TITLE
Mobile - Add cleared and uncleared Balances in Account Details

### PR DESCRIPTION
**Pull request by HansiWursti**
Hello,

thank you for the work at Actual Budget.

I added a small Feature that i personally miss in the mobile View in Account Details.

Bildschirmfoto am 2023-12-09 um 19 21 39

Maybe it could fit into the regular Build.

Possibly one could make the Balance text a button and toggle it or just show the cleared and uncleared fields, if there are some uncleared transactions.

Thank you!

### CODE REVIEW

**Comment by shall0pass** [comment]
Thank you for taking this on! I think it would feel more visually balanced if the cleared value was on the left and the larger balance text was centered.

Clicking the balance as a button is a good idea to toggle visibility of the other two, but I don't think it would be a show stopper if you didn't implement that.

**Comment by shall0pass** [comment]
Resolves: https://github.com/actualbudget/actual/issues/1629

**Comment by joel-jeremy** [comment]
What if we put this in a modal which shows when the balance amount is clicked? WDYT?

**Comment by shall0pass** [comment]
@joel-jeremy Are there additional options or metrics you want to display here? If it's just the two that are shown above, I like the on/off idea for displaying them.  If there are more, then I could see possibly moving to a modal as the screen becomes space limited.

**Comment by Teprifer** [comment]
Desktop has the order as: Balance, Cleared, Uncleared
For consistency I think the mobile version should match.

Cleared value should be colour neutral in my view(same as desktop) as there's nothing about it that needs to draw attention to it. If anything it would be the uncleared value that would be a different colour - but that would be inconsistent with the desktop.

Putting it in a modal is inconsistent with desktop, and also removes the ability to always know how much has or hasn't cleared at a glance. 1 vote for keeping it as a toggle.

**Comment by youngcw** [comment]
I like the idea of clicking the balance to show the details. I don't think I care between total on the left or total in the middle.

**Comment by HansiWursti** [comment]
Hello,

thank you for your kind feedback.

I am no real professional dev and i am happy that i somehow created something working.

I changed it a little bit, so that the main balance stays centered and the other two are now left and right.

The logic is now as following:

If there are some uncleared transactions, it shows the other two balances.
If the uncleared balance is zero, the cleared and the main balance are simply the same.
So i think this is the best way giving the user some extra info if necessary and simply hide it if there is no real benefit.

Bildschirmfoto am 2023-12-10 um 17 41 19
Bildschirmfoto am 2023-12-10 um 17 41 33

Thank you!

**Comment by HansiWursti** [comment]
Hi,

i fixed the VRT Problem, so the PR should be ready for review and possibly be merged.

Thank you!

**Comment by joel-jeremy** [comment]
> Are there additional options or metrics you want to display here? If it's just the two that are shown above, I like the on/off idea for displaying them. If there are more, then I could see possibly moving to a modal as the screen becomes space limited.

I think we would want to add more account actions in the future such as reconciliation. Having the cleared/uncleared and the reconciliation action in one place would be ideal.

**Comment by shall0pass** [comment]
I find the fields useful in the current spot, but I see your point about reconciling.  One though is that if we add a modal for reconciling, we could possibly blur the view behind and redisplay the values in the modal so they're present for that interaction.  Another idea could be to add the reconciling more inline, possibly by pressing the account name to expand a larger area for the reconciling buttons.

**Comment by HansiWursti** [comment]
Hi,

i would love to see this feature in the next release

Is there a problem to merge this request in it's current state?

Thank you

**Comment by shall0pass** [comment]
I don't have any issues with it.  I'm hoping at least one other person will comment as I don't want to be the lone voice in wanting this feature.  There is a merge conflict that needs to be addressed and it likely won't be merged until after the merge freeze if we can find agreement to move forward.

Thanks for your hard work!

**Comment by youngcw** [comment]
I think it's fine as is, assuming the conflicts get cleared up. I still think a toggle on/off would be better and match the desktop view better. That is probably fine as as separate PR though

**Comment by Teprifer** [comment]
> I think it's fine as is, assuming the conflicts get cleared up. I still think a toggle on/off would be better and match the desktop view better. That is probably fine as as separate PR though

I agree, perhaps get the issue created now and linked back to this to keep track of it?

**Comment by HansiWursti** [comment]
Hi @shall0pass, @youngcw,

Merge conflict should hopefully be fixed.

Thank you!

**Review by shall0pass — APPROVED** [review]

**Pull request merged**
