### PR TITLE
Prefer using let over const in most cases

### PR DESCRIPTION
**Pull request by j-f1**
Heuristics:

- Use `let` in almost all cases, except:
- when you call `require`, `useState`, or `useReducer`, use const
- when you destructure `props`, `this.props`, or `this.state`, use const
- I considered requiring `const` usage with `UPPER_SNAKE_CASE` variables, but that doesn’t work because they’re modified in several cases.

### CODE REVIEW

**Comment by TomAFrench** [comment]
Can you give some motivation for why to prefer `let` over `const`? Restricting mutability is generally good from a code readability standard in my experience.

**Comment by j-f1** [comment]
Practically: the codebase already heavily uses `let` so I wanted to standardize that
Ideologically:
- if you want to reassign a variable you have to change it to `let`
- function params, catch bindings, and other places the language introduces new variables are all `let` bound rather than `const` bound
- `const` does not actually enforce immutability, only frozen objects or the upcoming records/tuples do that

> But I don’t have super strong feelings and would be willing to close this PR or open an alternative that enforces `const` usage where possible

**Comment by TomAFrench** [comment]
Generally I prefer immutability wherever mutability is unneeded so my preference is that we standardise on `const`. 

>if you want to reassign a variable you have to change it to let

Preferring `const` means that the usage of `let` conveys the information that we're expecting to reassign this variable.

> function params, catch bindings, and other places the language introduces new variables are all let bound rather than const bound
> const does not actually enforce immutability, only frozen objects or the upcoming records/tuples do that

Yep, these are unfortunate features of TS. My thinking is "don't let perfect be the enemy of the good" here however as we'll get the benefits for all the other cases.

**Comment by MatissJanis** [comment]
Personally I'm OK with either using one or the other. But not both.

So if it's not possible to use `let` everywhere - I'd prefer to use `const`.

**Comment by trevdor** [comment]
The heuristics listed feel like mental overhead I’d like to avoid. However, I’d be interested in why those cases you name need to be `const`, @j-f1. I’ve worked in prefer-const projects for too long to have considered it. 

I, too, am fine with either and probably prefer one or the other, but also prefer not making a huge breaking change (i.e. lean toward the existing convention).

Also, what are the chances we NEVER need mutability in our entire app? I’ve never worked on a large project without some exceptions. Are we just thinking lint exceptions for such cases?

**Comment by j-f1** [comment]
> The heuristics listed feel like mental overhead I’d like to avoid.

The lint rule I’ve created handles the heuristics automatically, and has fix support so you just need to run `lint --fix` to get everything up to spec.

> I’d be interested in why those cases you name need to be `const`

I chose them based on reviewing the code and trying to match them fairly closely (although tbh there is not much consistency at the moment, as you can see from the diff).

> ps. - if you need help with this migration - let me know. Happy to lend a hand. It's going to be very messy and very big..

If the migration requires significant manual input we are doing it wrong. Everything needs to be handled by auto-fixable ESLint rules, both for the initial migration and for all future contributions.

**Pull request closed without merging**
