### PR TITLE
:sparkles: (bank-sync) add explicit nordigen bank-sync warning

### PR DESCRIPTION
**Pull request by MatissJanis**
Adding an explicit bank-sync warning disclaimer.
#724 

Screenshot 2023-03-21 at 20 09 54

### CODE REVIEW

**Comment by MatissJanis** [comment]
cc @rich-howell maybe you have some feedback about the copy in this disclaimer.

**Comment by MatissJanis** [comment]
oo.. I like the idea of including links to their privacy policy. Updated the copy.

Screenshot 2023-03-21 at 21 59 15

**Comment by MatissJanis** [comment]
I like that! @j-f1 any further thoughts from you?

**Comment by j-f1** [comment]
That works for me!

**Comment by MatissJanis** [comment]
Screenshot 2023-03-21 at 23 32 12

**Review by j-f1 — COMMENTED** [review]
Sorry for the delay in reviewing! one small nit: once you’ve selected a country, there is no padding between the bank name input and the warning:

Screenshot_2023-03-22 23 42 36

**Review by j-f1 — APPROVED** [review]
LGTM!

**Review by j-f1 — APPROVED** [review]

**Pull request merged**
