### PR TITLE
Improve handling of the undo/redo shortcuts

### LINKED ISSUE #606: Improve undo/redo keyboard shortcut handling
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When hitting CMD+Z to undo, sometimes I find Safari reopening my last closed tab. When I re-close that tab, I come back to find the undo has been successfully completed. Similarly, in Discord, @&zwnj;Rohan said:

> Many times, I expect the textfield to get reset when using CMD+Z but it ends up deleting my recently added transaction.

I think there should be 2 changes here to improve the UX:

- call `preventDefault` if we can handle the undo ourselves to avoid the browser doing something weird
- disable the undo/redo shortcuts if the user is focused on a text input

### What error did you receive?

_No response_

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

_No response_

### Operating System

None

### PR DESCRIPTION
**Pull request by j-f1**
Fixes #606:

- when the undo/redo is handled, stop the browser from applying its automatic undo/redo behavior (for example, Safari will reopen the last closed tab)
- when focused on an input field, give the browser’s undo precedence over Actual’s undo (e.g. undo making changes to a text field that haven’t yet been committed)

### CODE REVIEW

**Comment by MatissJanis** [comment]
I like where this is going, but I found a small bug:

Repro:
1. delete a transaction
2. click on notes field but do not change anything there
3. click outside notes
4. ctrl+z (nothing happens)
5. ctrl+z (deleted transaction reappears)

Previously the first ctrl+z would bring back the transaction. But this no longer happens.

**Review by MatissJanis — CHANGES_REQUESTED** [review]
requesting changes so the labels get auto-updated

**Comment by j-f1** [comment]
That looks like it was a pre-existing bug but I’ve fixed it!

**Review by MatissJanis — APPROVED** [review]
Nice!

**Pull request merged**
