### PR TITLE
Include more information in payee of split parent

### PR DESCRIPTION
**Pull request by jfdoming**
Split from #2923

Before:
image

After:
image

### CODE REVIEW

**Comment by youngcw** [comment]
What do you think about reverting the subdued text for the payee back to the same color as regular lines?

**Comment by jfdoming** [comment]
> What do you think about reverting the subdued text for the payee back to the same color as regular lines?

Just for the payee or also the category? IMO the consistency across the two child-derived fields is nice (I could even see us doing something similar to this PR for categories, not sure). But I can see the argument for just payee, since it is now no longer a "special" payee, let me know your thoughts!

**Comment by jfdoming** [comment]
I think it might make sense to keep it as is, then; my understanding from playing around with the UI is we've been using that grey colour to signify "can't edit this field" and the parent here is indeed not editable

**Review by joel-jeremy — APPROVED** [review]
LGTM! It would be awesome to have in mobile view too but we can address in a separate PR. :)

**Pull request merged**
