### PR TITLE
Mobile split transactions

### PR DESCRIPTION
**Pull request by joel-jeremy**
Mobile split transactions + a hook to limit editing a field when another is currently being edited

### CODE REVIEW

**Comment by youngcw** [comment]
It feels a little bit cumbersome, but I can't think of anything to make it better other than maybe auto propagating the payee or something.

The number in the split amount cell stays there when I click it.  Could that be changed to go away or something when entering a value?  Could the behavior match the big amount at the top?

I don't think its obvious that pressing the split button at the bottom adds a new split line.

**Comment by Redbox3070** [comment]
Hi, I tested it also with some account transfers and it seems to work well. It's quite intuitive since the "Amount left" button substitutes "Add transaction"👍

**Comment by youngcw** [comment]
Nice! I like those updates

**Comment by joel-jeremy** [comment]
@youngcw Would you mind approving if everything is good?

**Review by youngcw — APPROVED** [review]

**Pull request merged**
