### PR TITLE
Hide hidden groups and categories in spending report category selector

### PR DESCRIPTION
**Pull request by kyrias**
In the future we should have a way to optionally toggle these to be visible like we do on the budget page, but that requires figuring out a decent UI for this.

### CODE REVIEW

**Comment by kyrias** [comment]
Hmm, I'm a bit confused, why are `hidden` and `is_income` integers rather than booleans?  I think that means that we're lying in other places where we declare those fields as `boolean`.

**Comment by MatissJanis** [comment]
Small bug: when the group has only hidden categories - it cannot be toggle-able.

Demo budget:
[2023-09-16-_test-budget.zip](https://github.com/actualbudget/actual/files/12640710/2023-09-16-_test-budget.zip)

**Comment by MatissJanis** [comment]
Also: I don't think we should remove the hidden categories from the category selector. Ideally we would have a way to toggle the visibility of them (as in budget page), but until we have this functionality - I would argue it's better to show them and allow people to toggle them off than it is to explicitly remove them without the option of adding them back in.

**Comment by kyrias** [comment]
> Small bug: when the group has only hidden categories - it cannot be toggle-able.

That's not a new bug, but I was meaning to hide hidden groups as well.

> but until we have this functionality - I would argue it's better to show them and allow people to toggle them off than it is to explicitly remove them without the option of adding them back in.

I personally don't think that makes sense.  If someone explicitly marks something as hidden it should be hidden until you mark it otherwise, and until a toggle is implemented they can just mark the category as not hidden if they want to see it.

**Comment by MatissJanis** [comment]
A relatively _quick_ UI fix here might be:
- show the hidden categories by default
- use a different color for them (light gray?)
- by default: have them in the "unchecked" state

That wouldn't require any specific toggle element, but would be a short-term solution to the problem.

**Pull request closed without merging**
