### PR TITLE
Create .editorconfig

### PR DESCRIPTION
**Pull request by coliff**
Help keep code formatting consistent

### CODE REVIEW

**Comment by jlongster** [comment]
What does this do that Prettier doesn't?

**Comment by bryanbanda** [comment]
> What does this do that Prettier doesn't?

I reckon Prettier will format your code after the fact but editorconfig will allow the editor to already format the code as you write it. One problem that might arise is a divergence between `prettier` & `editorconfig` settings should one be updated and the other one isn't

**Comment by j-f1** [comment]
Prettier [supports EditorConfig](https://prettier.io/docs/en/configuration.html#editorconfig), so they won’t conflict (as long as you don’t include settings that Prettier doesn’t support). As @bryanbanda said, it makes the editor experience nicer by e.g. telling your editor where to place indent guides, and which encoding to use.

**Comment by jlongster** [comment]
Ok cool, sounds good. Are we sure that this is consistent with the prettier settings? I'll merge as-is but we should make sure they are aligned (and that prettier is correctly set up)

@j-f1 I should have known that, I remember that now :)

**Pull request merged**
