### PR TITLE
Custom Reports changes

### PR DESCRIPTION
**Pull request by carkom**
Fixing small visual issues with custom reports.

### CODE REVIEW

**Comment by youngcw** [comment]
Looks good aside from the VRT still not passing

**Comment by youngcw** [comment]
The scroll bars do seem really bright on the dark modes.  Could the existing scrollbar styles be used instead of manually setting up a new style?

**Review by youngcw — DISMISSED** [review]
All seems fine, but I do think that scrollbars should be made to look more like the rest of the app at some point.

**Comment by carkom** [comment]
> The scroll bars do seem really bright on the dark modes. Could the existing scrollbar styles be used instead of manually setting up a new style?

Horizontal colors have purposefully been left out. Wasn't sure where it might be used to strategically hide the horizontal ones. I created a new style for when/if we do want to show horizontal bars and matched the color the the "lightScrollbar". Cheers!

**Review by youngcw — APPROVED** [review]

**Pull request merged**
