### PR TITLE
Move all loot-design code into desktop-client

### PR DESCRIPTION
**Pull request by j-f1**
Seems to build fine, will test later.

### CODE REVIEW

**Comment by MatissJanis** [comment]
This is going to create loads of conflicts.

Is there a more gradual approach we could take? Or perhaps a codemod migration which leaves symlinks (for now)?

**Comment by j-f1** [comment]
I think the best approach here is to do it all at once (in particular so it’s easy to skip past when doing git blame etc). I am hopeful it won’t cause too many conflicts when people just modify the files in `desktop-client` or `loot-core`, and I’m happy to help out with any conflicts that do occur upon merging. I don’t think it’s worth the time sink to write a codemod since this is a one-time task applied to one medium-sized codebase, and I was able to do the whole thing mostly manually in probably less than an hour. I also don’t want to use symlinks because webpack does not support symlinks pointing to files outside of the main root dir (`packages/foo/src`).

**Comment by MatissJanis** [comment]
If we cannot do this more gracefully I would not want to do this at all. It creates more problems than it solves. And this is not just the active PRs that will get conflicts. It's also anyone changing things on the side and planing to submit a PR later on.

**Comment by j-f1** [comment]
Hm, I guess another option could be to move files into `desktop-client` a batch at a time. That would still result in the same set of conflicts though, just spread out over time. I also believe (although I have not tested this) that Git handles renames fairly well. The only issue would be if someone changed any of the imports that reference `loot-design`, but most changes to content or logic should not have any issues. In particular, all of the files in `loot-design` were correctly marked as “moved” instead of being deleted and added (except where I did actually delete the file).

**Comment by MatissJanis** [comment]
Can we test this hypothesis with a small batch of file-moves? Hopefully it works as you describe 🤞

**Comment by j-f1** [comment]
Will grab a few of the open PRs and try to merge this branch into them as a test and report back here with the results when I get a chance.

**Comment by j-f1** [comment]
Went through the open PRs. Only #731 had additional conflicts when compared against merging with the current `master`, and it only had 1, related to changed imports. Of course, a few additional imports would have to be updated from `loot-design` to relative paths for that PR too.

**Comment by MatissJanis** [comment]
Ok, lets go ahead with this then :+1:

**Pull request merged**
