### PR TITLE
test: bare-bones e2e testing with playwright

### PR DESCRIPTION
**Pull request by MatissJanis**
E2E testing solution using [playwright](https://playwright.dev/)

This PR features mostly the addition of the e2e testing framework and one example test (more to come after merging this PR).

Additionally, I added a "create test file" button to the configuration page (very first page new customers see). This button will only be visible in DEV and PREVIEW environments. By having it there we reduce the amount of clicks required to set-up a test budget file. Thus it saves time for the e2e test runner.

Problems:
- [x] open PRs that are getting updated with more changes: the e2e CI job starts immediately; it does not wait for Netlify deployment to finish. This problem does not exist for new PRs - fixed via a [workaround](https://github.com/JakePartusch/wait-for-netlify-action/issues/6#issuecomment-667644956)

Missing:
- [x] Documentation
- [x] https://github.com/actualbudget/actual/pull/417 needs to be merged before this PR

### CODE REVIEW

**Comment by MatissJanis** [comment]
Depends on: https://github.com/actualbudget/actual/pull/417

**Comment by jlongster** [comment]
Nice! I love playwright. Just a suggestion (leaving my thoughts around on things I see!): I think most things can be tested with react-testing-library and jsdom. See the transaction table tests. We definitely need some e2e tests though, but they are a lot slower and more fickle. If you find yourself writing a lot of tests for component logic it's worth doing those through react-testing-library which has a good API for working with user events and such.

I really do love playwright though. You can test a lot of tricky things with it that don't work in jsdom.

**Comment by MatissJanis** [comment]
While I do agree with the sentiment of the hourglass testing methodology, we also need to be mindful of the context: the current state of Actual. Let me walk you through my thought process:

**What's currently the biggest bottleneck in Actual?**

Lack of initiative to groom all the community PRs which results in low community spirit.

**What can we do to fix this?**

Start grooming and merging peoples work.

**What are the risks of doing so?**

Things might break. Quality might decrease.

**What can we do to solve this in the short-term?**

Quality - improve the tooling so most issues would be caught by automatic linters/formatters or other tools.

Reliability - increase the test coverage. Provide QA tooling.

**How do we quickly raise the test coverage?**

By creating high-level e2e test that cover broad areas. Whilst they're not the perfect solution and should not be used as the go-to solution in the long term (integration tests should be preferred), they are a quick way to drastically raise the coverage and thus make the product more reliable.

**Comment by jlongster** [comment]
We don't disagree :) I'm just encouraging you to also invest in react-testing-library tests. This integration is definitely an improvement, but it'll only provide basic coverage of the main flows. It's a lot easier and faster to write integration tests so after you get some e2e tests, it's my opinion that there will more payoff from integration tests.

**Comment by MatissJanis** [comment]
Ready for review.

If approved I'll work on adding more e2e tests (in a separate PR) for the most customer-critical workflows. That should give us some more peace of mind when working through the PR backlog and future PRs.

**Review by trevdor — APPROVED** [review]
Sweet! This covers so many valuable core use cases right out of the gate.

**Pull request merged**
