### PR TITLE
[Feature] CAMT.053 import (new version)

### PR DESCRIPTION
**Pull request by bfritscher**
This PR introduces add the ability to import CAMT.053 based XML files into Actual.
This should solve the camt part of #513 
It replaces PR #740 which seems abandoned.

The xml2js parser is used, as it is already utliszed by the ofx parser.

As it only looks for Ntry attributes it also works for variation like CAMT.052 and CAMT.054.

The code changes include:
- XML extension has been added to the File upload buttons
- ImportTransactions Dialog has been adapted to only show reconciliation checkbox for CAMT file type
- A new parser has been added, with a test file.

Test file: "packages/loot-core/src/mocks/files/camt/camt.053.xml"
image

### CODE REVIEW

**Comment by youngcw** [comment]
Do you have an example file you could post here?

**Comment by bfritscher** [comment]
Here another one which also works https://bankrec.westpac.com.au/docs/downloads/camt053/camt053-npp-sample-file.xml

image

**Review by youngcw — APPROVED** [review]
Thanks

**Comment by hertg** [comment]
I stumbled on this PR via search engine, after thinking that the exports of my bank are not supported. Could you update the docs to mention this format? 

https://github.com/actualbudget/docs/blob/master/docs/transactions/importing.md

I would do it myself, but I don't know anything about those formats and how I'd have to phrase it :) Thank you so much for implementing this!

**Pull request merged**
