### PR TITLE
Add a warning when SharedArrayBuffer is not available

### PR DESCRIPTION
**Pull request by j-f1**
This message could definitely use some improvement (maybe by linking to a doc with instructions to fix?). I considered hooking it up as an in-app notification, but I wasn’t sure if that would show up at the right time, and this feels severe enough to demand immediate action before continuing to use the app.

### CODE REVIEW

**Comment by MatissJanis** [comment]
This is pretty intrusive. What if we added a always-visible top warning bar? Sort of like this:

demo

Plus: I think we should also disable creating 2x files if this issue occurs (and we might expand the same logic with more edge cases as we discover them).

**Comment by jlongster** [comment]
I've seen a couple threads about the problems with shared budget files, and personally this PR is the right move. This _should_ be intrusive. The app just doesn't work if absurd-sql can't use `SharedArrayBuffer`.

A minor improvement could be to show a message in the app instead of an alert. I'd simply make the app just not load at all, and instead show a message like "This app is missing the correct headers to work." Possibly show instructions for what headers it needs and how to configure it, and maybe link to a docs page explaining why it needs it (I could help write that)

**Comment by jlongster** [comment]
(I believe there's already a codepath for showing a critical error when the app fails to load or something)

**Comment by j-f1** [comment]
Update:

Screenshot_2023-02-02 10 36 20

**Comment by j-f1** [comment]
Link works, merging

**Pull request merged**
