### PR TITLE
Fixes #3585 - Fixes Rule Conditions Removal

### LINKED ISSUE #3585: [Bug]: Rule Conditions Removal
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When removing conditions of a rule, it removes the last condition in the list, not the condition selected.

Steps;
Edit Rule
Select '-' for condition to remove

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by attyluccio**
Fixes the issue #3585 

actually the removal worked correctly behind the scenes but was not rendered properly because the inputs did not have valid keys but the array index was used.

I fixed it by generating uuidv4s (instead of the previous Math.random() of the other inputs) and using them as the key

### CODE REVIEW

**Review by MatissJanis — CHANGES_REQUESTED** [review]
Seems to be still broken for me unfortunately


https://github.com/user-attachments/assets/d9291159-0c39-4b33-8059-4d033e8d4a9a

**Comment by attyluccio** [comment]
https://github.com/user-attachments/assets/5fc432e6-86c7-40fd-885b-c8bad5c1015f

maybe I'm missing something but seems ok here... I'll recheck the code as soon as possible

**Comment by attyluccio** [comment]
i found the bug... it was only on already saved rules... it should be fixed now.

**Review by MatissJanis — APPROVED** [review]
Thanks!

**Pull request merged**
