### PR TITLE
Reapply rules to split transactions when the parent changes

### PR DESCRIPTION
**Pull request by jfdoming**
Concretely, this enables the "standard" workflow for split-transaction-entry on desktop, where you enter the payee first, and then edit the amount afterwards (and expect splits in a rule to apply when you edit the amount).

After adding payee:
image

After updating the amount:
image

Note that this doesn't affect transaction _editing_ within the transaction table, since rules are intentionally _not_ run there.

### CODE REVIEW

**Comment by youngcw** [comment]
One issue Im seeing is:
1. Fill in parent info, tab along and it splits the transaction
2. fill in parent amount
3. press enter
4. see that the first split doesn't update.

It works if you press anything other than enter (at least that Ive tried)

**Comment by psybers** [comment]
If you enter in a payee that has a split rule, it shows the splits.  Should it remove the splits if you shift-tab back and change the payee to a different payee (that has no split rules)?

**Comment by jfdoming** [comment]
> One issue Im seeing is:
> 
> 1. Fill in parent info, tab along and it splits the transaction
> 2. fill in parent amount
> 3. press enter
> 4. see that the first split doesn't update.
> 
> It works if you press anything other than enter (at least that Ive tried)

Thanks for the feedback! Sorry for the delay, this one was pretty tricky to trace 😅 give it another go?

Also quick note, had to update the vrt. Seems like with this change, a different row was left highlighted at the end of the test. Since the highlight is just due to where focus ended up, I think this is not an actual regression. (See below).

Old vrt:
image

New vrt:
image

**Comment by jfdoming** [comment]
> If you enter in a payee that has a split rule, it shows the splits. Should it remove the splits if you shift-tab back and change the payee to a different payee (that has no split rules)?

Hmm, it's an interesting thought. I think it would be difficult to implement right now, since we don't maintain any notion of "dirty" state w.r.t rules (would require pushing down a bunch of extra info). Also, right now with "normal" rules, we don't have this behaviour (e.g., if you have a rule that applies a category to a certain payee, that category stays even if you then change the payee), so I'm inclined to keep as is? But feel free to push back if you think this should be the general behaviour (maybe we should open a feature request for that?).

**Comment by youngcw** [comment]
Nice.  That seems to be working well now.

**Comment by youngcw** [comment]
Can you run the vrt again?  It's strange that only one theme version had a change and not all three theme versions

**Review by psybers — APPROVED** [review]
LGTM (other than the VRT thing already pointed out).

**Comment by jfdoming** [comment]
> Can you run the vrt again? It's strange that only one theme version had a change and not all three theme versions

You're right, that is strange... let me dig a little bit

**Comment by jfdoming** [comment]
> Can you run the vrt again? It's strange that only one theme version had a change and not all three theme versions

Hmm, so it seems to be a timing-related thing. When you add a transaction the modal with Add/Cancel stays open, and resizes itself after the transaction gets added. I _think_ what's happening is the resize only completes after the first two screenshots, hence why the last one (midnight theme) has a different hover. Presumably this occurred only now because the code I added causes React to do an extra render? But I'm finding this quite hard to repro; the only way I was able to affect this behaviour at all was by adding an extra screenshot call _before_ the theme screenshots (then the extra screenshot contains the incorrect hover instead)

Any ideas on what might be going on? Since the change consistently repros we could also leave it as is, defer to you

**Comment by youngcw** [comment]
@jfdoming can you merge master?  I think we are ready after that

**Comment by jfdoming** [comment]
@youngcw should be good to go!

**Review by youngcw — APPROVED** [review]

**Pull request merged**
