### PR TITLE
 Bugfix:Midnight theme button contrast

### LINKED ISSUE #2488: [Bug]:  [Theme - Midnight] - Improve contrast in Payee autocomplete's "Create payee" and Category autocomplete's "Split transaction" buttons
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### Is this related to GoCardless, Simplefin or another bank-sync provider?

- [ ] I have checked my server logs and could not see any errors there
- [ ] I will be attaching my server logs to this issue
- [ ] I will be attaching my client-side (browser) logs to this issue
- [ ] I understand that this issue will be automatically closed if insufficient information is provided

### What happened?

Payee autocomplete's "Create Payee" button
image

Category autocomplete's "Split Transaction" button
image

### What error did you receive?

_No response_

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by Jenna59**
Closes #2488

### CODE REVIEW

**Comment by joel-jeremy** [comment]
I think when adding a new entry to a theme, you will need to add the same to the other themes (list, dark, development) and define what should be the colors for those themes as well.

**Comment by Jenna59** [comment]
@joel-jeremy Hi Joel! Do you know anything about how to get the E2E/VRT test to pass? I don't know much about that kind of test, just that a screenshot comparison is failing.

**Comment by psybers** [comment]
> @joel-jeremy Hi Joel! Do you know anything about how to get the E2E/VRT test to pass? I don't know much about that kind of test, just that a screenshot comparison is failing.

@Jenna59 I recall someone else had to update screenshots. There were some instructions posted in #2419.

**Comment by youngcw** [comment]
Anyone can update the vrt tests. The instructions are in the readme for the desktop-client package.

**Comment by shall0pass** [comment]
When I look at the 'Light' theme, I'm seeing this:

image

Dark and Midnight theme looks good.

**Review by joel-jeremy — APPROVED** [review]
LGTM :)

**Pull request merged**
