### PR TITLE
fix: Margin when editing account on desktop

### LINKED ISSUE #1606: [Bug]: Components overlap when editing account name
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When editing an account's name, the components are overlapping:
image

### What error did you receive?

_No response_

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by dhruvramdev**
Fixes #1606

### CODE REVIEW

**Comment by joel-jeremy** [comment]
Thank you for create a PR! Can we adjust margin/padding so that the hover also doesn't overlap?
image

**Comment by joel-jeremy** [comment]
The visual regression tests are failing. Can you run the VRT update snapshots? Please see here: https://github.com/actualbudget/actual/tree/master/packages/desktop-client#visual-regression

**Comment by dhruvramdev** [comment]
@joel-jeremy Can you confirm if it looks correct?

**Comment by youngcw** [comment]
@dhruvramdev Can you get the merge conflicts taken care of?  Looks good otherwise

**Comment by dhruvramdev** [comment]
Fixed the VRT and merge conflicts

**Review by youngcw — APPROVED** [review]

**Comment by joel-jeremy** [comment]
I see that we will be giving up a bit of transactions table real estate for this. I'm fine with it but we could also consider just making the active style padding of the account name input and the account balance hover padding smaller.

**Comment by youngcw** [comment]
> I see that we will be giving up a bit of transactions table real estate for this. I'm fine with it but we could also consider just making the active style padding of the account name input and the account balance hover padding smaller.

I agree that it would be nice to not lose the screen real estate if possible.  @dhruvramdev Would you be willing to look into @joel-jeremy recommendation?

**Comment by dhruvramdev** [comment]
Trimmed the components as per suggestion. Let me know if it's too much.

**Comment by youngcw** [comment]
I like that better.  Thanks for that.  Ill let @joel-jeremy confirm that all is alright.

**Review by joel-jeremy — APPROVED** [review]
Looks much better! Thank you!

**Pull request merged**
