### PR TITLE
Minimal typescript migration

### PR DESCRIPTION
**Pull request by TomAFrench**
This PR performs an MVP migration of `loot-core` over to typescript:

- A TS compatible linter has been set up.
- `ts-loader` has been added to the webpack config so that it can load TS files
- The entrypoint file `main.js` has been replaced by `main.ts`.
- The minimum possible changes have been made to the source files to fix the resultant TS errors and allow the `loot-core` package to build.

This allows us to gradually migrate the rest of the package over to typescript without having to do everything at once (causing huge merge conflicts with the other PRs). Considering how widely `loot-core` is used across the other packages, I think it makes sense to migrate this package first and once it has a well defined interface then we can migrate the other packages over to TS.

One odd thing I've noticed is that we've set the context for the `loot-core` package to be the monorepo root which seems to cause a need for `ts-loader` to be installed up there (or at the very least hoisted). I haven't looked into whether this is necessary or if we can remove this.

### CODE REVIEW

**Comment by TomAFrench** [comment]
Converting to draft as this currently blows up running tests in loot-core as `babel-jest` can't handle TS. The plan is to rebase this on top of https://github.com/TomAFrench/actual/commit/28056eae687850e2b44fa3248bb16784005acd3a down the line once that's in master.

**Comment by jcdickinson** [comment]
Have you considered renaming everything to `.ts` (with `git mv` for full merge fidelity)? TS is a strict superset of JS, so every file in this repo is already valid TS.

**Comment by TomAFrench** [comment]
Doing that would destroy information on which files have had a meaningful migration over to typescript. We'd also be requiring those other files to pass the type checks which they likely would fail (`main.ts` failed a number of checks which required me to modify several other files).

It'd also add a ton of noise to the PR so if we were to do that I'd prefer to do it as a separate PR, my preference though is to migrate to `.ts` directory by directory as we add strict types to those files.

**Comment by MatissJanis** [comment]
Closing this PR as stale. Someone else can pick up the work started here and continue it in a new PR.

https://github.com/actualbudget/actual/issues/577

**Pull request closed without merging**
