### PR TITLE
add goal tooltip to balance in budget table

### PR DESCRIPTION
**Pull request by matt-fidd**
I saw a suggestion along these lines in the discord some time ago (can't pinpoint exactly but somewhere around the 2 month mark probably)

What do people think? I've gone through a good few designs so if anyone has any suggestions I'm more than open to them!

To test you'll need to enable goal templates, apply them, and hover over the balance in the final column of the budget table. I'm not sure if this would want a dashed underline to make it more obvious or if it's best left discovered organically to keep the table clearer.

image

### CODE REVIEW

**Comment by youngcw** [comment]
For now I think that the goal coloring should be enough indication that there may be more info hiding there.  If we need more indication in the future we could add something.

**Comment by youngcw** [comment]
I like this for now.  Its clean and gets the point across.  More flash could be added later with progress bars or mini charts  Have you peaked at my PR for a new type of template?  I imagine it would be easy to update this to include those changes.

**Comment by matt-fidd** [comment]
> I like this for now. Its clean and gets the point across. More flash could be added later with progress bars or mini charts Have you peaked at my PR for a new type of template? I imagine it would be easy to update this to include those changes.

I saw it come in, but I've not had a chance to properly comb through the code for a review. Functionally it all seems to work as expected. Looking at it, it shouldn't be difficult at all to support it in this tooltip.

I'd quite like this in for the release if possible, I'm not sure what the rules on mergefreeze are though. As your goal template change is in the milestone, if we can have it approved and merged I'd be happy to update the tooltip quickly to have it in if there's any chance?

**Comment by matt-fidd** [comment]
Had a look through and rebased this branch locally on top of your change, looks like it would just work as is (once the merge conflicts are cleared up).

I'd add this as an extra bit in the tooltip though:
```diff
+              <GoalTooltipRow>
+                <div>Goal Type:</div>
+                <div>{longGoalValue === 1 ? 'Long' : 'Template'}</div>
+              </GoalTooltipRow>
```

**Comment by matt-fidd** [comment]
@youngcw I've rebased this to bring in your goal changes and add a goal type to the tooltip

**Comment by youngcw** [comment]
Your underfunded calculation seems to be wrong for long goals.  Would it make more sense to to have a remaining line instead of a budgeted line in the tooltip?

**Comment by matt-fidd** [comment]
Good spot, it was correct testing over just one month.

image
image

I've kept the tooltip as it was, but fixed the calculations for long goals. I've also tweaked the wording from 'budgeted' to 'balance', although I think budgeted would probably convey the right meaning either way.

**Comment by youngcw** [comment]
Ok, Thats fine.

**Review by youngcw — APPROVED** [review]

**Pull request merged**
