### PR TITLE
Fallback to memo in ofx if payee is not found

### PR DESCRIPTION
**Pull request by Shazib**
Solves #767 

In my side quest to replace node-libofx i've come across a number of ofx files that use 'memo' in place of 'name' for the payee information, mostly outside of europe/US. 

This implementation falls back to memo if payee is blank (for all transactions)

~~Maybe we should use a fixed choice per sheet, at the moment it decides _per_ transaction.~~ I thought about adding an option in settings for users to enable 'use memo instead of name' but I think thats not ideal for non technical users. The other option is that we allow the re-mapping of the fields in the GUI at import time?

### CODE REVIEW

**Comment by j-f1** [comment]
This seems like a reasonable approach — maybe try checking if all of the payees are blank first, and then we can switch to a per-transaction algorithm if people continue to report issues?

**Comment by j-f1** [comment]
I was about to follow that up with “I can’t imagine a bank would provide a response that mixes the two” but then again clearly I lack the imagination of bank OFX export devs ;)

**Comment by Shazib** [comment]
Ran out of time today will sort this tomorrow, and add an additional test file that actually uses 'memo' for payees.

**Comment by Shazib** [comment]
The import seems to work ok on the netlify build so i'm not 100% sure why its upset, maybe somewhere is passing blank instead of null

**Review by j-f1 — APPROVED** [review]

**Comment by themadman0980** [comment]
Would it possibly be wiser to leave the Memo field as notes and allow users to set a payee based on rules (as has worked previously)? 

I guess the alternative is to have a toggle to allow using the memo field as payee (without enforcing it for all users)? This aligns with feature request #521.

**Comment by Shazib** [comment]
Is this feature causing issues for you? It only does anything when payee doesn't exist as all iirc - is there a scenario where a bank is exporting transactions with notes(memo) but no payee?

**Comment by themadman0980** [comment]
Correct, see #1524 for details.

**Pull request merged**
