### PR TITLE
Split payee on mobile

### PR DESCRIPTION
**Pull request by joel-jeremy**

### CODE REVIEW

**Comment by Teprifer** [comment]
Unfortunately this doesn't flow well in mobile as it turns splits in to mystery transactions.

Edge:
image

This PR:
image

In hindsight this is the same as the recent change desktop's collapsed split:
image

I don't think turning transactions in to mysteries is a good thing, is there some way to show the first payee(or payee with the  largest share) of the split as a default?

Some mock ups - excuse my MS Paint skills.

image

My preference would be the last one, the count would only show if there were more than 1 unique payees as it'd be redundant to have a count where the payee is the same but the category differs. This would also be an enhancement over the current state. Similar could be done for desktop collapsed.

**Comment by joel-jeremy** [comment]
I like that idea. We could possibly implement that in desktop too if a split transaction is  collapsed.

**Comment by youngcw** [comment]
I like @Teprifer 's first and last mockups.

**Comment by psybers** [comment]
Just curious, but if there is a 'Split' (and icon) right below, do we need to say 'split' twice?

**Comment by jfdoming** [comment]
> Just curious, but if there is a 'Split' (and icon) right below, do we need to say 'split' twice?

I agree, maybe one idea is moving the "split" icon up to the payee, as it is on desktop, instead, but removing the "Split" text so it's similar to what I proposed [here](https://github.com/actualbudget/actual/pull/3049)?
image

**Comment by matt-fidd** [comment]
@joel-jeremy is this ready for review?

**Pull request closed without merging**
