### PR TITLE
[Bugfix] Goals: Database entry

### PR DESCRIPTION
**Pull request by shall0pass**
There is an error in the database insertion if the entry doesn't initially exist when applying goal templates.

Previously an entry like this: 
image

would be created.  With this change, an entry like this: 
image

will be created.  The issue I was seeing was that the color coded goal templates were not always rendering color, and in the process of tracking the issue down discovered this as the root issue.

### CODE REVIEW

**Comment by youngcw** [comment]
> the entry doesn't initially exist

Do you mean like the category month entry doesn't exist?

**Comment by youngcw** [comment]
also, is there a process to recreate the issue?

**Comment by shall0pass** [comment]
> > the entry doesn't initially exist
> 
> Do you mean like the category month entry doesn't exist?

Yes.  The database entry for the category for a given month doesn't exist until you make a budget or transaction against it.  So if the first thing you do for a category in a new month is run the templates, the database entry has to be created because it didn't exist.

**Review by youngcw — APPROVED** [review]

**Comment by shall0pass** [comment]
> also, is there a process to recreate the issue?

I can put up a test budget here shortly.  All I had to do to see the issue is to run the templates in a future month.  To see the colors not turn, use priorities and make sure the To Budget is underfunded.

**Pull request merged**
