### PR TITLE
Mobile payees and rules pages

### PR DESCRIPTION
**Pull request by joel-jeremy**

### CODE REVIEW

**Comment by youngcw** [comment]
This will be great.

Probably for a different PR, but the formatting on the rules page needs some fixing for the small size.

**Comment by joel-jeremy** [comment]
I have made a change to make the link schedule rule to wrap the schedule data on smaller screens

**Comment by joel-jeremy** [comment]
Oh I see. I think that is for displaying the `pre` or `post` stages. But yeah, a rules page specifically catered for mobile devices would be great but that should be done in a different PR.

**Comment by carkom** [comment]
What do you think of copying the "+" from accounts page format for the rules page? Currently with 3 rules, the "create new rule" button is behind the main menu and there's no ability to scroll down so that the menu auto hides. This makes the new rules button inaccessible in my current circumstance.

**Comment by youngcw** [comment]
The new rule button seems to be covered by the footer in a lot of situations.

Thats the only big issue Im seeing.

**Comment by MatissJanis** [comment]
👋 The rules & payees views are pretty hard to use on mobile. 

Rules:

https://github.com/actualbudget/actual/assets/886567/6d8e6116-ca18-4b4d-95f8-ee75b80c1e0c

- [ ] "add rule" button is basically unclickable because of the footer
- [ ] rules modal style for some elements is broken
- [ ] on smaller screens the rules modal will be comletely broken (there is no `minHeight` for the content of the modal)
- [ ] the footer keeps scrolling up&down when I scroll inside the modal
- [ ] the autocomplete component used in rules modal doesn't really work on mobile; plus it's tiny

Payees:
- [ ] same problem as rules - the footer overlays the last items in the list making them unusable
- [ ] same problem as rules - modal content does not have `minHeight`
- [ ] same problem as rules - autocomplete

**Pull request closed without merging**
