### PR TITLE
Fix some YNAB4 importer bugs

### PR DESCRIPTION
**Pull request by rianmcguire**
I ran into a few minor issues while importing my YNAB4 data. With these fixes, I'm able to import my 9-year-old YNAB4 budget and have no discrepancies in the budget balances.

I suggest reviewing commit-by-commit.

### CODE REVIEW

**Comment by MatissJanis** [comment]
Hey!

Thanks for your contribution. Would be mind sharing a sample YNAB4 export so we could test this change?

Thanks again

**Comment by biohzrddd** [comment]
> With these fixes, I'm able to import my 9-year-old YNAB4 budget and have no discrepancies in the budget balances.

In YNAB4 did you ever use Income: [this month] and Income: [next month]? This affects my to-be-budgeted amounts after importing and I'm wondering if these changes fix that.

**Comment by biohzrddd** [comment]
Below is a YNAB4 file that breaks upon import to Actual. The budget starts 1 October 2022 and has income and expenses Oct, Nov, and Dec. 

For October, Actual shows 0.00 in Available Funds when there is (500 + 500 + 501 + 900 + 901) income available that month.

[Test Budget for Export to Actual 2022~36098EE4.ynab4.zip](https://github.com/actualbudget/actual/files/10254331/Test.Budget.for.Export.to.Actual.2022.36098EE4.ynab4.zip)

YNAB4 Budget values for the above Test Budget

Actual upon importing Test Budget

Comparison of Actual and YNAB4 accounts

**Comment by MatissJanis** [comment]
👋 Sorry for taking so long to properly review this. We're currently working on the next release, so am quite busy with that, but I'll try to get on this straight after getting the release out.

**Review by MatissJanis — APPROVED** [review]
👋 Finally got to reviewing this. Looks good on my end. Did not spot any bugs.

Thanks for your contribution and sorry again for taking so long!

**Comment by biohzrddd** [comment]
Thanks for the work merging @MatissJanis ! I tried importing my test file from #399 and confirmed the cleared status now imports. 

However, the budgeted values still do not. Shall I raise another bug for that? The below image is using https://deploy-preview-88--actualbudget.netlify.app/budget and the same result for https://deploy-preview-490--actualbudget.netlify.app/budget

image

**Comment by MatissJanis** [comment]
@shall0pass would you mind moving the conversation to #490 ?

**Pull request merged**
