### PR TITLE
Add Modal2 backdrop

### PR DESCRIPTION
**Pull request by joel-jeremy**
Resolves https://github.com/actualbudget/actual/issues/3145

### CODE REVIEW

**Comment by MatissJanis** [comment]
I think the `accounts` VRT tests need to be updated. I'm actually surprised they aren't breaking in CI in this PR 🤔

**Comment by joel-jeremy** [comment]
> I think the `accounts` VRT tests need to be updated. I'm actually surprised they aren't breaking in CI in this PR 🤔

That's true. Maybe it only detects shifts in pixel position but not blur/brightness changes? Not sure.

**Comment by MatissJanis** [comment]
Would you mind updating the screnshots? Other than that LGTM!

**Comment by joel-jeremy** [comment]
@MatissJanis Turns out playwright cannot detect the difference when blurred by < 1px

**Review by MatissJanis — APPROVED** [review]

**Pull request merged**
