### PR TITLE
Mobile: Refresh button for linked accounts

### PR DESCRIPTION
**Pull request by benjylxwang**
Added a refresh button in the mobile view for running the sync (to gocardless) and download function

### CODE REVIEW

**Comment by benjylxwang** [comment]
Oh I just saw #1663 which does a very similar thing and clashes horribly with this :D
Is there any appetite for having the button as well? I can fix the merge after #1663 goes in and put this up again

**Comment by MatissJanis** [comment]
👋 Thanks for the contribution! Very exciting to see new folks contribute to Actual!

I think given we just added pull-down-to refresh functionality for this (in #1663), then the button would not be necessary anymore.

What do you think @trevdor ?

**Comment by trevdor** [comment]
Agreed—we definitely need the functionality, @benjylxwang, and appreciate you working on it.  But I don’t see a need for a button now that pull-to-refresh handles import refresh.

Have we missed anything about your goal for this PR?

**Comment by benjylxwang** [comment]
Nope was just adding the button. I'll close it in that case!

**Pull request closed without merging**
