### PR TITLE
[Bugfix]: Dark mode - darker tint for pageTextLink

### PR DESCRIPTION
**Pull request by Evomatic**
This fixes an issue for Actual Dark mode, where page text links in settings is too difficult to read: https://github.com/actualbudget/actual/issues/1760

Before: 
image

After:
image

### CODE REVIEW

**Comment by MatissJanis** [comment]
👋 The contract between the link and the background still seems.. a bit off. What if we instead changed the background color of the block to the one used in budget page? The purple looks good there.

Screenshot 2023-10-09 at 18 51 17

**Comment by Evomatic** [comment]
Hi @MatissJanis - Thank you for your feedback! You're right, the contrast did appear to be off still, especially after comparing it to your suggested change. 

Looks better I think.
image

**Review by MatissJanis — APPROVED** [review]
Perfect! Really like this change.

cc @carkom any objections from you here?

**Comment by Evomatic** [comment]
Hi @carkom,

I see what you mean, thanks for the feedback!

If I am understanding correctly, Themes [light.ts](https://github.com/actualbudget/actual/blob/master/packages/desktop-client/src/style/themes/light.ts) and [dark.ts](https://github.com/actualbudget/actual/blob/master/packages/desktop-client/src/style/themes/dark.ts) are set globally with [useTheme](https://github.com/actualbudget/actual/blob/cae2b9cd5ad8014b15f168e095bb5317731a708b/packages/desktop-client/src/style/theme.tsx#L18C1-L18C1). For links it looks like there is a [ExternalLink](https://github.com/actualbudget/actual/blob/master/packages/desktop-client/src/components/common/ExternalLink.tsx) component that has prop `externalLinkColors` which allows us to choose a color based on the `externalLinkColors` object. (where theme colors are fed depending on which theme is active). 

One idea I have would be to create a new color variable for the dark theme that is specific to the settings page. Something like `settingsPageTextLink`. Then in the `externalLinkColors` object, add a new purple property that uses the new color variable. Then color can be changed for settings without inadvertently changing it everywhere else.

I am not sure if this is the best approach for what you might have in mind, but does seem viable. 🤔

**Comment by carkom** [comment]
Hi @Evomatic, yep that's how it works!

The idea is to create consistency across the app so re-using color compenents is highest priority. The goal is to have as few colors as possible in "light" and "dark" components. By adding specific colors just for one page we would be increasing complexity and number of unique colors. Imagine if we did this for every page that has a linkcolor. We'd end up with 8+ link color options, this is opposite of what we are trying to accomplish.

The preferred implementation is to create consistency where linkcolor is being used. If it has a darker background on a different page then we might consider unifying those elements and making them the same. This comes with a larger amount of work up front beacuse you have to track down every place each color is being used and making sure it isn't creating any visual regressions. The bennifit, however, is that it makes the themes much simpler for future development.

I'd be happy to have help with dark theme PRs if you are wanting to contribute. Join in on the discord channel "project-dark-mode" and we can chat about how we can partner on this.

**Comment by carkom** [comment]
@MatissJanis, I'd prefer to not merge this change as it current is since it will create more work on the whole for dark theme project. I'll discuss with Evo how we can adjust it to help move dark theme forward.

**Comment by carkom** [comment]
@Evomatic, rather than change the colors file, which changes many other pages across the app that are using that same color. There's an easier fix for this, that is already build into the theme code. Change your external link color - just add linkColor="purple" to all the links that need better contrast. Also note that it will change the linkColors in the light version as well.

`
          <ExternalLink 
            to="https://actualbudget.org/docs/releases"
            linkColor="purple"
          >
            Release Notes
          </ExternalLink>`

**Comment by Evomatic** [comment]
> Hi @Evomatic, yep that's how it works!
> 
> The idea is to create consistency across the app so re-using color compenents is highest priority. The goal is to have as few colors as possible in "light" and "dark" components. By adding specific colors just for one page we would be increasing complexity and number of unique colors. Imagine if we did this for every page that has a linkcolor. We'd end up with 8+ link color options, this is opposite of what we are trying to accomplish.
> 
> The preferred implementation is to create consistency where linkcolor is being used. If it has a darker background on a different page then we might consider unifying those elements and making them the same. This comes with a larger amount of work up front beacuse you have to track down every place each color is being used and making sure it isn't creating any visual regressions. The bennifit, however, is that it makes the themes much simpler for future development.
> 
> I'd be happy to have help with dark theme PRs if you are wanting to contribute. Join in on the discord channel "project-dark-mode" and we can chat about how we can partner on this.

@carkom Thanks for the explanation, this makes sense. I am happy to help with dark theme PRs and have joined the discord and "project-dark-mode" channel.

**Comment by Evomatic** [comment]
> @Evomatic, rather than change the colors file, which changes many other pages across the app that are using that same color. There's an easier fix for this, that is already build into the theme code. Change your external link color - just add linkColor="purple" to all the links that need better contrast. Also note that it will change the linkColors in the light version as well.
> 
> ` <ExternalLink to="https://actualbudget.org/docs/releases" linkColor="purple" > Release Notes </ExternalLink>`

Adding the `linkColor`  purple to the external links works! The contrast is definitely better than before and is still readable in light mode as well.

image

image

**Comment by rich-howell** [comment]
image

This still fails the accessibility contrast tests in dev tools in edge. 

image

**Comment by carkom** [comment]
If we want to change the pill background color we just need to check everywhere it's used and make sure we are happy with it.

**Comment by carkom** [comment]
The pillbackground is only used 2 other places (altpillbackground is used many others but we can address that on a different PR).
@Evomatic, change the pillbackground back to the lighter color from before in order to create more contrast. Then we can check the look/contrast here as well as settings page and that should cover us so we can close off this PR.
image

**Comment by Evomatic** [comment]
Hi @carkom - I was taking a look at `pillBackground` and I think it is being used in 3 different places, unless I have misunderstood something?

1. [Balance.js](https://github.com/actualbudget/actual/blob/e0b2eab475f6ccf050ca9efc8d63fdfbe9890fdc/packages/desktop-client/src/components/accounts/Balance.js#L28)
2. [FiltersMenu.js](https://github.com/actualbudget/actual/blob/e0b2eab475f6ccf050ca9efc8d63fdfbe9890fdc/packages/desktop-client/src/components/filters/FiltersMenu.js#L506)
3. [UI.tsx](https://github.com/actualbudget/actual/blob/e0b2eab475f6ccf050ca9efc8d63fdfbe9890fdc/packages/desktop-client/src/components/settings/UI.tsx#L22)

>  change the pillbackground back to the lighter color from before in order to create more contrast.

Sorry, do you mean change it back to the original color, `navy600`? If so I did this already. Currently this is what I have in my local.

Dark:
image

image


Light:
image

image

**Comment by carkom** [comment]
Yep you understand correctly. 

Sorry I meant darker. Change it to navy800 like you had it and we can see how those 3 places (balance, filtermenu, UI) look. If we are happy for all of them to change then we can merge it.

**Comment by Evomatic** [comment]
Hi @carkom - I made the change to `navy800`  and here is what we have now

Settings:
image

Accounts & filter menu:
image

**Comment by rich-howell** [comment]
> Hi @carkom - I made the change to `navy800` and here is what we have now
> 
> Settings: image
> 
> Accounts & filter menu: image

So much easier to read now and AA passes AAA still fails though.

**Comment by carkom** [comment]
I'm happy with these colors. All looks good to me.

Do we need to meet AAA in every situation? Or is that just for reference?

**Comment by rich-howell** [comment]
> I'm happy with these colors. All looks good to me.
> 
> Do we need to meet AAA in every situation? Or is that just for reference?

Was just for reference. 

"Level AA includes all Level A and AA requirements. Many organizations strive to meet Level AA."

**Comment by carkom** [comment]
Thanks Rich!

@Evomatic, I think it's all good now. Just fix the VRT by updating screenshots and should be good to go!

**Review by carkom — APPROVED** [review]
LGTM!

**Comment by Evomatic** [comment]
Hi @carkom I updated the VRT screenshots, following the README

**Review by MatissJanis — APPROVED** [review]
Thanks so much! And apologies for the slow review. 😨

**Pull request merged**
