### PR TITLE
:construction_worker:  run feature-request action on labeled action

### PR DESCRIPTION
**Pull request by MatissJanis**
Run the feature request management action when adding "feature" label.

This will allow us to..
1. remove "feature" label
2. add back "feature" label

Thus execute the workflow on the existing issues.

### CODE REVIEW

**Comment by MatissJanis** [comment]
The `labeled` action also applies to newly created issues. So in an essence this github workflow will run in both of these scenarios:
1. a new issue with the label "feature" is created
2. an existing issue gets the "feature" label added

**Review by rich-howell — APPROVED** [review]
LGTM

**Review by j-f1 — APPROVED** [review]
Does this apply when an issue is newly created with labels?

**Comment by MatissJanis** [comment]
> Does this apply when an issue is newly created with labels?

Yes, it does :)

**Pull request merged**
