### PR TITLE
sideBar Dark Color changes

### PR DESCRIPTION
**Pull request by carkom**
Dark Theme sidebar color updates.

Takes place of #1821

### CODE REVIEW

**Comment by carkom** [comment]
@rich-howell , can you do your AA and AAA checks on these?

**Comment by rich-howell** [comment]
> @rich-howell , can you do your AA and AAA checks on these?

For the selected item it now passes :) 

image

**Comment by rich-howell** [comment]
This PR for whatever reason also seems to resolve #1869 

image

**Comment by youngcw** [comment]
I feel like the new sidebar colors don't match the other colors.  The new sidebar looks way more gray than the other blue hue colors.

**Comment by carkom** [comment]
Navy900 give good contrast and keeps with the theme. I like that, what do you think?

image

**Comment by youngcw** [comment]
I like that navy900 option. Is that the same as the light theme?

**Comment by carkom** [comment]
> I like that navy900 option. Is that the same as the light theme?

It is.

**Comment by carkom** [comment]
I agree, I like it better as well. Adds some synergy being the same in both themes.

**Review by youngcw — APPROVED** [review]

**Pull request merged**
