### PR TITLE
Regenerate icons without the .web.js extension

### PR DESCRIPTION
**Pull request by j-f1**
This makes it easier to import since the file name will be correctly completed without the `.web` suffix. However, auto-imports will still add the `Svg` prefix to the component name because there is no way to remove it.

### CODE REVIEW

**Review by MatissJanis — APPROVED** [review]
Thanks! I totally forgot to follow up on the icon cleanup after removing the mobile versions.

**Review by MatissJanis — CHANGES_REQUESTED** [review]
Actually - I'm noticing some issues on netlify. Will post in comments.

**Comment by MatissJanis** [comment]
Screenshot 2023-01-20 at 19 01 03
Screenshot 2023-01-20 at 19 01 59
Screenshot 2023-01-20 at 19 02 27

**Comment by j-f1** [comment]
Thanks for pointing that out! Looks like the sizing got messed up. Switched to `viewBox` which should fix that.

**Review by MatissJanis — APPROVED** [review]

**Pull request merged**
