### PR TITLE
:sparkles: (api) ability to run bank sync via the API

### PR DESCRIPTION
**Pull request by MatissJanis**
Allow running 3rd party (gocardless, simplefin) bank-sync via the API package.

This will allow people to run the bank-sync operation in the background on a schedule (i.e. with cron jobs).

Usage:

```javascript
const api = require('@actual-app/api');

(async () => {
  await api.init({
    // Budget data will be cached locally here, in subdirectories for each file.
    dataDir: '/path/to/budget/file',
    // This is the URL of your running server
    serverURL: 'https://xxxxxxx.fly.dev',
    // This is the password you use to log into the server
    password: 'xxxxxx',
  });

  // This is the ID from Settings → Show advanced settings → Sync ID
  await api.downloadBudget('xxxxxx-xxxx-xxxxx-xxxxx');

  // Run bank sync for a single account
  await api.runBankSync({ accountId: 'xxxxxx-xxxxx-xxx-xxxxx-xxxxxxxx' });

  // Run bank sync for all accounts
  await api.runBankSync();

  await api.shutdown();
})();

```

Docs: https://github.com/actualbudget/docs/pull/350

### CODE REVIEW

**Comment by matt-fidd** [comment]
Unsure if this is user error, but when calling `runBankSync` with no arguments, I'm receiving the below error.

```js
/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:43402
            handlers['accounts-bank-sync'] = async function ({ id }) {
                                                                                             ^

TypeError: Cannot destructure property 'id' of 'undefined' as it is undefined.
    at handlers.accounts-bank-sync (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:43402:64)
    at handlers.api/bank-sync (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:34823:72)
    at runHandler (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:44781:33)
    at Object.send (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:44463:94)
    at send (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/methods.js:31:21)
    at Object.runBankSync (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/methods.js:58:12)
    at /data/home/matt/cron/actual/bankSync.js:25:12

Node.js v18.19.1
```

**Comment by MatissJanis** [comment]
Thanks for testing @matt-fidd ! I must have accidentally removed something when I cleaned up the implementation. 

Should be patched now. Give it another go.

**Comment by matt-fidd** [comment]
Thanks @MatissJanis!

Looks better now!

It doesn't seem to respect when an accountId is passed to it either, if I pass it the ID of a single account it syncs all accounts.

It also appears to hit a problem halfway through my sync where it tries to re sync with the server and falls over.

```
Bank Sync operation for account: ########
  Pulling transactions from GoCardless
  Syncing since 2024-05-01T17:10:28.143Z-0000-b80ed5e91c4802ff 7 (attempt: 0)
  SyncError: SyncError: encrypt-failure
      at Module.encode (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:47024:35)
      at _fullSync (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:47705:77)
      at async /data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:47611:32 {
    reason: 'encrypt-failure',
    meta: { isMissingKey: true }
  }
```

From then on, any API interactions are met with the below error.

```
node bankSync.js
- Connecting
-- Success
- Downloading
Loaded spreadsheet from cache (3136 items)
Syncing since 2024-05-01T17:10:28.143Z-0000-b80ed5e91c4802ff 7 (attempt: 0)
SyncError: SyncError: encrypt-failure
    at Module.encode (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:47024:35)
    at _fullSync (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:47705:77)
    at async /data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:47611:32
    at async initialFullSync (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:47597:32)
    at async handlers.sync-budget (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:43980:32)
    at async handlers.api/download-budget (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:34777:36) {
  reason: 'encrypt-failure',
  meta: { isMissingKey: true }
}
/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:34779
                        throw new Error((0, _shared_errors__WEBPACK_IMPORTED_MODULE_2__.getSyncError)(result.error, localBudget.id));
                              ^

Error: We had an unknown problem opening ?My-Finances-5cca4be?.
    at handlers.api/download-budget (/data/home/matt/cron/actual/node_modules/@actual-app/api/dist/app/bundle.api.js:34779:31)

Node.js v18.19.1
```

and to be able to continue, I have to wipe the cache directory and resync from blank

**Comment by matt-fidd** [comment]
Some debugging later, it appears that the error is thrown [here ](https://github.com/actualbudget/actual/blob/ad73a404c4c1e24e1cacaffb0230dc71ba9c10f5/packages/loot-core/src/server/encryption.ts#L54) as the `keys` object is empty.

With the debug lines below added

```diff
export function getKey(keyId) {
  if (keyId == null || keys[keyId] == null) {
+    console.log(keyId);
+    console.log(keys);
+    console.log(keys[keyId]);
    throw new Error('missing-key');
  }
  return keys[keyId];
}
```

The following is printed (master key has been redacted but it is set!)

```js
Loaded spreadsheet from cache (3136 items)                                                                                                                                                                                                                                  
Syncing since 2024-05-01T21:31:22.845Z-0073-9f76373186bb94dd 13 (attempt: 0) 
                                                                                                                                                                                               
***REDACTED KEY***                                                                                                                                                                                                                                       
{}                                                                                                                                                                                                                                                                          
undefined              
                                                                                                                                                                                                                                                     
SyncError: SyncError: encrypt-failure
...
```

**Comment by MatissJanis** [comment]
Looks like the e2e encryption is having problems there for you. Did you set the encryption password in the code?

https://actualbudget.org/docs/api/#connecting-to-a-remote-server

```
await api.downloadBudget('1cfdbb80-6274-49bf-b0c2-737235a4c81f', {
    password: 'password1',
});
```

**Comment by matt-fidd** [comment]
I did set the encryption password and it manages to connect and sync a couple of accounts, and then it gets caught up somewhere and empties the keys object in /loot-core/src/server/encryption.ts. I've checked and neither the `unloadKey` or `unloadAllKeys` functions have been called.

**Comment by matt-fidd** [comment]
Done some more digging, I can't force it to happen with any other API functions. If I just sync one bank account over and over it also does not happen, only when calling `api.runBankSync();`

**Comment by MatissJanis** [comment]
Thanks for the investigation @matt-fidd . I've split off the patch of this issue into a separate PR: https://github.com/actualbudget/actual/pull/2698

**Comment by matt-fidd** [comment]
Amazing, thank you @MatissJanis!

**Comment by youngcw** [comment]
@MatissJanis Is there much more that needs added here or is the ready for review?

**Comment by MatissJanis** [comment]
@youngcw this Pr depends on #2698. Once that one is merged - I'll open this one back up.

**Comment by MatissJanis** [comment]
Out for review again.

Would appreciate another round of testing from you @matt-fidd ! 🙇

**Comment by matt-fidd** [comment]
All looking good!!

**Review by youngcw — APPROVED** [review]

**Pull request merged**
