### PR TITLE
✨ (dashboards) text widget

### PR DESCRIPTION
**Pull request by MatissJanis**
Depends on https://github.com/actualbudget/actual/pull/3284 and https://github.com/actualbudget/actual/pull/3289

https://github.com/user-attachments/assets/ca3100dd-c2e1-4ec8-a2da-4c7a1e1e63ce

**Open question:** should text widgets have a "name"/"title" as the other widgets? Or perhaps there is NO name and instead the name can be set by updating the content of the widget (thus allowing to remove the name entirely if the user wishes to do that).

### CODE REVIEW

**Comment by MatissJanis** [comment]
Open for review

**Comment by youngcw** [comment]
I think that a text widget shouldn't have a title.

Is there a way to center the text within the box?  Like make a window width card and have a centered heading?

**Comment by MikesGlitch** [comment]
The textarea isn't padded out on the right & bottom sides - it looks a bit off. Moving the mouse to the outside edge causes some flickering of the scrollbars:

test

I'm seeing it on Edge

**Comment by MatissJanis** [comment]
Thanks for the feedback @MikesGlitch ! I had absolutely forgotten to add color theme support to this input box. That is now done.

As for the paddings/margins: my original intention was to mimic the underlaying content as closely as possible (i.e. if the content is plain-text and you click "edit" - the edit box should become available, but the content visually should look exactly the same as before). That was the intention behind the /weird/ paddings.

But now that I thought about it more.. it doesn't really make much sense as people will be using various formatting options. So the content will be skewed either way. 

Added extra bottom & right padding ✅

**Review by MikesGlitch — APPROVED** [review]

**Pull request merged**
