### PR TITLE
[Maintenence] Refactor Goals Schedule file

### PR DESCRIPTION
**Pull request by shall0pass**
This is an attempt to simplify the schedules file by breaking out the logic in separate functions and hopefully squashing a few bugs in the process.  I think this is a little easier to follow than the currently written method of nested if-else logic and will hopefully be easier to debug in the future.  The calculation method remains the same, so hopefully there are no regressions 🤞.  

One possible gotcha is the way the schedule templates are now filtered.  It is possible that a schedule could end up in both the sinkingFund and full template arrays.  I haven't seen it happen in any of the iterations I've tried so far but I may have missed a situation.

Believed to fixed:
1. When placing a non-repeating schedule into the future, the schedule template would not budget.
2. Monthly recurring schedules would sometimes have non-expected values.

@jfdoming You added startDate and started variables in #1899. I removed them because it was causing issue 1 above.  Is there a schedule condition I need to check that I'm overlooking?  It's simply commented for now so it's easy to turn back on.

This is an attempt at a flow chart for all of the logic happening in this file. 
mermaid-1702930808136

### CODE REVIEW

**Comment by youngcw** [comment]
I think this is overwriting previous templates budgeted value.

**Comment by youngcw** [comment]
That overwrite issue is fixed now.  I still need to go through and make sure the chart and code make sense

**Review by youngcw — DISMISSED** [review]

**Comment by jfdoming** [comment]
@shall0pass thanks for looking! I think I added those variables to fix a different calculation issue I found, but maybe I misunderstood how things were supposed to work. I'm on vacation right now so I don't have my computer but I'll take a look tomorrow and let you know if I noticed anything weird

**Comment by shall0pass** [comment]
Remerged master and made sure #2125 was applied.

**Review by jfdoming — APPROVED** [review]
I wasn't able to find/reproduce the original issue I found, so feel free to merge this as is. I'll open an issue in the repo if I can reproduce it.

**Comment by Kidglove57** [comment]
Sorry I did not respond to your original review request @shall0pass. I don’t think my GitHub notifications are set right! Will look later - however I am seeing the same issues on current release as was reported in GitHub

**Comment by shall0pass** [comment]
> Sorry I did not respond to your original review request @shall0pass. I don’t think my GitHub notifications are set right! Will look later - however I am seeing the same issues on current release as was reported in GitHub

You're seeing the issue on 24.1.0 or you're seeing the issue in this PR?  Nothing was merged for 24.1.0 around that issue, so it should still be unresolved.

**Comment by Kidglove57** [comment]
> > Sorry I did not respond to your original review request @shall0pass. I don’t think my GitHub notifications are set right! Will look later - however I am seeing the same issues on current release as was reported in GitHub
> 
> You're seeing the issue on 24.1.0 or you're seeing the issue in this PR? Nothing was merged for 24.1.0 around that issue, so it should still be unresolved.

Understood - I have now been able to test my own file in this PR. It now fills the budget  as it should for a single line annual "#template schedule x" but gives me an odd number (too low) where I have a series of  annual "template schedule ..." listed in the same category.

**Review by youngcw — APPROVED** [review]

**Pull request merged**
