### PR TITLE
Fix React Aria Button hover styles 

### LINKED ISSUE #3447: [Bug]: Focus/hover in select component not working on edge
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

## Steps to reproduce
1. Visit https://edge.actualbudget.org.
2. Open the Rules page and create a new rule.
3. Hover/click on the "Payee" button—the hover effect flickers and then disappears

## Expected behaviour
On https://demo.actualbudget.org, the effect displays on focus and doesn't disappear.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by joel-jeremy**
Resolves #3447 

Preferring to use className instead of the inline style syntax to allow for easier CSS library migration in the future

### CODE REVIEW

**Review by matt-fidd — COMMENTED** [review]
I've double checked as best I can but this doesn't seem to replicate the behaviour in demo (which is a little odd anyway IMO)

Just going off the report in #3447 I was testing the payee selector in the rules creation modal

On edge: as described in the bug
On demo: no hover effect, grayed out background on click that does not persist
In this change: hover effect changes text colour to black, but click effect isn't there

Can send videos if you can't reproduce but I've cleared cache etc so it should be the same for everyone

**Comment by MikesGlitch** [comment]
@coderabbitai full review

**Comment by jfdoming** [comment]
> > I've double checked as best I can but this doesn't seem to replicate the behaviour in demo (which is a little odd anyway IMO)
> > Just going off the report in #3447 I was testing the payee selector in the rules creation modal
> > On edge: as described in the bug On demo: no hover effect, grayed out background on click that does not persist In this change: hover effect changes text colour to black, but click effect isn't there
> > Can send videos if you can't reproduce but I've cleared cache etc so it should be the same for everyone
> 
> If I remember correctly, the behavior in this PR was how it used to work before. If not, I think the hover effect made in this PR is a better experience than the one in edge/demo.

I like _that_ we have a hover effect, but I wonder, could we make it dim the background instead of setting the text colour (similar to other buttons when hovered)? Right now it's only visible on the payee selector in midnight mode, but not the op selector. I also think it would be worth persisting the effect on focus/when the select is open—I think this is how many other apps indicate a select. e.g. see native one in Safari which persists the focus effect:
image

**Review by matt-fidd — APPROVED** [review]
Looks good! Prefer the hover effect now, thank you.

**Comment by tim-smart** [comment]
This caused a regression where some css classes are not prioritized correctly:
image
image

It might surface itself in other places when overriding styles.

**Pull request merged**
