### PR TITLE
Dark Theme Manager and Modals

### PR DESCRIPTION
**Pull request by carkom**
darkTheme phase 4. Manager and Modals.

### CODE REVIEW

**Comment by carkom** [comment]
Still WIP

**Comment by carkom** [comment]
@MatissJanis, I've gone through and removed any changes to the code and focused instead on just swapping "colors" to "theme" and then matching the colors in order to avoid any regression. Please check my work in hopes that I didn't miss anything. Cheers!

**Review by MatissJanis — CHANGES_REQUESTED** [review]
Spotted just one small issue. Apart from that - LGTM!

**Comment by carkom** [comment]
> Spotted just one small issue. Apart from that - LGTM!

Fixed!

**Review by MatissJanis — APPROVED** [review]
Perfect!

**Pull request merged**
