### PR TITLE
Mobile: To Budget inconsistency 

### PR DESCRIPTION
**Pull request by shall0pass**
Addresses https://github.com/actualbudget/actual/issues/1538

Just had to rearrange a few things.

### CODE REVIEW

**Comment by MatissJanis** [comment]
I don't quite understand why moving this code to a new component solves the problem. Fundamentally it's still the same thing, right?

Is there a deeper root-cause issue?

**Comment by shall0pass** [comment]
Yes.  The useContext wasn't resolving for the initial definition and it was trying to pull out of the '__global' spreadsheet instead of the current months spreadsheet.  I saw this same approach was used in MobileBudgetTable.js to get around this for presumably this reason.  I wasn't sure how to add the equivalent of 

<NamespaceContext.Provider value={monthUtils.sheetForMonth(month, type)}>

to the useSpreadsheet command. So I basically did a copy/paste operation of the already used approach.

**Comment by MatissJanis** [comment]
Oh, I understand now. Previously we were using `useSheetValue` OUTSIDE the context, but now with the move to a separate component it will be used INSIDE the context.

**Review by MatissJanis — APPROVED** [review]

**Review by trevdor — APPROVED** [review]
👍🏻

**Pull request merged**
