### PR TITLE
add delay when dispatching modals to prevent ghost interactions

### PR DESCRIPTION
**Pull request by tim-smart**
While testing on mobile, using onClick eliminated some issues where some
modals were receiving pointer up events from a previous interaction,
causing some "ghost" interations.

### CODE REVIEW

**Comment by MatissJanis** [comment]
👋 What issue is this solving? How can we reproduce it?

**Comment by tim-smart** [comment]
When clicking on menu items like "Cover overspending", the pointer event can also trigger the category selector on the modal that is overlayed, causing two category selectors to be displayed.

**Comment by joel-jeremy** [comment]
@tim-smart Is it possible to handle this by controlling the propagation of the pointer/click events?

**Comment by tim-smart** [comment]
The handlers already have .stopPropagation() applied, so it seems that doesn't work.

**Pull request closed without merging**
