### PR TITLE
Fix running balances thick header.

### LINKED ISSUE #3075: [Bug]: Larger border on running balance column header
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Screenshot taken on edge.actualbudget.org with the test budget.

To reproduce, turn running balance on and you'll see the top and bottom borders on the "Balance" column header are larger than the surrounding ones.

image

### What browsers are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by psybers**
Fixes #3075.

Note: I branched off of #3080 as it modifies the same line.

### CODE REVIEW

**Comment by youngcw** [comment]
#3076 was already looking at this

**Comment by youngcw** [comment]
this makes the header text left justified instead of right

**Comment by psybers** [comment]
Good catch. Should be fixed now.

**Review by jfdoming — DISMISSED** [review]
visually this looks good to me!

**Review by youngcw — APPROVED** [review]

**Pull request merged**
