### PR TITLE
Make the “Not logged in” warning a button

### PR DESCRIPTION
**Pull request by j-f1**
Flow:

1. log into an Actual server
1. change the server password in another browser (or delete the `server-files` DB)
1. Reload the budget page. Now the top right says “Not logged in”
1. Click on “Not logged in” to close the current file and open the bootstrap/login flow

Once you click the “Not logged in” button you can go to “Change” → “Stop using a server” to get back to your local files.

### CODE REVIEW

**Comment by rich-howell** [comment]
If the password has been changed, would it not make sense to send the user back to the boostrap page so they can re-authenticate?

**Comment by j-f1** [comment]
I don’t want to block them from accessing the app, so I think it makes sense to just have the warning in the top light that they can click to go to the login page if they want to.

**Comment by j-f1** [comment]
Opened [a support thread](https://answers.netlify.com/t/build-fails-with-enoent-in-a-dependency-during-yarn-install/86043) about the build failures.

**Comment by rich-howell** [comment]
> I don’t want to block them from accessing the app, so I think it makes sense to just have the warning in the top light that they can click to go to the login page if they want to.

Ok

**Review by MatissJanis — APPROVED** [review]
Makes sense

**Pull request merged**
