### PR TITLE
:sparkles: (budget-type) moving the selector to settings page

### PR DESCRIPTION
**Pull request by MatissJanis**
Related: https://github.com/actualbudget/actual/issues/2999

Screenshot 2024-07-09 at 21 00 23

**Why does it require 2x clicks to switch the budget type first time?** No clue. But that's broken in edge too, so not really related to the code move. I might look into fixing this later (in another PR).

### CODE REVIEW

**Comment by youngcw** [comment]
Is there something we could do to make that settings card not so big?  It seems to imply that that setting is more important than it really is.

**Comment by matt-fidd** [comment]
Is it worth highlighting that report budgets are still experimental (I know this is part of the change to start releasing them) for now?

**Review by youngcw — APPROVED** [review]

**Comment by MatissJanis** [comment]
@youngcw @matt-fidd 

> Is there something we could do to make that settings card not so big? It seems to imply that that setting is more important than it really is. Or maybe put it in the advanced settings section?

I think we have a couple options here:

1. reduce the amount of content - though I'm not sure what else we could cut from this block while still keeping in meaningful;
2. move the block to a different position on the page - I'm open to this; personally I don't think this is an "advanced feature", so I'd prefer to keep it in "general settings" section. So maybe have it below e2e settings and above exporting (I think export makes sense to be the last one)? WDYT?
3. reduce the font size or change the style of this setting block - I don't think that's a good idea as it would create an inconsistency in the page

> Is it worth highlighting that report budgets are still experimental (I know this is part of the change to start releasing them) for now?
The setting block is only visible if the experimental feature is turned ON. So IMO there is no need to add extra copy here reminding folks again that this is a unstable feature.

**Comment by youngcw** [comment]
Could the explanations for the types be hidden by default with the option to expand the card and show the explanations?

Moving it down could be fine too.

**Comment by MatissJanis** [comment]
Moved it down :+1:

**Review by youngcw — APPROVED** [review]

**Pull request merged**
