### PR TITLE
[WIP] Revert ":electron: Update Electron to latest stable version  (#2763)"

### PR DESCRIPTION
**Pull request by MatissJanis**
This reverts commit 2901b5e5d0fd8af0beb6cce216383d825bba75e3.

Just checking if reverting this PR would fix https://github.com/actualbudget/actual/issues/2705

### CODE REVIEW

**Comment by MatissJanis** [comment]
Nope, this is not the problem.

**Comment by youngcw** [comment]
I believe that was the only change to electron this last month.  My next guess would be that there is something happening with the GH Mac runner.

**Comment by MatissJanis** [comment]
That's a good idea. The build here is working OK: https://github.com/actualbudget/actual/actions/runs/8971187425

I'll re-run the job and see if the new build breaks.

**Comment by MatissJanis** [comment]
The new build breaks! You're on to something @youngcw !

https://github.com/actualbudget/actual/actions/runs/8971187425

--

Lets move the discussion back to https://github.com/actualbudget/actual/issues/2705

**Pull request closed without merging**
