### PR TITLE
Fix menuItemTextHeader contrast in dark mode

### LINKED ISSUE #2395: [Bug]: Dark Theme - Edit Transaction Drop Down Heading Contrast
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### Is this related to GoCardless, Simplefin or another bank-sync provider?

- [ ] I have checked my server logs and could not see any errors there
- [ ] I will be attaching my server logs to this issue
- [ ] I will be attaching my client-side (browser) logs to this issue
- [ ] I understand that this issue will be automatically closed if insufficient information is provided

### What happened?

The contrast on the "Edit Field" heading when you click the transaction drop down is almost unreadable. 

image

Changing the color to `--color-pageTextPositive` which uses #B990FF makes it a bit easier to read but it still fails AA

image

According to webaim it needs to be #E8DCF4 which is pretty light. 

image

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

### LINKED ISSUE #2644: [Bug]: Transaction Edit menu shortcuts have poor contrast in dark mode (and lesser so in midnight)
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Referring to the short cut letters on the right side of the transaction edit menu.

If the shortcut for Show wasn't F they could be done away with entirely by underlining their respective short cut letter in the action name itself.

Light for comparison:
image

Dark (very poor contrast):
image

Midnight (poor contrast):
image

Generally, I think the size of these could be improved which would aid, but improving contrast should help with discoverability enough.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by matt-fidd**
Fixes #2395
Fixes #2644

https://webaim.org/resources/contrastchecker/?fcolor=F2EBFE&bcolor=486581

image

### CODE REVIEW

**Comment by youngcw** [comment]
This is much easier to read, but the color is basically the same as the regular text.  Could it be a shade or two darker and still meet contrast levels?

**Comment by matt-fidd** [comment]
Unfortunately it looks like even purple150 (p9) fails 

image

**Comment by sierikov** [comment]
This combination of colors may work. For this case, we can make the background slightly darkened so we can meet the contrast ratio more easily.

Accent: `#c699fa`
Background: `#2a435e` 
This pair produces a ratio of 4.52.

This will look like this: 
Screenshot 2024-04-25 at 17 28 39

What do you think?

**Comment by youngcw** [comment]
I would be ok with a darker background color for all those menus in the account page.  That would make for much more text colors to choose from.  I think that purple accent color is nice, where the current one is hard to see for the keyboard shortcuts

**Comment by matt-fidd** [comment]
Thank you for the suggestions, I've kept it within the predefined colours but darkened the menu background and changed the accent colour to purple.

I've also extended this to fix #2644 and so altered the midnight theme to change the keybind accent colour to purple.

Checked this all in webaim and it meets requirements

**Comment by youngcw** [comment]
I think that looks pretty good

**Comment by matt-fidd** [comment]
Just noticed we've lost the horizontal separator in dark mode. One second

**Review by youngcw — APPROVED** [review]

**Pull request merged**
