### PR TITLE
Add an “Experimental Features” section in the settings

### PR DESCRIPTION
**Pull request by j-f1**
This is under the advanced section. Maybe it makes sense to only turn this on in dev/preview mode? But especially as bank syncing starts to be built it would be nice to let people turn these things on.

Screenshot_2023-01-14 17 49 47Screenshot_2023-01-14 17 51 13

### CODE REVIEW

**Comment by TechwizEE** [comment]
Brought up the Netifly Deploy Preview, confirmed the "Experimental features" section appears after clicking "Show advanced settings", toggled the two check boxes several times and they toggle without issue.  

I was not apparent the check boxes enable/control additional functionality at this point.  I reviewed the code and concluded this was mostly a cosmetic change with two new settings flags: `flags.reportBudget` and `flags.syncAccount`.  Is there additional functionality to be tested?

**Comment by j-f1** [comment]
The `reportBudget` flag toggles on a button titled “Rollover budget” in the Budget screen, and `syncAccount` changes the “Add Account” modal

**Comment by TechwizEE** [comment]
Reviewed the action performed by "Enable budget mode toggle"
- Saw the "Rollover budget" option appear in the "Budget"
- Clicked "Rollover budget", then clicked "Switch ...", observed the budget change
- Clicked "Switch ..." again, and saw the budget change back
- While in "Report budget mode", went to "Experimental features" and saw "Enable budget mode toggle" show additional text "Switch to a rollover budget before turning off this feature"

Reviewed the action performed by "Enable account syncing"
- Saw the "Add Account" modal change
- It now shows two options: "Link bank account" and "Create local account"
- Clicked "Link bank account", saw a new modal with button "Link back in browser", clicked button and was taken to https://link.actualbudget.com, the website showed error "An error occurred: a valid token is missing"
- Clicked "Create local account", saw the appropriate modal

Unchecked both toggles in "Experimental features"
- Saw "Rollover budget" option disappear from the "Budget"
- Saw the normal "Create Local Account" model come up when "Add account" is clicked.

@j-f1 Nice job!  Any other features or interactions I missed?

**Comment by j-f1** [comment]
Great! I think that’s everything (although James is responsible for all of the actual functionality, not me)

**Comment by MatissJanis** [comment]
👋 Overall I think this is a good idea. I've actually also been thinking of ways to allow people build things under feature flags that _might_ not eventually end up in the _full_ product. The work you did here will allow people to swap the experimental features on/off. Which is great!

Though can we make the process of enabling these features more complex? Currently it's easy to misclick (especially on mobile) and accidentally enable a feature. What if enabling a feature kicks of some migration script that breaks the budget? Then you're screwed.

What I was thinking: it would be nice if turning features on/off would be a two step process.

Either:
1. "unlock" the feature flag checkboxes by ticking some box/key
2. then modify the feature flags as currently

Or:
1. allow toggling the feature flags (like now)
2. add a "save" button; only after clicking it do the feature flags actually persist

**Comment by j-f1** [comment]
Added this. You have to click it to show the checkboxes. And experimental features using the checkbox UI should ideally not do anything immediately when you check the checkbox (e.g. how the report budget toggle just enables another toggle in the budget view)

Screenshot_2023-01-17 16 24 56

**Review by MatissJanis — DISMISSED** [review]
Looks good to me.

**Review by MatissJanis — APPROVED** [review]

**Pull request merged**
