### PR TITLE
Dark Theme color fixes

### PR DESCRIPTION
**Pull request by carkom**
Fixing or updating some dark mode colors.

### CODE REVIEW

**Comment by youngcw** [comment]
Did you miss pushing a commit?  I don't see anything different on the missed colors

**Comment by carkom** [comment]
> Did you miss pushing a commit? I don't see anything different on the missed colors

Just hadn't pushed. Got distracted with RL stuff. Sorry!

**Comment by youngcw** [comment]
it feels weird that the note gets darker when hovering.  The month notes icon stay the same with feels better.  I would prefer something that was subdued like the light mode has, but that might be exactly what was happening before the change.

**Comment by carkom** [comment]
> it feels weird that the note gets darker when hovering. The month notes icon stay the same with feels better. I would prefer something that was subdued like the light mode has, but that might be exactly what was happening before the change.

We can make it whatever we like. There's some inconsistency here in coloring. I would suggest we copy the way light theme month icons functions and appy it to categoroes and month notes for both light and dark.

Light theme functions as follows. We should make these consistent, just a matter of choosing which to do then I can apply to both light and dark themes in the same manner.

Month notes icon:
- empty and unhovered - transparent
- empty and hoveredRow - subdued
- empty and hoveredButton - black
- hasNotes and unhovered - subdued
- hasNotes and hovered - subdued
- hasNotes and hovered Button - black
- both empty/hasNotes Selected (editing notes) - black

Category notes icon:
- empty and unhovered - transparent
- empty and hoveredRow - black
- empty and hoveredButton - black
- hasNotes and unhovered - black
- hasNotes and hovered - black
- hasNotes and hovered Button - black
- both empty/hasNotes Selected (editing notes) - transparent

**Comment by carkom** [comment]
If no other changes, I'd say this is ready for review. Cheers!

**Comment by youngcw** [comment]
I think my only nitpik is that the negative value color on the budget table seems more washed out than the other colors now
image

**Comment by youngcw** [comment]
> I think my only nitpik is that the negative value color on the budget table seems more washed out than the other colors now

Condering those colors only show with goal templates enabled, this is probably not a big deal right now.

**Review by youngcw — APPROVED** [review]

**Pull request merged**
