### PR TITLE
PageRoute concept

### PR DESCRIPTION
**Pull request by trevdor**
An attempt to keep Reports and Budget always-rendered like they used to be, but compatible with React Router 6.

Still some bugs with this.

### CODE REVIEW

**Comment by j-f1** [comment]
Something else to check for that must have broken recently: clicking the balance on any of the account index pages (all, on budget, off budget, not the per-account ones) should toggle the extra balances.

**Comment by trevdor** [comment]
> roken recently: clicking the balance on any of the account index pages (all, on budget, off budget, not the per-account ones) should toggle the extra balances.

I don't think this is broken anymore? Can't repro, anyway. "All accounts" hides the cleared column, so there's no cleared/uncleared distinction. Suspect we should stop that screen showing the expander on hover at all.

**Comment by trevdor** [comment]
@MatissJanis Updated to have only /budget be persistent. 
Haven't tested locally yet bc my local build is failing:
Screenshot 2023-07-28 at 10 46 01 AM

**Comment by MatissJanis** [comment]
Looks like the Netlify build is also failing with an error (possibly the same you observed locally).

**Comment by trevdor** [comment]
Closing. 
So far I haven't been able to get this "persistent route" concept working in RR v6, and want to focus on other issues. 

I'm also not sure keeping the budget page always-rendered is the right approach. It was an attempt to replicate what we did under RR v5. But if we simply want to avoid re-loading a large amount of data on return to this page, other approaches should be possible.

**Pull request closed without merging**
