### PR TITLE
Consider child transactions when fuzzy matching imported transactions

### PR DESCRIPTION
**Pull request by joel-jeremy**
Match split transaction entries when importing transactions

### CODE REVIEW

**Comment by youngcw** [comment]
Have you tested this with SimpleFIN?

Should this get extended to file imports?

**Comment by joel-jeremy** [comment]
I was able to test in SimpleFIN. I don't have a GoCardless account so I haven't tested that. I have also applied the same on the file imports here: https://github.com/actualbudget/actual/pull/2309/files#diff-686fc94775444483c551d99e96c7bc92175543a53600f050fa2cdbe119b10523L640

**Review by youngcw — APPROVED** [review]

**Comment by yoyotogblo** [comment]
What does it mean to fuzzy match a split trasnsaction? 

So if I have a split: 
Parent Transaction $100
Child 1: Category - Food, Amount - $70
Child 2: Category - Toiletries, Amount - $30

The imported transaction would always be $100 so how would it match a child transaction? Shouldn't it be trying to match only the parent (which it currently does)?

**Comment by youngcw** [comment]
@yoyotogblo I believe the use case would be if you combined imported transactions into a single split, like a wire transfer and its fee for example. Each are single transactions in the bank, but could be nice to combine in Actual.

**Comment by yoyotogblo** [comment]
> @yoyotogblo I believe the use case would be if you combined imported transactions into a single split, like a wire transfer and its fee for example. Each are single transactions in the bank, but could be nice to combine in Actual.

Is combining imported transactions possible in Actual? Personally, I prefer leaving the integrity of the transactions in place (so leaving those 2 transactions separate). But if combining is a thing, then I can see why this could be useful. Otherwise, not sure of a use-case for it.

**Comment by joel-jeremy** [comment]
> Is combining imported transactions possible in Actual? Personally, I prefer leaving the integrity of the transactions in place (so leaving those 2 transactions separate). But if combining is a thing, then I can see why this could be useful. Otherwise, not sure of a use-case for it.

The most common use case for this is grouping the fee and the actual purchase together. Or breaking down credit card statements with the individual purchases/installments being child transactions.

**Comment by yoyotogblo** [comment]
> The most common use case for this is grouping the fee and the actual purchase together. Or breaking down credit card statements with the individual purchases/installments being child transactions.

Thanks... How would you group the fee and actual purchase together? Or are you saying you manually enter the two transactions as one parent transaction and 2 child transactions, and then you want the imported transactions to match each child?

Also, I don't believe breaking down a transaction into many child transactions (split transactions) isn't really applicable in this case because the imported transaction won't match any of the child transactions.

Sorry about all these questions. On my end, just a bit concerned about even more fuzzy matching when it has the potential to be the wrong match especially with Actual not requesting approval of matches (like YNAB does).

**Pull request merged**
