### PR TITLE
:bug: (electron) always show titlebar

### PR DESCRIPTION
**Pull request by MatissJanis**
https://github.com/actualbudget/actual/issues/1047

Before:

image

After:

Screenshot 2023-07-29 at 20 12 25

### CODE REVIEW

**Comment by MatissJanis** [comment]
Would appreciate some testing on windows machine here @Shazib

**Comment by Shazib** [comment]
> Would appreciate some testing on windows machine here @Shazib

Looks good to me. 

The '<<' to collapse is broken and practically invisible but thats probably an unrelated dark-theme thing.

image

**Review by j-f1 — APPROVED** [review]
That works! A little less fancy than the old style but a lot easier to deal with conceptually.

**Comment by MatissJanis** [comment]
@Shazib thanks, we have already an issue for that here: https://github.com/actualbudget/actual/issues/1416 :)

**Pull request merged**
