### PR TITLE
Update screenshot

### LINKED ISSUE #1476: [Maintenance] Update the product screenshot in README.md
The screenshot in README.md is outdated. Would be nice if someone could update it to the latest one.

Feel free to use the DEMO budget as an example to showcase some data.

### PR DESCRIPTION
**Pull request by adamkelly86**
Closes #1476

### CODE REVIEW

**Comment by joel-jeremy** [comment]
I suggest we screenshot the test budget in #1442

**Comment by adamkelly86** [comment]
I took the one from docs

**Comment by MatissJanis** [comment]
I'll merge this PR for now. We can update the screenshot once the emoji PR is merged.

**Comment by MatissJanis** [comment]
Thanks, by the way!

**Pull request merged**
