### PR TITLE
Adds delay before note is displayed on hover. Solves issue #658. 

### LINKED ISSUE #658: Add delay to note display on hover
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I am really appreciating the display of notes on hover over the notes boxes. However, the display is instant and can get in the way when working on the budget.

### Describe your ideal solution to this problem

This is just a quality of life request. Is it possible to incorporate a momentary delay to the reveal of the note? Just enough delay so that the notes do not pop up unintentionally when scrolling through the budget?
Thank you for considering.

### Teaching and learning

_No response_

### PR DESCRIPTION
**Pull request by venkata-krishnas**
Since the issue was to provide some delay so that the note doesn't display immediately on hover, I have added a 2 second delay. As this issue felt fairly easy to solve, I am submitting this PR. This is my first pull request on open source. Thank you for this opportunity. If there's a mistake I would love some feedback as this will be a great learning opportunity.

Fixes #658

### CODE REVIEW

**Comment by Kidglove57** [comment]
Thank you so much for working on my issue 658! I am grateful. My only comment would be that perhaps 2 seconds is too long and would mean that people would think that the hover feature is not working at all? Even ½ second would be enough in my view, so that the notes do not flash up instantly if accidentally moving the cursor over that area.

**Comment by glp-66** [comment]
I feel like 2 seconds is too long as well. I like the way it functions now. I might be ok with 1/2 sec

**Comment by venkata-krishnas** [comment]
Hi, Can anyone please explain me why the tests are failing? The changes seem to be working for me.

**Comment by j-f1** [comment]
The Netlify build is failing for reasons we do not understand across all PRs. Approved the other tests to run for you though.

**Comment by trevdor** [comment]
@venkata-krishnas Have you tried 200-300ms? I suspect it would still give the delay needed to avoid accidental hover actions, while keeping the use case for the tooltip snappy.

**Comment by venkata-krishnas** [comment]
Hi @trevdor, I've tried different delays. 200 300 still felt a little quick in my opinion. But I think duration delay can be subjective. I am not sure which delay is perfect honestly.

**Comment by j-f1** [comment]
If you run `yarn lint --fix` from the project root folder, it should reformat your code to comply with our code style guidelines, which should fix those issues.

**Comment by venkata-krishnas** [comment]
Thank you. Will do.

**Comment by venkata-krishnas** [comment]
I am running this command in the root folder, but I am getting this error.
yarn lint --fix               
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...

**Comment by j-f1** [comment]
Try running `yarn install` first.

**Comment by venkata-krishnas** [comment]
Hello, 
E2E Tests / Run end-to-end tests on Netlify PR preview (pull_request) keep failing. Is this something due to my changes or is this related to other netlify tests failing?

**Comment by Kidglove57** [comment]
I have been wondering the same about the duration of the delay and I agree that it is subjective. It only requires a momentary "pause". If we had the preview operating again it would be an easier choice ...!

**Comment by j-f1** [comment]
> E2E Tests / Run end-to-end tests on Netlify PR preview (pull_request) keep failing. Is this something due to my changes or is this related to other netlify tests failing?

Since the end-to-end tests require the deploy to succeed before they can run, they are currently failing. No need to worry about that until we get the Netlify build working again!

**Comment by venkata-krishnas** [comment]
Thank you @j-f1.

**Comment by j-f1** [comment]
Just merged the latest changes in which should fix the build issues so we can give this a try!

**Comment by j-f1** [comment]
I tested it out in the preview and noticed a small issue. If I mouse in and quickly mouse out of the button before the timer is up, the note will still pop up and can’t be easily closed.

https://user-images.githubusercontent.com/25517624/221014649-4000dea9-e7e6-4d59-a9f4-993533fbff76.mov

**Review by j-f1 — CHANGES_REQUESTED** [review]
Marking as changes requested due to the above issue — ideally the note would only pop up after hovering the mouse over the button for 0.5s, and that wait would be cancelled when moving the mouse out of the button.

**Comment by venkata-krishnas** [comment]
I will work on the changes and let you know. THank you.

**Comment by venkata-krishnas** [comment]
Hey @j-f1 . I fixed the issue. Can you please test it now. Thank you.

**Comment by venkata-krishnas** [comment]
Also is there a way I can test my code without using the preview. I do not want to PR every time I want to test it in preview. How do I deploy it on my local host. Thank you.

**Comment by trevdor** [comment]
Now that I've tried it on the preview, I'm more convinced 500 ms is a bit too long of a delay for a hover action. 
If you don't pause, I wouldn't think 200-300ms would trigger any popups unintentionally.
And, though this isn't authoritative by any means, it's been my experience that those smaller delays are more commonly used in UIs. 

(Also, @venkata-krishnas, have you seen [this guide for local installs](https://actualbudget.github.io/docs/Installing/Local/your-own-machine/#running-actual)?)

**Comment by venkata-krishnas** [comment]
@trevdor Thank you. I was only looking at the contribute part of the documentation. Also the delay in my last commit is 300ms. Do you think I should go down to 100 or 200?

**Comment by Kidglove57** [comment]
@venkata-krishnas I tested the Preview just a few moments ago and I thought the new delay was perfect. Thank you!

**Comment by venkata-krishnas** [comment]
@Kidglove57 Thanks for the feedback :) .

**Comment by trevdor** [comment]
Ahhh, I'm sorry. Looks like I hadn't tried the updated delay. It feels great right now. Thanks, @venkata-krishnas.

**Pull request merged**
