### PR TITLE
:bug: (rules) fix filtering in the rules page

### LINKED ISSUE #1502: [Bug]: Rules only partially loaded
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When accessing the "Rules" page, I only get part of them.

Until a few days ago (probably until upgrade to v23.8.0), I could scroll to the bottom of the page and other rules would be loaded.
Now, when scrolling to the bottom of the page, nothing happens.

Could it be related to #1342 ?

Moreover, filtering on rules only work on rules that have been loaded, therefore I could only filter on a subset of the rules I have.

When creating a new rule (after clicking on "Save"), all rules are loaded, filtering works as expected, etc.

### What error did you receive?

No error

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

### PR DESCRIPTION
**Pull request by MatissJanis**
Previously the filtering was applied only to the loaded data. Meaning if there are >1 pages of data - it would initially apply only to the first page. After this fix - the filters are applied to all the pages.

### CODE REVIEW

**Comment by MatissJanis** [comment]
> But I haven't been able to reproduce the filtering issue in master.

You would need to have multiple pages of rules to reproduce. It won't be possible with the test budget as there' s just not enough rules.

> I have however reproduced the other issue referenced in the issue, which remains with this change. Which is that loadMore just isn't firing at all for me in firefox (works fine in my chrome).

Argh.. ok, I'll unlink the bug report. So this change isn't fixing it. Still - it fixes a different issue.

**Comment by jasonmichalski** [comment]
just submitted PR #2167 to merge into this branch ... should fix the load more rules, but more testers definitely welcome

**Review by carkom — APPROVED** [review]
LGTM!

**Review by twk3 — APPROVED** [review]
@MatissJanis you can go ahead a relink this to https://github.com/actualbudget/actual/issues/1502 because it's now fixing both issues mentioned there.

I reread the issue and finally comprehended what the initial issue was. (I kept thinking it was the loadMore that wasn't being filtered but that was working fine)

This PR looks good. 
- Cleans up multiple redundant state
- Filter now applies against the full data, so items in future pages now show up right away when the filter includes them and they should be appearing.
- loadMore is firing properly when scrolling down in firefox  (tested on linux popOS)

Thanks @MatissJanis and @jasonmichalski

**Pull request merged**
