### PR TITLE
[WIP] Adding a repeat count - #241

### PR DESCRIPTION
**Pull request by manuelcanepa**
This commit introduce a new field (Repeat count), with this number, the schedule rule will be created with a lte date to stop after N repetitions

### CODE REVIEW

**Comment by MatissJanis** [comment]
Thanks, I'm now able to test the feature.

Overall IMO this is a good idea, but there's some things we need to polish.

What made you choose to implement a "repeat count" feature? Did you consider other alternatives such as "end date"?

Personally I think an "end date" is easier to understand and hence would be nicer for the customer. I would recommend adding a "end date" field + the option to toggle "no end date" (enabled by default). 

Irrelevant which approach we choose - there is a small bug - the "upcoming next dates" table is incorrect - it should show only 1x date if this transaction repeats 1x (screenshot 1)

Screenshot 2023-01-05 at 20 20 06

I would also like to hear some more thoughts from the community before we merge this to master.

**Comment by trevdor** [comment]
Hey friends. 👋🏻  
I'll offer another opinion: it would be lovely to offer both end date and "repeat X times" options.
Notably, Apple and Google both do just that in their own calendars.

@manuelcanepa Would you be interested in adding the end date alternative to this PR as you polish it up? 

Other notes:
1. Apple & Google both keep the UI simple until you dig into customizations. You pick a frequency and they'll repeat the calendar event forever.
2. For custom repeat, both offer:
    A. Ends: _never_ (default, since it matches the simple case in [1])
    B. Ends on date
    C. Ends after X occurrences 

### Apple
apple_calendar

### Google 
google_calendar

**Comment by rich-howell** [comment]
> > Hey friends. 👋🏻 I'll offer another opinion: it would be lovely to offer both end date and "repeat X times" options. Notably, Apple and Google both do just that in their own calendars.
> > @manuelcanepa Would you be interested in adding the end date alternative to this PR as you polish it up?
> > ...
> 
> I love it! Maybe i will need some assistant with css, but in terms of programming i can achieve that. Give me some time to do it.

We can help with CSS where required, so glad you are still willing to push this PR forward.

**Comment by SalvyTek** [comment]
I've done some tests these days and everything seems to be working fine.

Instead of always showing 4 dates, if the number of repetitions is less than 4 (for example 2), wouldn't it be better to display the exact number of dates (in this case only two dates)?

image

Thank you so much for the great job you are doing and sorry for my terrible english...

**Comment by MatissJanis** [comment]
👋 Hey! Just checking in since this PR has been inactive for a long time.

@manuelcanepa are you planing to pick this up again?

**Comment by MatissJanis** [comment]
:wave: I'll close this off for now due to inactivity, but please feel free to continue working on this and open a new PR once it's ready for review again. It'd be great to get this feature merged eventually!

**Comment by MSBack** [comment]
@manuelcanepa Hope you will open and finish a pull request with this feature!

**Comment by manuelcanepa** [comment]
@MSBack Im sorry, im a little busy right now. I have some PR to refine and push.

**Comment by Alistair1231** [comment]
This would be really useful!

**Pull request closed without merging**
