### PR TITLE
[WIP] Update tooltip and themes with better visibility

### PR DESCRIPTION
**Pull request by VoltaicGRiD**
---
category: Enhancements
authors: [VoltaicGRiD, psybers]
---

Implement greater visibility and accessibility on popover menus and tooltips
---

Release notes also appended to the `upcoming-release-notes` dir.
Updated themes and tooltip code with proper borders for accessibility and visibility on all themes.

### CODE REVIEW

**Review by psybers — APPROVED** [review]

**Comment by psybers** [comment]
LGTM!

You will need to update the visual regression test images.

**Comment by psybers** [comment]
@VoltaicGRiD Are you able to update this?

**Comment by VoltaicGRiD** [comment]
> LGTM!
> 
> You will need to update the visual regression test images.

Yeah, I'd be happy to update them, but not sure where they are.

**Comment by psybers** [comment]
> Yeah, I'd be happy to update them, but not sure where they are.

In the `actual` repo, you will want to look at the instructions in https://github.com/actualbudget/actual/blob/master/packages/desktop-client/README.md on how to run the E2E VRT suite.  Be sure to include the `--update-snapshots` argument and it will regenerate the images.  Then just commit and push any it changed.

**Pull request closed without merging**
