### PR TITLE
Undoable auto transfer notes + auto notes for cover

### PR DESCRIPTION
**Pull request by joel-jeremy**
Resolves https://github.com/actualbudget/actual/issues/3404

### CODE REVIEW

**Comment by youngcw** [comment]
Seems to work well.  @Teprifer do you see anything else that needs fixed here?

**Comment by Teprifer** [comment]
> Seems to work well. @Teprifer do you see anything else that needs fixed here?

I feel bad not picking up on it before. :(

There's something a bit weird with the undo, it needs to be done twice if the note is viewed, this isn't the case in a few days old edge.

To reproduce:
1.  Do a transfer
1.  Click to check note
1.  Click outside to dismiss note
1.  ctrl+z (nothing happens)
1.  ctrl+z again (action is undone)

This stacks:

1.  Do a transfer
1.  Click to check note
1.  Click outside to dismiss note
1.  Do a transfer
1.  Click to check note
1.  Click outside to dismiss note
1.  ctrl+z (nothing happens)
1.  ctrl+z again (second action is undone)
1.  ctrl+z (nothing happens)
1.  ctrl+z again (first action is undone)

If not clicking the note in between, then only one ctrl+z is required.

1.  Do a transfer
1.  ctrl+z (action is undone)

Fairly minor overall, but could be come across as ctrl+z not working in niche cases?

**Comment by Teprifer** [comment]
Cheers for fixing the ctrl+z.

I, uh, mis-clicked when testing and found a difference in transfer behaviour to Edge:

In Edge if you click a category to assign the funds to another category and select the source category as the destination category nothing happens. In this PR it'll allocate the transfer value again to that category, pulling from To Budget (obviously).

This PR:
image

Transfer food to food:
image

Result:
image

**Comment by joel-jeremy** [comment]
> Cheers for fixing the ctrl+z.
> 
> I, uh, mis-clicked when testing and found a difference in transfer behaviour to Edge:
> 
> In Edge if you click a category to assign the funds to another category and select the source category as the destination category nothing happens. In this PR it'll allocate the transfer value again to that category, pulling from To Budget (obviously).
> 
> This PR: image
> 
> Transfer food to food: image
> 
> Result: image

Nice catch! I've hidden the source category in the transfer menu and cover menus.

**Comment by Teprifer** [comment]
@joel-jeremy Has that change been pushed to github? Or has the netlify build not updated? The source category is still showing for me.

Food (transfer)
image

I checked cover too, but trying to cover a negative with itself doesn't result in any note or change in budget, so this menu option is as expected.
Clothing (cover)
image

**Comment by joel-jeremy** [comment]
> @joel-jeremy Has that change been pushed to github? Or has the netlify build not updated? The source category is still showing for me.
> 
> Food (transfer) image
> 
> I checked cover too, but trying to cover a negative with itself doesn't result in any note or change in budget, so this menu option is as expected. Clothing (cover) image

Thank you for the testing it out! Sorry, I missed an if condition on the new utility method. Should be fixed now.

**Comment by Teprifer** [comment]
All good, familiar with the "oh that one other bit". Checks out functionality wise so should be good for a code review I think?

**Comment by joel-jeremy** [comment]
> All good, familiar with the "oh that one other bit". Checks out functionality wise so should be good for a code review I think?

Had to rebase to resolve a conflict. Should be good for code review :)

**Comment by Teprifer** [comment]
> > All good, familiar with the "oh that one other bit". Checks out functionality wise so should be good for a code review I think?
> 
> Had to rebase to resolve a conflict. Should be good for code review :)

Haha, well, I'm sure a code review would've picked that up - I was more indicating to others as you don't want me pretending I can code review. :)

**Pull request merged**
