### PR TITLE
Don't allow duplicate category names (per group)

### LINKED ISSUE #1829: [Bug]: Duplicate Category Names Allowed
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

It is currently possible to create infinite categories with identical names under the same parent category.

image

I had a category called **Obsidian** which I had hidden a little while ago, I had forgotten about it and decided to start my Obsidian subscription again, created another category called **Obsidian** which Actual allowed me to do. 

When you select the category Obsidian from the Category drop down on the account sheet you are then presented with both categories 

image

or in the case of the demo budget all the Food categories 

image

### What error did you receive?

No error

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by Shazib**
GUI Level check and a separate one at DB to catch API etc.

### CODE REVIEW

**Comment by rich-howell** [comment]
Hey @Shazib 

This doesn't actually fix the problem though, I could create Food in one group then hide it and create it later in another group and it would still show me two Food's on the transaction entry.

I would have to go back to the budget check which group the category is showing for then go back to the transaction entry screen and enter the transaction..seems like a lot of clicking around. 

What would the use case be for two categories on the budget being called the same thing ever existing? For example, would this be a possibility?

Usual Expenses - Food
Bills - Food

If it wouldn't it might be worth preventing duplicate category names entirely?

**Comment by Shazib** [comment]
> If it wouldn't it might be worth preventing duplicate category names entirely?

I can envisage scenarios where you have multiple of the same categories under different groups

e.g. 
"Work Expenses" -> "Food"
"Travel" -> "Food"
"Household" -> "Food"

Or 
"Holidays" -> "Travel Costs"
"Work" -> "Travel Costs"

Maybe the popup could show you the group as well?

**Comment by Shazib** [comment]
> ~~Maybe the popup could show you the group as well?~~

Maybe the popup could indicate hidden categories?

**Comment by Shazib** [comment]
@rich-howell what do you think

image

**Comment by Crazypkr1099** [comment]
> @rich-howell what do you think
> 
> image
> 

I don't like this. It's going to clutter the crap out of it. Honestly I don't see the big deal with checking your hiddens before creating a group 🤷

**Comment by Shazib** [comment]
> I don't like this. It's going to clutter the crap out of it. Honestly I don't see the big deal with checking your hiddens before creating a group 🤷

Do people have loads of hidden categories? I wouldnt consider that super cluttered personally!

**Comment by Shazib** [comment]
I actually think its kind of useful to see if its hidden 🤷

Although maybe this is kind of two separate PR's; not allowing duplicate names is fairly straightforward.

**Comment by youngcw** [comment]
I think the category picker change should be a separate PR.  

Have you checked the case of moving a category from one group to another?  I would be ok with allowing same names but different groups, but then we need to do the checks on moves as well as creates.  That wouldn't matter if only one of the same name are allowed.

**Comment by Shazib** [comment]
> I think the category picker change should be a separate PR.
> 
> Have you checked the case of moving a category from one group to another? I would be ok with allowing same names but different groups, but then we need to do the checks on moves as well as creates. That wouldn't matter if only one of the same name are allowed.

The change isn't actually in the PR just a screenshot.

I will check the case of moving a category!

**Comment by rich-howell** [comment]
> > @rich-howell what do you think
> > image
> 
> I don't like this. It's going to clutter the crap out of it. Honestly I don't see the big deal with checking your hiddens before creating a group 🤷

There are two workflows here that are impacted by hidden categories and the ability to create a category with a duplicate name.

**The Budget Sheet**

If you have a category you created 2 years ago and it is hidden your not going to remember that you hid it before creating a new one, I don't think the workflow of checking if the category is hidden before creating any new category really works all that well.

**Transaction Sheet**

When adding a new transaction, the category shows regardless of if it is hidden or not so if you select the category you hid two years ago and remember you might not know it is there you will be thinking why is my budget now showing negative numbers.

**My thoughts**

I agree that seeing if the category is hidden in the category picker is an improvement on the current workflow and would solve the problem entirely. _(You might not even have to stop people creating duplicates)_

**Comment by carkom** [comment]
This is great @Shazib. Maybe you'd be interested in doing the same for account names? If not, no worries. Cheers!

**Comment by Shazib** [comment]
> This is great @Shazib. Maybe you'd be interested in doing the same for account names? If not, no worries. Cheers!

Sure thing i can take a look at that!

**Comment by Shazib** [comment]
> This seems to be working well. Can you look at getting the tests to pass, and the merge conflicts cleared up?

@youngcw done. The electron builds are broken right now I think not due to this PR

**Comment by youngcw** [comment]
Two minor things that would be nice:
1. If you get the warning about making a duplicate it would be nice to have a way to cancel making the category.  Right now, as far as I can tell, you have to make a dummy name, then delete it.  It would be nice to cancel the creation.
2. It would be a cherry on top if the warning included the name you were trying to create. Its not necessary, but would be nice.

**Comment by rich-howell** [comment]
This still doesn't fix the problem in that I raised in the issue, it is still not clear in the category drop down which category is hidden and which isn't (screenshot taken from the deploy preview)

image

**Comment by carkom** [comment]
FYI, hidden categories is being worked on in a different PR. #1843

**Comment by Shazib** [comment]
> Two minor things that would be nice:
> 
> 1. If you get the warning about making a duplicate it would be nice to have a way to cancel making the category.  Right now, as far as I can tell, you have to make a dummy name, then delete it.  It would be nice to cancel the creation.
> 
> 2. It would be a cherry on top if the warning included the name you were trying to create. Its not necessary, but would be nice.

For point 1, Can't you just hit escape?

**Comment by youngcw** [comment]
> For point 1, Can't you just hit escape?

That doesn't close the category creation view, just clears the filled in name.

**Comment by Shazib** [comment]
> > For point 1, Can't you just hit escape?
> 
> That doesn't close the category creation view, just clears the filled in name.

Yes sorry - you can just click off it though, you don't have to go through with the create, it cancels if you focus away from the cell

**Comment by Shazib** [comment]
> This still doesn't fix the problem in that I raised in the issue, it is still not clear in the category drop down which category is hidden and which isn't (screenshot taken from the deploy preview)
> 
> image

I have removed the tag linking that issue.

I think this is safe to merge standalone while we work on that.

**Comment by youngcw** [comment]
@Shazib This is pretty much ready right?  If you merge master the electron issues should be fixed.

**Comment by Shazib** [comment]
> @Shazib This is pretty much ready right?  If you merge master the electron issues should be fixed.

@youngcw yep. I'll merge master tonight.

**Comment by youngcw** [comment]
Should this check for same name, different case? ie not capitalized

**Comment by Shazib** [comment]
> Should this check for same name, different case? ie not capitalized

good spot - added

**Comment by carkom** [comment]
> This is great @Shazib. Maybe you'd be interested in doing the same for account names? If not, no worries. Cheers!

Might be good to also do group names? Could be a separate PR.

**Comment by Shazib** [comment]
> > This is great @Shazib. Maybe you'd be interested in doing the same for account names? If not, no worries. Cheers!
> 
> Might be good to also do group names? Could be a separate PR.

Yeh i'd do that as a separate PR to avoid scope creep with this one.

**Review by youngcw — APPROVED** [review]

**Pull request merged**
