### PR TITLE
[WIP] Shows notes in transaction list on mobile, fixes #1764

### LINKED ISSUE #1764: [Feature] Add notes to mobile view
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

You need to press every transaction to see the notes of it, i think notes information is important and is only the missing info of every transaction on the account view, you need to press the transaction itself to see the notes

### Describe your ideal solution to this problem

The lates version show every transaction as this:

=========================
Date
=========================
Payee                             $0.0000
Category
==========================

It would be nice to add the notes maybe between payee and category with small letter too like this:

=========================
Date
=========================
Payee 
Notes                                      $0.0000
Category
==========================

### Teaching and learning

ADding a view to use less clicks/tabs on mobiles would be very useful and informative to see fast almost all the important info everybody want to see on the transactions

### PR DESCRIPTION
**Pull request by a-gradina**
This is not fully done. I need feedback on the UI. I'm somehow not sold on how it looks, though.
image

Fixes #1764

### CODE REVIEW

**Comment by Teprifer** [comment]
My gut is to have the notes under the category, I realise how you have it matches the order in desktop view, but somehow it seems better, maybe because it's a lower priority piece of information? With the side bonus of having more horizontal room for the notes?

I think also because where you have it now, results in the category being shown in a different order depending on if there are notes or not.

**Comment by a-gradina** [comment]
> My gut is to have the notes under the category, I realise how you have it matches the order in desktop view, but somehow it seems better, maybe because it's a lower priority piece of information? With the side bonus of having more horizontal room for the notes?
> 
> I think also because where you have it now, results in the category being shown in a different order depending on if there are notes or not.

I would find it strange if the order differs from the desktop view. However, I do agree that the note is often larger than the category, which might not look as good. As for ordering by importance, maybe I'm in the minority, but the category is the least important to me here. More often than not, I can identify the category just by looking at the Payee. But since UI/UX isn't my strong suit, I'll adjust to whatever you guys prefer.

**Comment by youngcw** [comment]
I had always thought we could use the middle for notes and not make the sides more filled then they are

**Comment by Teprifer** [comment]
> I had always thought we could use the middle for notes and not make the sides more filled then they are

Hrm, maybe, I did realize that on mobile notes are added last, so the order thing doesn't apply. 

The more jarring bit is the part I mentioned is about how the category location jumps all over the place when scrolling through transactions with and without notes.
Having notes at the bottom removes this UI quirk.

Is there another way this could be addressed?

**Comment by youngcw** [comment]
I agree that inconsistent spacing and placement would be a no go

**Comment by a-gradina** [comment]
Sooo like so?
image

**Comment by Teprifer** [comment]
> Sooo like so? image

Yeah that'd been my thinking.

And sorry I think I should clarify my earlier remark about importance, I was thinking in terms of a hierarchy of Account -> Category -> The specific thing(the note), rather than the value to us individually. :)

Also I realised I totally misread @youngcw 's comment possibly - did you mean the horizontal middle rather than vertical?
image

If so I kinda get what you're suggesting although I'm not sure how well it'd work with long notes, could look a bit information dense?

**Comment by a-gradina** [comment]
This is how I understood @youngcw’s comment as well. I prefer keeping the note on the left side. Either way, long notes need to be truncated. If the notes remain on the left, I’d suggest increasing the height of the transaction. Right now, the text seems too close together.

**Comment by ducpham01** [comment]
> > Sooo like so? image
> 
> Yeah that'd been my thinking.
> 
> And sorry I think I should clarify my earlier remark about importance, I was thinking in terms of a hierarchy of Account -> Category -> The specific thing(the note), rather than the value to us individually. :)
> 
> Also I realised I totally misread @youngcw 's comment possibly - did you mean the horizontal middle rather than vertical? image
> 
> If so I kinda get what you're suggesting although I'm not sure how well it'd work with long notes, could look a bit information dense?

I think placing notes in horizontal middle quite align with desktop view, and I like it. But for longer payee name, it would look really dense. 

So placing it like @a-gradina suggest is okay to me https://github.com/actualbudget/actual/pull/3668#issuecomment-2414720915

**Comment by a-gradina** [comment]
With [022e08e](https://github.com/actualbudget/actual/pull/3668/commits/022e08e5dc833cae262af5c080a53d6453a0697e) I restored it to how it looked in my initial commit. So now the notes are in the middle and get truncated at 25 chars. I've been trying to get playwright to work for a few nights but I can't get it to work. Right now I don't have the time to work on this, so if someone wants to take over, go ahead.

**Comment by ducpham01** [comment]
I’ll make some attempts to get playwright work. I’ll update the progress this weeekend. 

@a-gradina I’ll create a PR on your branch?

**Pull request closed without merging**
