### PR TITLE
Feature: Translate loot-design

### PR DESCRIPTION
**Pull request by manuelcanepa**

### CODE REVIEW

**Comment by MatissJanis** [comment]
👋 Hi

Its an interesting idea to add i18n to Actual. But is there a specific reason why you would want this?

Personally I don't think Actual has a big enough community to support translating the product in different languages and then to keep these languages up-to-date (emphasis on _updating existing translations_). If we do a cost vs benefit analysis then, in my opinion, the cost of building and maintaining this solution is far too steep.

Another problem we need to consider is the proposed approach of using `general.delete` type strings for all the content. It just makes development that much more difficult. Did you consider using actual English text as the `key`? So instead of `t("general.delete")` you would do `t("Delete")`. This will also _partially_ solve the 1st problem since each change to the English string will automatically stop the usage of the localized strings too.

However, I'm open to hear from other people in the community too.

Related PR: https://github.com/actualbudget/actual/pull/205

**Comment by manuelcanepa** [comment]
@MatissJanis i will reply in order. if you keep thinking that the community is small, the community will keep small. Get on the other side and think: You are looking for a project like this to manage your money but you dont's speak english at all, you will offer a hand to translate and improve the project or you will create a new project from scratch on your own language? On the other hand, i agree with you about the keys, idk why we  start using that approach.

**Comment by turbcool** [comment]
Lacking translation is a showstopper. My family doesn't know English and even though Actual is a wonderful app, I'd choose something else (Firefly III) because it has translations.

**Comment by j-f1** [comment]
Closing this for now as well since #205 has been closed.

**Pull request closed without merging**
