### PR TITLE
Remove usage of Formik

### PR DESCRIPTION
**Pull request by j-f1**
This is a fairly large dependency, and we use it pretty lightly (just in the create/close account modals). It isn’t pulling its weight, so I’m removing it.

### CODE REVIEW

**Comment by TomAFrench** [comment]
If I create a new account on this, once I click the `create` button then I go back to the previous modal where I can choose between local and nordigen accounts. Is this expected?

**Comment by j-f1** [comment]
That’s a bug in the `master` version too but I can fix it!

**Comment by TomAFrench** [comment]
Ah ok, I'm able to do the full create/close flow just fine so this PR looks good to me. If you want to roll that fix into this PR then that's fine with me but it can also go in a separate PR.

**Comment by j-f1** [comment]
It’s sufficiently unrelated, I will open a follow-up PR.

**Review by MatissJanis — APPROVED** [review]

**Pull request merged**
