### PR TITLE
Add option to set how far out the upcoming scheduled transactions are shown in the account view.

### PR DESCRIPTION
**Pull request by SamBobBarnes**
Add option to set how far out the upcoming scheduled transactions are shown in the account view.
This option can be set to 1, 7, 14, or 30 days out from today.

The only thing lacking from this enhancement, that I couldn't work out how to implement, was longer periods (eg 2-3 mo) because I couldn't work out how to show more than just the next instance of a scheduled transaction. This may also be an issue if a user has scheduled transactions that should occur more than once per visible period.

I implemented this enhancement because I was frustrated that I could only see 7 days into the future and could not plan ahead very far into the future. This is something that I wanted because I was moving from quicken where I utilized seeing a month in the future often for planning purposes.

### CODE REVIEW

**Comment by youngcw** [comment]
Could the setting live somewhere other than the settings page?  Like in the schedules page?

**Comment by joel-jeremy** [comment]
This setting should be moved to the schedule creation form IMO. We could have a "Remind me X days ahead" setting which can be different per schedule.

**Comment by SamBobBarnes** [comment]
> Could the setting live somewhere other than the settings page? Like in the schedules page?

I moved the setting to the schedules page

**Comment by youngcw** [comment]
The schedules page location is better.  Personally, I think that above the table would be nicer, but maybe thats just me.

**Comment by joel-jeremy** [comment]
Having it collapsed as default would be great too since I imagine the option won't be changed often.

Personally, it would be best if we can add an option to "Remind x days ahead" here but it's not required on this PR. That would also require more effort since it would need some change to the database.
image

**Comment by youngcw** [comment]
I feel like the box to edit the schedule show window should show the current option by default and not require the user to click edit to see what it is.  Probably could just get rid of the edit button and just show the window length selection.

**Comment by SamBobBarnes** [comment]
> I feel like the box to edit the schedule show window should show the current option by default and not require the user to click edit to see what it is. Probably could just get rid of the edit button and just show the window length selection.

I had had it expanded by default before, but @joel-jeremy had asked that I make it collapsed by default. Is there a different style that might work/look better @youngcw?

**Comment by youngcw** [comment]
Hmm.  Maybe if the setting was a bit smaller.  Right now its pretty big and obvious so making it smaller would make it not matter as much.  Maybe something similar to the "new custom report" button on the reports page in terms of size.

**Comment by SamBobBarnes** [comment]
> Hmm. Maybe if the setting was a bit smaller. Right now its pretty big and obvious so making it smaller would make it not matter as much. Maybe something similar to the "new custom report" button on the reports page in terms of size.

@youngcw I updated it to use the same button. Not sure about how to inform the user of the current setting. What I have might be a bit crude. Lmk what you think!

**Comment by youngcw** [comment]
Hey, thats pretty good for the button.

**Review by youngcw — DISMISSED** [review]
@joel-jeremy Do you want to add anything before I merge this?

**Comment by Teprifer** [comment]
> The only thing lacking from this enhancement, that I couldn't work out how to implement, was longer periods (eg 2-3 mo) because I couldn't work out how to show more than just the next instance of a scheduled transaction. This may also be an issue if a user has scheduled transactions that should occur more than once per visible period.

@youngcw  I think we'll get a lot of bug reports around this particular aspect, I think that could be OK as a separate PR (by anyone) later on, but I do think it'd be best if the edit period text also made note of this, e.g. "Only the first occurrence of each schedule will display." thoughts?

image

**Comment by youngcw** [comment]
Editing the text to say that would be fine now.

**Review by youngcw — APPROVED** [review]

**Comment by SamBobBarnes** [comment]
@youngcw ill make a pr to add that text this weekend. Been busy the last couple days with a hackathon. Thanks for taking care of this tho!

**Pull request merged**
