### PR TITLE
:fire:  removal of react-native mobile apps

### PR DESCRIPTION
**Pull request by MatissJanis**
This is the initial PR to remove the mobile-app codebase. There's still loads of react-native code that we'll need to slowly remove over time. But at least this removes the bulk of the legacy functionality.

The code will still be accessible here in an archive format: https://github.com/actualbudget/actual-mobile-archive

### CODE REVIEW

**Comment by j-f1** [comment]
Can you also rename the icon files from `*.web.js` to `*.js`?

**Comment by MatissJanis** [comment]
> Can you also rename any remaining files from `*.web.js` to `*.js`?

I think that makes sense. But lets do that in a follow-up PR, ok? This one already has ~600 modified files 😅

**Comment by rich-howell** [comment]
Does this PR mean this PR https://github.com/actualbudget/actual/pull/211 will be redundant?

**Comment by MatissJanis** [comment]
> Does this PR mean these PR's;
> 
> #45 #211
> 
> Will be redundant?

No. Electron = desktop version. We still have that though it hasn't been working for ages. I'll need to work on making the build process work for it sometime later.

**Comment by jlongster** [comment]
> No. Electron = desktop version. We still have that though it hasn't been working for ages. I'll need to work on making the build process work for it sometime later.

fwiw this isn't true. I use the electron app for all development because it's much better (you can hot reload the server etc). It runs last I tried it which was a few weeks ago.

The only current issue is the current version number (`22.12.03`). The `03` part is technically not valid semver and part of the electron toolchain is complaining about that. Once the number changes to be valid (and we make sure we don't use that again) it'll work fine.

Just do:

```
yarn rebuild-electron
yarn start
```

From the root and it should run!

**Comment by jlongster** [comment]
> Can you also rename any remaining files from *.web.js to *.js?

If you want to support the API you cannot do that. The platform layer has different implementations for some of those modules for the API bundle.

**Review by jlongster — APPROVED** [review]
Thanks for doing this!

btw it looks like in here you deleted all the `v1` icons? Are you sure those aren't used anywhere in the desktop/browser app? I thought there were still a few imported.

Approving!

**Comment by j-f1** [comment]
> If you want to support the API you cannot do that. The platform layer has different implementations for some of those modules for the API bundle.

I was mostly thinking about cases where there were web/mobile or web/iOS/android variants (like for the icons), those extensions can be removed, right?

**Comment by jlongster** [comment]
That's true! yes there are likely several things that could be renamed back to just `.js` now :)

**Comment by MatissJanis** [comment]
> > No. Electron = desktop version. We still have that though it hasn't been working for ages. I'll need to work on making the build process work for it sometime later.
> 
> fwiw this isn't true. I use the electron app for all development because it's much better (you can hot reload the server etc). It runs last I tried it which was a few weeks ago.
> 
> The only current issue is the current version number (`22.12.03`). The `03` part is technically not valid semver and part of the electron toolchain is complaining about that. Once the number changes to be valid (and we make sure we don't use that again) it'll work fine.
> 
> Just do:
> 
> ```
> yarn rebuild-electron
> yarn start
> ```
> 
> From the root and it should run!

So the version is the root cause for electron builds currently not working? Interesting

https://github.com/actualbudget/actual/actions/runs/3897219375/jobs/6654657350

**Comment by j-f1** [comment]
That looks like it’s trying to run a shell script as JS for some reason.

**Comment by jlongster** [comment]
@MatissJanis that is likely, yeah. pretty I used it a few weeks ago and had to manually tweak that version locally to get it running, but once I did it ran! The biggest blocker for officially supporting it is deploying electron is really annoying

**Comment by jlongster** [comment]
I was on mobile so I didn't look at the CI output. yes you're right @j-f1 that is something different. Getting it to run in CI falls under the "deploying electron" umbrella which is annoying; I'm not surprised it's failing in CI. There's some work there to make it work in the CI env.

**Comment by MatissJanis** [comment]
> Thanks for doing this!
> 
> btw it looks like in here you deleted all the `v1` icons? Are you sure those aren't used anywhere in the desktop/browser app? I thought there were still a few imported.
> 
> Approving!

Missed this comment.

The PR deletes all `*.mobile.js` v1 icons. `*.web.js` icons remain unchanged.

**Pull request merged**
