### PR TITLE
[WIP] Make the width of categories column in the budget view customizable

### PR DESCRIPTION
**Pull request by EvidentlyCube**
## Background

It's the smallest deal breaker I ever had but after imported my nYNAB budgets I have a lot of categories which names don't fit in the available space on the budget view and in a lot of cases I can't shorten them and keep them meaningful enough for my needs:

image

## What I've done

**A new "Display" section in configuration** - it supports values from 100 to 1024 (arbitrarily selected), gracefully handles incorrect input (resets to original value).
image

It should properly handle most UI elements (I've tried to find all the places that hardcoded the old width of 200 px):
image

## Notes:

* This is my first PR and I haven't even properly started using the application yet so there might be things I've missed
* I wasn't exactly sure how to best handle not updating the pref with text values so used a temp variable and only actually update the setting on blur
* I wasn't sure if local pref is the best place for this
* I personally find this level of customization to lay somewhere between "basic" and "advanced" but I opted for the default settings because it seemed to fit neatly with theme and formatting

Finally, this does go a bit against the design strategy:

> The goal of the UI is to be minimalistic [...] We are against adding a button/user setting for every little piece of UI (sizes, paddings, margins, etc.)

But at the same time the default 200 is awfully small, especially with upcoming i18n as many languages are much **wider** than English.

### CODE REVIEW

**Comment by EvidentlyCube** [comment]
At the moment two VRT tests are failing.

`settings.test.js:29:7 › Settings › checks the page visuals` is expected as the settings has a new section in this PR

`mobile.test.js:140:7 › Mobile › checks that settings page can be opened` I think this one is also caused by a new section being added causing a slight shift in the text:

image

**Comment by youngcw** [comment]
If the changes are expected then update the snapshots as part of the PR

**Comment by EvidentlyCube** [comment]
@youngcw Thanks, I'll see what I can do! I am on Linux and so almost every VRT test fails due to a lot of tiny differences in font rendering, so I'll need to have some fun with getting development env up on my TV PC.

**Comment by youngcw** [comment]
They get updated in docker for consistency.  The package readme shows the process

**Comment by EvidentlyCube** [comment]
> They get updated in docker for consistency. The package readme shows the process

Ugh, I noticed docker and my brain immediately went "nah, I am good". Thanks, updated and checks are passing!

## Things I am least confident about:

1. 200 as the default value is hardcoded everywhere. It's no different from the number being hardcoded in the styles before but I am generally not too fond of it, especially that things depend on it being the same.
2. I feel like there should be a way to force a default value for a local pref but I failed to find anything. It'd save the code from doing `= 200` everywhere `useLocalPref()` happens.
3. "Should this be in settings or somewhere else" is probably the biggest question. An ideal scenario would most likely be a way to drag the edge of the column and resize it with the mouse but that's not something I am willing to attempt unless I'll know it's something that would be accepted as a solution.

Otherwise I tried to mimic the code as best I could. It's the biggest React codebase I see and it's very intimidating to look at.

**Comment by jfdoming** [comment]
> > They get updated in docker for consistency. The package readme shows the process
> 
> Ugh, I noticed docker and my brain immediately went "nah, I am good". Thanks, updated and checks are passing!
> 
> ## Things I am least confident about:
> 1. 200 as the default value is hardcoded everywhere. It's no different from the number being hardcoded in the styles before but I am generally not too fond of it, especially that things depend on it being the same.
> 2. I feel like there should be a way to force a default value for a local pref but I failed to find anything. It'd save the code from doing `= 200` everywhere `useLocalPref()` happens.
> 3. "Should this be in settings or somewhere else" is probably the biggest question. An ideal scenario would most likely be a way to drag the edge of the column and resize it with the mouse but that's not something I am willing to attempt unless I'll know it's something that would be accepted as a solution.
> 
> Otherwise I tried to mimic the code as best I could. It's the biggest React codebase I see and it's very intimidating to look at.

I do think there's #3309 which might attempt mouse resize as well

**Comment by EvidentlyCube** [comment]
> I do think there's https://github.com/actualbudget/actual/pull/3309 which might attempt mouse resize as well

It does mouse resize indeed. Then there's a reason to get back to this PR once the other one is merged and rewrite it to use mouse instead.

**Comment by Jonathan-Fang** [comment]
Rewrite using the mouse to drag the edge or the column sounds like a great idea! It can help fill the whitespace on 1920x1080 monitors too.

**Pull request closed without merging**
