### PR TITLE
darkMode Fixes

### LINKED ISSUE #1763: [Bug]: Dark Mode upcoming schedules muted
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

In light mode upcoming schedules are highlighted in the schedules screen

image

However in dark mode they are muted 

image

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by carkom**
Fixes issue with server status in titlebar and upcoming for schedules.

Fixes #1763

### CODE REVIEW

**Comment by carkom** [comment]
Also fixes #1761

**Comment by carkom** [comment]
fixes #1761

**Review by joel-jeremy — APPROVED** [review]
Looks good!

**Comment by carkom** [comment]
fixed #1761

**Pull request merged**
