### PR TITLE
Fix ofx/qfx import options

### PR DESCRIPTION
**Pull request by joel-jeremy**
Fix QFX import errors reported in version 23.9.0.

### CODE REVIEW

**Comment by MatissJanis** [comment]
Do you have an example QFX file for reproduction?

**Comment by joel-jeremy** [comment]
A sample file was provided in Discord: https://discord.com/channels/937901803608096828/1148022803224858726

**Comment by MatissJanis** [comment]
Attaching the file for future reference in github.

[268573_0000653667-S0045ofxdl.qfx.zip](https://github.com/actualbudget/actual/files/12515315/268573_0000653667-S0045ofxdl.qfx.zip)

**Comment by MatissJanis** [comment]
Screenshot 2023-09-04 at 17 33 11

importing the above file on the netlify preview still causes a crash. But I think that might be a different problem.. 

```safeNumber: can’t safely perform arithmetic with number: -20230831000050717000```

**Comment by MatissJanis** [comment]
I'm actually unable to reproduce the original issue on `demo.actualbudget.org` with the given file. Are you able to repro?

**Comment by MatissJanis** [comment]
demo is similar to edge. It auto-deploys the latest `master` branch. But multiple times per day.

I'm confused. If the issue is already solved on `master` branch - is this PR just code quality improvements? That's also fine; I just want to understand how to review this PR.

**Comment by joel-jeremy** [comment]
If you run v23.9.0, you should be able to replicate the issue. This PR to enable the fallback option for both ofx and qfx because right now the fallback option is not showing up for qfx imports.

**Review by MatissJanis — APPROVED** [review]

**Pull request merged**
