### PR TITLE
Update loot-core to webpack 5

### PR DESCRIPTION
**Pull request by j-f1**
~based on #1114~

This brings its build process up to date with the rest of the project. We can now use Node 20 to build successfully.

Closes #918

### CODE REVIEW

**Comment by MatissJanis** [comment]
Wait, what???

Before: bundle.api.js  2.73 MiB

After: bundle.api.js 1.8 MiB

Wow!

**Review by MatissJanis — APPROVED** [review]

**Comment by j-f1** [comment]
Probably a result of removing a bunch of native Node modules that were previously poly filled. I did notice that I didn’t check if the zip functionality still works, so will need to do that.

**Comment by MatissJanis** [comment]
Should we also close https://github.com/actualbudget/actual/pull/918 after this is merged?

**Comment by j-f1** [comment]
I think that makes sense for now, and we can re-evaluate later. The next FF release will include module worker support so we might be able to pick that back up with module-based imports??

**Comment by j-f1** [comment]
Also realized I need to remove the polyfills for the API package since that should be using the real Node.js builtins.

**Review by MatissJanis — APPROVED** [review]

**Pull request merged**
