### PR TITLE
Fixed a bug where it was possible to make a transfer to the same account as the one making the transfer.

### PR DESCRIPTION
**Pull request by Miodec**
The payee autocomplete was always using cached accounts. Added a check to see if accounts was already passed in as a parameter - only using cached if it wasnt.

### CODE REVIEW

**Comment by j-f1** [comment]
It looks like you have some failing tests?

**Comment by Miodec** [comment]
I can't really figure out why the test is failing - any help would be appreciated.

**Review by tjfinlinson — COMMENTED** [review]
Looks good from my point of view. When creating a transfer, if typing in the name of the account you are already in, the account no longer shows up like it currently does. This seems like a nice user enhancement.

**Comment by MatissJanis** [comment]
👋 Would you mind giving me a step-by-step instructions how to reproduce the issue so I could test it?

Thanks!

**Review by MatissJanis — APPROVED** [review]
Amazing! Thanks for your contribution!

(I'll leave this PR open for a few more days in case any other maintainer wants to review)

**Pull request merged**
