### PR TITLE
Include split transactions in “Linked transactions”

### PR DESCRIPTION
**Pull request by j-f1**
Previously, a child transaction of a split transaction was not shown in the list of linked transactions when editing a schedule.

Now, it is shown along the other transactions. I think it could be nice to have some sort of indicator that the transaction is part of a split transaction but that isn’t crucial IMO

### CODE REVIEW

**Comment by MatissJanis** [comment]
How do I reproduce the issue?

**Comment by j-f1** [comment]
Link a child of a split transaction to a schedule, then open that schedule in the schedule editor. It won’t show up in the list of transactions in the released version.

**Comment by MatissJanis** [comment]
Should we even allow linking a child transaction to a schedule? I can't imagine how this would work. How can a child transaction be added to a schedule, but not the parent?

**Comment by MatissJanis** [comment]
Hmm.. something there seems very broken. I don't think child transactions should be link-able to schedules as there is no way for a schedule to create ONLY a child transaction without a parent.

**Comment by j-f1** [comment]
It wouldn’t be automatically created, but you could set up a rule or manually link the transactions

**Comment by rich-howell** [comment]
@j-f1 I am not sure how this would work in practice, other than your single use case how would this be useful in day to day budgeting, why would it be required or needed. Why would there be a split transaction that works in the way your suggesting. 

Seems to me that it is a bit "messy"

**Comment by j-f1** [comment]
I don’t think it is a common use case, but I would like such transactions to show up properly in the list. I agree that it would be uncommon, but why is that necessarily bad or messy?

**Comment by rich-howell** [comment]
> I don’t think it is a common use case, but I would like such transactions to show up properly in the list. I agree that it would be uncommon, but why is that necessarily bad or messy?

I am trying to understand what we are asking for here. Can you make a GIF?

**Comment by j-f1** [comment]
Transaction:
Screenshot_2023-02-14 14 53 02

<details><summary>Current behavior:</summary>
Screenshot_2023-02-14 14 52 46
</details>
<details><summary>New behavior:</summary>
Screenshot_2023-02-14 14 54 48
</details>

**Review by MatissJanis — CHANGES_REQUESTED** [review]
Sorry to be the bummer, but I think both me and Rich are in agreement here that child transactions should not be allowed to be linked to schedules.

(correct me if I'm reading you wrong Rich)

**Comment by j-f1** [comment]
I don’t understand why this is harmful? Can you explain more?

**Comment by rich-howell** [comment]
> I don’t understand why this is harmful? Can you explain more?

I am really failing to see the use case here, your screenshots dont really demonstrate how it would be functionaly in the app itself. Did I say harmful? If I did, I didn't mean harmful but it seems it might some ambiguty to the feature unless we are clear on how this should/would work.

**Comment by j-f1** [comment]
> I am really failing to see the use case here, your screenshots dont really demonstrate how it would be functionaly in the app itself.

Sorry, I tried to be descriptive there but clearly there’s something I’m not communicating well enough. My rationale is that you can already link the children of a split transaction to a schedule (in the released version of Actual), but it does not show up in the list of currently linked transactions in the schedule editor UI. This PR just makes it possible to see such transactions in that UI.

It’s kind of hard to make a GIF because I’d have to demonstrate the issue across 2 different versions of Actual (and the auto-generated test budget is subtly random)

> Did I say harmful? If I did, I didn't mean harmful but it seems it might some ambiguty to the feature unless we are clear on how this should/would work.

I didn’t see anyone say “harmful” before me but I’m confused why this change would not be accepted so I assumed it was because you were seeing some negative aspect to the change.

**Comment by j-f1** [comment]
Closing this out for now since we aren’t able to reach an agreement on what the correct behavior here is at the moment.

**Pull request closed without merging**
