### PR TITLE
Add rule actions to prepend/append to transaction notes.

### LINKED ISSUE #3197: [Feature] Enable rule to Append text to note instead of Set
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It would be useful to be able to create a 'Post' rule which you could choose to append extra text to the Notes filed rather than Set text which overwrites anything existing.

Example Usecase:  I have rules which identify retailers / transactions and label them, categorise, set notes accordingly.  My partner has a joint credit card on my account.  I want to be able to tag these transactions in the notes column with tag eg: #PartnerSpend.  She may shop at the same stores as me so the categories, shop rename rules are still valid.  If I set a Post rule currently it will overwrite any notes that might get set as part of these rules.

### Describe your ideal solution to this problem

Drop down option in the Rules UI to swap between 'set' (defeault) to 'append' option when creating or editing a rule.

### Teaching and learning

Using the 'i' button next to it to explain usage.

### PR DESCRIPTION
**Pull request by psybers**
Fixes #3197.

Also allows for prepending to notes.

image

### CODE REVIEW

**Comment by youngcw** [comment]
Cool! Can you add in the prepend option too?

**Comment by psybers** [comment]
> Cool! Can you add in the prepend option too?

@youngcw done.

**Comment by youngcw** [comment]
the option to append doesn't seem to work when I do a manual entry test

**Comment by youngcw** [comment]
wrong button sorry

**Comment by psybers** [comment]
> the option to append doesn't seem to work when I do a manual entry test

Can you give me specific steps? It seems to work for me... though I did find a bug while trying to reproduce your issue:

image

It put 'undefined' in there. Oops.

**Review by joel-jeremy — APPROVED** [review]
Code LGTM! One thing I noticed is that it doesn't append/prepend when a note is already entered beforehand?

**Comment by psybers** [comment]
> Code LGTM! One thing I noticed is when entering a new transaction, the rule doesn't append/prepend when a note is already entered beforehand.

@youngcw Is that what you were referring to?  I was testing with an empty note, and it worked.

I think this isn't an issue with *this* PR though. That is just the behavior of the rules: they won't apply while entering in a transaction if the field is already populated.  Otherwise, it might be impossible to change things as the rules will keep re-applying.

**Comment by youngcw** [comment]
thats maybe it.  I think I was adding in a small note as I was entering a test transaction.

**Review by matt-fidd — APPROVED** [review]

**Pull request merged**
