### PR TITLE
Make RN app work

### PR DESCRIPTION
**Pull request by 7brend7**
Fixed issues for successful run of ReactNative app.

! Tested only for android !

### CODE REVIEW

**Comment by vivekmiyani** [comment]
@7brend7 Will it work with actual-server selfhosting?

**Comment by 7brend7** [comment]
@vivekmiyani - yes, moreover it will work only with selfhosted actual server;
I’ve added views to enter server url and password  in the similar way as in desktop-client;

**Comment by vivekmiyani** [comment]
@7brend7 Just wondering how `subscribe-sign-in` route working (As I saw there is only `/login` route on the actual-server) 😕

**Comment by MatissJanis** [comment]
:wave: Thanks for the contribution.

Sadly mobile app is no longer supported here. We'll be deleting it from the main repository with the next release.

However, we will have a responsive mobile app **very soon** (next release). So keep an eye out for that!

**Pull request closed without merging**
