### PR TITLE
prune: remove unused icons

### PR DESCRIPTION
**Pull request by MatissJanis**
Removing unused icons and adding `eslint-ignore` rule to the remaining.

### CODE REVIEW

**Comment by j-f1** [comment]
IMO we should keep the icons since they may be useful in the future — maybe add an ignore to the entire folder for now?

**Comment by jlongster** [comment]
This looks great! svgs definitely went through some evolution and need some cleanup. Some context: the svgs in the root `svg` folder are very old (and can be deleted if not used). The svgs in `v1` are an assortment from various places. A few of them are still used throughout the app. The svgs in `v2` are all icons from https://www.streamlinehq.com (actually, a subset of them I believe). I'd keep around icons in `v2` even if we don't use them because they are meant to be a readily available set if icons, so you can import them and use them (even if we aren't using them yet). That was my plan at least.

The `generate` script is also old and `generate-new` is the one that is used to convert svgs to React components.

And I agree with @j-f1: was gonna suggest just ignoring the whole folder. These are generated files that don't need to be linted.

But this cleanup is AWESOME. definitely a messy area!

**Comment by MatissJanis** [comment]
This PR doesn't touch v1 or v2 icons btw. Only the legacy ones that are unused.

A PR approval ✅ would be appreciated if you think this is good-to-go.

**Comment by jlongster** [comment]
Yeah, this PR looks good for that reason :) just giving some context when I see stuff! I'm in a rush right now so haven't actually looked to closely to r+ but it should be fine

**Review by jlongster — APPROVED** [review]
looks good to me, thanks for the cleanup!

**Pull request merged**
