### PR TITLE
Fix suggested payee issues #3317 #3316

### PR DESCRIPTION
**Pull request by qedi-r**
Fix issue #3317 by adding tombstone filter to common payee query.

### CODE REVIEW

**Comment by psybers** [comment]
Did something not get committed?  The diff contains no string `tombstone` in it anywhere.

**Comment by qedi-r** [comment]
Yep, I merging both clobbered the tombstone line. I've re-added it.

**Comment by qedi-r** [comment]
Added a couple of tests for the bugfixes.

**Comment by MatissJanis** [comment]
cc @psybers would you please mind verifying if this patch fixes the linked bug issues?

**Comment by psybers** [comment]
@MatissJanis yes, it fixed both reported bugs. But introduced a new bug.  Favorites used to be sorted to the top of the suggestions, now they are not:

image

**Comment by qedi-r** [comment]
I'm not sure it did sort favourites first, common second in the list - it sorted them with localeCompare before display, and that has not changed.

**Comment by qedi-r** [comment]
If we like that better, where favorites are at the top, I can add that though. I'll do it in a new bug, though.

**Comment by psybers** [comment]
Don't include that here.  It was just an artifact of the specific payees I selected while testing.  The existing behavior does not sort.

**Comment by qedi-r** [comment]
Yep. To clarify: is this additional sorting desired behavior? I'm uncertain it is. Should I open a new bug for that?

**Comment by psybers** [comment]
You can open an issue. I would upvote it.  I desire that behavior. ;-)

**Comment by MatissJanis** [comment]
My 2cents: agreed that favorites should be at the top. If they are not there - what purpose do they serve? Just an icon besides them? That's not really rhat useful. But putting them at the top if the list: definitely useful.

**Review by matt-fidd — APPROVED** [review]
Change looks good to me! Thanks for the fix

**Review by MatissJanis — APPROVED** [review]

**Pull request merged**
