### PR TITLE
a11y: update cleared state display for clarity

### PR DESCRIPTION
**Pull request by rickdoesdev**
Create new CircleEmpty svg and set uncleared state to use new icon.

Add 'cursor: pointer' to the cleared field to aid in action awareness.

See discussion https://github.com/actualbudget/actual/discussions/271 for initial thoughts around the problem and the solution.

Uncleared transactions have a hollow circle.
Cleared transactions maintain the existing filled background checkmark.
cleared field now gains a pointer on hover to show interactivity option

See image of this solution. 
image

Mobile application is unchanged. Given the direction seems to be deprecating the mobile app, I assumed I could skip changing there. Please let me know if I should update it anyway, or if there are any other issues!

### CODE REVIEW

**Comment by rickdoesdev** [comment]
There was as well an alternative design that maybe worth considering still. Included here, and easily updated in the PR if desire is to shift to it.

image

**Comment by trevdor** [comment]
Thanks, @rickdoesdev!

To me, the 3 dots feels like an action menu. As though I'd expect a menu to pop up when I click it. 
So of the two, I prefer your open circle. 

However, one concern (cuz I toyed with open circles, too): the gray circle-checkmark today contains a visual clue what clicking the icon will do. It's a little vague--but does suggest reconcile/clear/something along those lines. We lose that with an open circle. 

A couple ways I can think to get that visual info back:
1) use an alternative with more intuitive meaning
2) place a "C" or :checkmark: in the column header - putting the clue at top instead of in every row

Whaddya think? 

(And of course, @jlongster will probably have opinions, being a design systems guy...)

**Comment by rickdoesdev** [comment]
@trevdor Let's go with faded check then. Updated PR

image

**Comment by jlongster** [comment]
This is a complicated column as you say; scheduled transactions show different states. And we probably want a "locked" status on transactions at some point (people have asked for that a bunch) which will show something different.

It's really just a "status" column. We could explain this better with tooltips or something on the header and figure out the right icon to put in the header.

For now, I think at least changing the colors like the latest screenshot looks great @rickdoesdev. We can always iterate. Thanks a lot!

**Comment by rickdoesdev** [comment]
Thanks @jlongster!
Have just rebased the branch to git rid of the junk commit that added unused assets that were immediately deleted; I'll need you tick the workflow approval for me again thanks!

**Comment by trevdor** [comment]
@rich-howell I think we can remove `waiting-review` from this one. James gave it a 👍🏻 and I'd vote it's merge-ready, too.

**Pull request merged**
