### PR TITLE
Add support for customizing schedule names

### PR DESCRIPTION
**Pull request by j-f1**
This renames the “Payee” column of the schedule editor to “Name” and allows overriding the payee with a custom name. This is useful if you want to track several subscriptions payable to the same account (for example, I have several subscriptions paid via Apple for different apps, but want to label them with the actual recipient of the funds).

Are there any places I’m missing where we call out a schedule name that need to be updated too?

An open design question is where exactly the text field should be placed — I don’t really like either of these implementations:

Screenshot_2022-10-07 15 39 09
Screenshot_2022-10-07 15 45 44

### CODE REVIEW

**Comment by rich-howell** [comment]
@j-f1 Would this be better placed in the `notes` which is used in other areas of Actual already? I am not sure renaming the Payee is the best option, in your Example if I have 5 subscriptions through Apple what shows up on my bank statement? Is it Apple or is it the App name that the subscription resides? 

If it is the former I think the payee should remain as Apple with a note for the App name. 

If a note section was added, the paper note icon could be added to the end of `Payee` or somewhere close to the `Payee` label and remove the `Custom Name` field all together.

**Comment by j-f1** [comment]
> in your Example if I have 5 subscriptions through Apple what shows up on my bank statement? Is it Apple or is it the App name that the subscription resides?

It would still be Apple, and the payee would continue to show up as Apple, this just changes what’s displayed in the schedule list. What’s important to me is that some sort of distinguishing name shows up in the list (since I have 6 right now that would otherwise be difficult to tell apart).

That said, I think it would make sense to store this as a note field on the underlying rule, so that it would be automatically added to the corresponding transactions. In fact that’s what I’ve been manually doing already so it would be good to have it as a built in feature.

**Comment by j-f1** [comment]
An update on this: I looked into storing it on the action, but it turns out to be a bit complicated since there aren’t any other schedule features that manipulate the actions of the associated rule. I would appreciate any input/assistance/advice folks have on pushing this forward.

**Comment by rich-howell** [comment]
@j-f1 I have dropped the waiting-review tag from this one and replaced it with help-wanted...hope this helps.

**Comment by tjfinlinson** [comment]
@j-f1 

I have encountered this issue, it's seems like it's mostly a display issue as you can add the notes and specifics to the scheduled transaction. It does get confusing though when you have several transactions with the same Payee, but different amounts, but you can't see specifics about them in the scheduler screen. I'll try and see if I can at the very least help brainstorm ideas on this. I think it would be a nice little improvement to the scheduled section.

**Comment by MatissJanis** [comment]
👋 Just wanted to check-in here - what's the status?

We have a few feature requests to add the "notes" field to scheduled transactions (which makes sense). This would be a nice addition.

**Comment by j-f1** [comment]
The status is that I’ve figured out how to persist the schedule name (it should go onto an action in the underlying rule that sets the “notes” field of matched transactions). However, I wasn’t able to figure out how to make that work, since none of the other features of the schedule UI mess around with the actions. Also, the UI (as shown in the OP) needs improvement, since there isn’t a good place in the current layout to stuff another field into the schedule editor.

I’m gonna close this PR because I think the actual code changes to fix the issue are substantially different enough to warrant a new PR.

**Pull request closed without merging**
