### PR TITLE
:bug: (darkmode) fix transaction list hover effects

### LINKED ISSUE #1498: [Bug]: transaction table hover effect missing
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

We used to highlight the hovered row in transaction table. This seems to have been accidentally removed with the darkmode PRs. It should be brought back.

### What error did you receive?

_No response_

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

_No response_

### Operating System

None

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #1498

Fixing the transaction table hover effects. Also removing `animation` code as this does not seem to be working anymore (and hasn't been working for a while..). So I think it's worthwhile to clean it up to reduce the complexity in the transaction table.

### CODE REVIEW

**Review by shall0pass — CHANGES_REQUESTED** [review]
What's going on here?
image

I don't see this in demo.actualbudget.org

**Comment by MatissJanis** [comment]
Good spot @shall0pass! This has now been fixed along with some other table-header color regressions.

**Comment by youngcw** [comment]
Are you seeing this one? Missing shading on the budgeted column.
Screenshot from 2023-08-16 09-57-18

**Review by shall0pass — APPROVED** [review]
It looks great to me!

**Comment by carkom** [comment]
Table header background is being used as navy50 in tons of other places. Changing it here is likely going to mess up colors in many other parts of the app. The better way to do it is using table background in any places you want a white background. OR make an alttableheader background for your specific use.

Problem is consistency. You change it here cuz the header is white but a different table header else where is gray and you can't have both using the same const.

**Comment by MatissJanis** [comment]
Where do we want it to be gray @carkom ? I spot checked the most used pages (transactions, schedules, rules, payees) and they all use a white background.

**Comment by carkom** [comment]
Possibly only ones that haven't been merged yet. Check other dark theme PRs. Mobile transactions, importtransactions to name a few.

Also there's no point having a seaparte header and main table background color if they are just the same color. Anywhere that header and table rows have the same background then they should just use the same value.

**Comment by MatissJanis** [comment]
> Possibly only ones that haven't been merged yet. Check other dark theme PRs. Mobile transactions, importtransactions to name a few.

That's fine. I'm not too worried about un-merged darkmode PRs at this point. The main goal here was to fix regressions when comparing against v23.8.1 (in which all the tables I could spot-check used white background).

> Also there's no point having a seaparte header and main table background color if they are just the same color. Anywhere that header and table rows have the same background then they should just use the same value.

Agreed. My primary goal in this PR was not to improve the code quality, but to fix regressions in order to unblock next months release. If you'd like to improve the code quality here - that would be much appreciated.

**Pull request merged**
