### PR TITLE
Fix Electron Build

### PR DESCRIPTION
**Pull request by Shazib**
Some of the theme switching stuff has broken electron, at least on Windows builds.

This resolves that issue.

Dark mode still works in the netlify preview, and I haven't changed anything at all front-end wise, so I'm not sure why the visual regression tests have failed.

### CODE REVIEW

**Comment by MatissJanis** [comment]
Try updating your changes with latest `master`. That _might_ fix the VRT job.

**Comment by MatissJanis** [comment]
Looks like it didn't help. There must be some sort of change that affects them from this PR.

**Comment by MikesGlitch** [comment]
If you look at the test: "budget-Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-chromium"

You can see it expects dark theme but gets light theme. Maybe if you fix that issue the others will be fixed?

**Comment by Shazib** [comment]
> If you look at the test: "budget-Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-chromium"
> 
> You can see it expects dark theme but gets light theme. Maybe if you fix that issue the others will be fixed?
> 
> the theme switch happens in [playwright.config.js](https://github.com/actualbudget/actual/blob/master/packages/desktop-client/playwright.config.js#L27C61-L27C61). It's to do with the window.Actual.setTheme("dark") not working anymore

Thanks for the info, i'll dig into it a bit.

The loading of the theme seems to happen fine in the netlify preview, i've compared it to other older PR's and it seems to be in a similar time.

Do you know if the tests run against the netlify instance?

**Comment by MikesGlitch** [comment]
> > ") not working anymore
> 
> Thanks for the info, i'll dig into it a bit.

If you click the demo link and run this in the console

```
window.Actual.setTheme("dark") 
```

It should toggle it to dark. Or "light" will put it to light. That's broken the web demo - I'm assuming cause you removed it from the globals file.

**Comment by Shazib** [comment]
> It should toggle it to dark. Or "light" will put it to light. That's broken the web demo - I'm assuming cause you removed it from the globals file.
> 
> I think the initialisation might be fine, but the VRT tests toggle it from light to dark with that setTheme call to check against the screenshots.

Interesting, thanks! That gives me a thread to follow. I was going off the fact that the toggle button in the corner still works in the web version. 
I didn't remove `setTheme` entirely though, i just moved it to the preload file.

Anyway digging into it now, thanks for the guidance!

**Comment by Shazib** [comment]
@MikesGlitch  Thanks, Fixed!

**Review by MatissJanis — APPROVED** [review]
Thanks @Shazib ! <3

**Comment by MatissJanis** [comment]
And also thanks @MikesGlitch for the assist!

**Pull request merged**
