### PR TITLE
[Mobile] Collapsible budget groups

### PR DESCRIPTION
**Pull request by joel-jeremy**
Open to feedback whether this is a good idea or not. Another option would be to put the "collapse"/"uncollapse" button on the category group modal to retain more space for the category group name.

### CODE REVIEW

**Comment by MatissJanis** [comment]
Not quite sure what's going on here. But at some random intervals the page keeps jumping around. 🤔 

https://github.com/actualbudget/actual/assets/886567/d488f61e-9342-4843-83a6-9779d6ddda96

**Comment by joel-jeremy** [comment]
That's odd, I can't seem to replicate it. I'm using Chrome/Brave (both desktop and mobile).

**Comment by youngcw** [comment]
Im fine with how this is.  A possible way to help the lack of space issue is to increase the screen size that causes the balance/spent columns to combine.

**Comment by MatissJanis** [comment]
Managed to reproduce (also on demo app):

1. click anywhere on the page
2. DO RELEASE THE CLICK
3. drag down
4. you will jump to the very top of the page

If this happens sufficiently quickly - it looks like the entire page is jumping (the video I sent earlier).

**Review by MatissJanis — APPROVED** [review]

**Comment by joel-jeremy** [comment]
> Im fine with how this is. A possible way to help the lack of space issue is to increase the screen size that causes the budgeted/spent columns to combine. That would give more space to the group name on more screens. For example the VRT shows more of the name than my small screen phone because the vrt only shows balance and spent columns while my phone shows all 3.

This is one option and I wouldn't be against making such a change. For now, I would like to merge this and get some feedback first. If people start having issues then we could consider doing this suggestion.

> Managed to reproduce (also on demo app):

Something else might be causing the issue if it also happens on the demo app. Merging this for now. :)

**Comment by MatissJanis** [comment]
> Something else might be causing the issue if it also happens on the demo app. Merging this for now. :)

Totally! If it's one demo - it's not the fault of this pr.

**Pull request merged**
