### PR TITLE
Fix infinite loop in repeat goal

### PR DESCRIPTION
**Pull request by youngcw**
I believe I found the infinite loop problem in the repeat goal.  

This doesn't mess things up if you are budgeting the same month that the goal starts, that's probably why we didn't see it before.

Side note:  The logic always starts at the start date in the template, then increments until falling in the right month window.  If this template gets used for, say, a few years, it will start to bog down the processing.  If someone has a good quick fix I can add that.

### CODE REVIEW

**Comment by shall0pass** [comment]
This test template now works properly with this PR: #template $10 repeat every 2 weeks starting 2022-01-04

Unfortunately https://github.com/actualbudget/actual/issues/983 will remain open.

**Comment by shall0pass** [comment]
I'm having a bit of trouble putting a code comment where I want, so I'll do my best to explain it here.

At line 535, would you consider inserting
`next_date = addMinutes(next_date, next_date.getTimezoneOffset());`
after the addDays() function?

This cures the schedule loop for me.  However, I only know how to test it in my current timezone.  
image
These are the dates I see in the debugger before next_date decides to go to Jun 29 at the top of the loop.  The timezoneoffset is the minimum amount of time I've found that resolves the loop here.

**Comment by j-f1** [comment]
Is this ready to merge or do you still want to fix @shall0pass’s comment first?

**Comment by shall0pass** [comment]
> Is this ready to merge or do you still want to fix @shall0pass’s comment first?

I put a fix for the schedule in another PR so this one could be accepted quicker.

**Review by j-f1 — APPROVED** [review]

**Comment by j-f1** [comment]
Thank you for fixing!

**Pull request merged**
