### PR TITLE
Make transaction list sortable by cleared status

### PR DESCRIPTION
**Pull request by jaarasys-henria**
Make transactions list sortable by cleared status. Makes cleared status column behave like any other column that it makes sense to sort by. Simple implementation with no negatives to mention. Unless  you count the new header text taking up a little more horizontal screen space than the empty header it replaces as a downside.

I tried testing with different screen sizes and ratios in Mozilla Firefox and behavior looked sane to me.

Let me know if there's something I can do to enhance my suggested feature and I'll get it done. I hope I could properly deduce a correct implementation from the surrounding code. React is not my forte :)

### CODE REVIEW

**Comment by youngcw** [comment]
can you use just a "C" or "R" instead of "Cleared" that would not create as much empty space

**Comment by jaarasys-henria** [comment]
> can you use just a "C" or "R" instead of "Cleared" that would not create as much empty space

I considered and tried it, but didn't really like it. It felt a bit unclear IMO. Old YNAB4 has a nice, stylized 'C' letter. Maybe I could retry it and add some formatting to make it look more like a symbol for something instead of just looking too much like a stray letter up there in the column header. That _might_  sway me to love it.

**Comment by youngcw** [comment]
Something as simple as an italicized letter could make it not feel like a bug

**Comment by shall0pass** [comment]
Another thought.  Could the button default to the down position?  Normally when I sort by cleared status, I'm looking for the uncleared items.  Currently I need to click twice to bring those to the top.  I know it doesn't follow the default behavior of the other columns, but it seems like to me it would be more expected.  Thoughts?

**Comment by jaarasys-henria** [comment]
Feedback acknowledged and implemented.
- Needlessly long 'cleared' text is now just a '✓', which I feel strikes a nice balance between aesthetics and ease of implementation. I gave it some five px of wiggle room compared to the old values. I read React-stuff from the interwebz and came up with all kinds of convoluted schemes of passing styling via props, but then realized simple things are often the best, removed all of them and  leave ya'll with this simple change :)
- sort order now starts as ascending with falsey checkmarks first.

**Comment by youngcw** [comment]
I like that better

**Comment by youngcw** [comment]
Can you look into why the tests are failing?

**Comment by jaarasys-henria** [comment]
> Can you look into why the tests are failing?

Could there be some issue with PRs from forked repos and the workflow?

I just synced my PR to see how it goes this time, but same result. The `Wait for PR build to succeed` doesn't seem to detect a successful Netflify build of the PR, even though Netlify deployment logs don't seem to indicate any issue with the build step. It seems like it should succeed

It doesn't mark the 'wait for PR build' step as a failure though, even if it times out. Instead it lets the next step run and then we get an error with `no matching workflow run found with any artifacts`. For some reason it can't grab the `build-stats` build artifact. Netlify logs look like it should get created properly and then uploaded at the end of `build.yml `.

Looking at the [Workflow file](https://github.com/actualbudget/actual/actions/runs/7051424155/workflow?pr=1994), I believe it attempts to retrieve a build artifact called `build-stats` but fails to do so.

I wonder why this could be, since the build clearly succeeds and the live preview is online. Based on the [deployment log lines here ](https://app.netlify.com/sites/actualbudget/deploys/6568e48888453c00085372bd#L378) there should be something there for the next stage to enjoy.

[This commit](https://github.com/actualbudget/actual/commit/2108712f2dda986cc48e0fa37558b877905a7879) seems to touch something around those parts.

With no access to testing the Netlify API response and other releated things, I'm not sure what's going on. Any clues where to look next?

**Comment by youngcw** [comment]
At least half of our PRs come from forks, so I doubt its because of that.

**Comment by MatissJanis** [comment]
@youngcw as a maintainer you'll want to manually trigger CI jobs for folks that are first-time contributors in Github. And then also retry the bundle size comparison job.

Screenshot 2023-12-11 at 19 57 29

**Comment by youngcw** [comment]
Looks like its just the VRT that needs updated.  The steps to update the snapshots is here https://github.com/actualbudget/actual/blob/master/packages/desktop-client/README.md#visual-regression

**Comment by jaarasys-henria** [comment]
I think I _did_ see something about approving some workflow stage and it almost rang a bell. But just almost. Cheers for pitching in @MatissJanis! Nice to see this moving forward.

I'll look into the VRT thing later.

**Comment by Jackenmen** [comment]
Hi, I just wanted to let you know that this seems to ignore whether the cleared status is in "locked" state and treats it as cleared:
image

**Comment by jaarasys-henria** [comment]
@Jackenmen I'll look into it! Sry for the silence. Been quite a busy period.

**Comment by jaarasys-henria** [comment]
> Hi, I just wanted to let you know that this seems to ignore whether the cleared status is in "locked" state and treats it as cleared.

Is this more to your liking?

Also, it looks like someone has to push the magic button for the size comparison check like @youngcw or @MatissJanis did earlier.

**Comment by Jackenmen** [comment]
I'm not going to look at the code but the deploy preview works as I would expect it to, yeah!

**Comment by youngcw** [comment]
Nice

**Comment by youngcw** [comment]
I think my only concern at this point is that the column headers are not slightly misaligned from the data with the addition of the check mark.

**Comment by jaarasys-henria** [comment]
I see what you mean. I'll take a look at the alignments tomorrow.

-------- Original Message --------

**Comment by jaarasys-henria** [comment]
> I think my only concern at this point is that the column headers are not slightly misaligned from the data with the addition of the check mark.

This is now addressed as well :+1:

**Comment by youngcw** [comment]
Looks good.  Thanks!

**Review by youngcw — APPROVED** [review]

**Pull request merged**
