### PR TITLE
Add Reconcile button on the account page.

### PR DESCRIPTION
**Pull request by attyluccio**
As mentioned on discord, it is a small quality of life feature that adds the Reconcile button directly on the account page instead of having to go to the menu.

reconcile button

### CODE REVIEW

**Comment by attyluccio** [comment]
> Does the menu still need to have the reconcile option if there is a big button for it now?

I guess not! :) 

I will update code as soon I'm back from work

**Comment by youngcw** [comment]
Seems good to me.  Just need to get the conflicts taken care of.  Could you add in the translation to the button?  It looks like that file was ready for translation, so we need to keep that.

**Comment by jfdoming** [comment]
One quick question, any reason to have a big primary button instead of an icon button? Just thinking that not everyone uses reconciliation, and it fits better with the existing icon buttons. I could imagine a lock-and-key icon, for example?

**Comment by attyluccio** [comment]
> Seems good to me. Just need to get the conflicts taken care of. Could you add in the translation to the button? It looks like that file was ready for translation, so we need to keep that.

I'll edit the translation as soon as possible and check for the conflicts

**Review by youngcw — APPROVED** [review]
Looks good! @jfdoming Anything you would like to add before merging?

**Comment by youngcw** [comment]
Looks like something else is causing conflicts now.  That will need taken care of

**Review by jfdoming — CHANGES_REQUESTED** [review]
Thanks for the icon refactor! Looks pretty good now. However, I noticed that the lock icon button is smaller than the other button right next to it (23x23 vs 26x26), and the icon itself is smaller (13x13 vs 14x14). For visual consistency, mind making them the same?

**Comment by attyluccio** [comment]
> Looks like something else is causing conflicts now. That will need taken care of

I will check what is conflicting...  didn't notice.

**Comment by attyluccio** [comment]
> Thanks for the icon refactor! Looks pretty good now. However, I noticed that the lock icon button is smaller than the other button right next to it (23x23 vs 26x26), and the icon itself is smaller (13x13 vs 14x14). For visual consistency, mind making them the same?

yes will do... sorry for the mistake

**Comment by attyluccio** [comment]
I don't understand what the conflict is... it doesn't say anything. I did merge with master so I don't understand... should I retry the merge?

**Comment by attyluccio** [comment]
merged and fixed icons

**Comment by jfdoming** [comment]
> > Thanks for the icon refactor! Looks pretty good now. However, I noticed that the lock icon button is smaller than the other button right next to it (23x23 vs 26x26), and the icon itself is smaller (13x13 vs 14x14). For visual consistency, mind making them the same?
> 
> yes will do... sorry for the mistake

Absolutely no worries, just trying to make sure the submission is the best it can be! Looks much better now.

One thing I noticed is that the button is visible on the "All accounts" and "For budget" top-level pages, and crashes the app if clicked there. Is there any way we can hide the button on those pages?

**Comment by attyluccio** [comment]
> > > Thanks for the icon refactor! Looks pretty good now. However, I noticed that the lock icon button is smaller than the other button right next to it (23x23 vs 26x26), and the icon itself is smaller (13x13 vs 14x14). For visual consistency, mind making them the same?
> > 
> > 
> > yes will do... sorry for the mistake
> 
> Absolutely no worries, just trying to make sure the submission is the best it can be! Looks much better now.
> 
> One thing I noticed is that the button is visible on the "All accounts" and "For budget" top-level pages, and crashes the app if clicked there. Is there any way we can hide the button on those pages? I think _maybe_ we could just test for the presence of a valid account ID.

sorry for this other mistake! I don't use those pages often and totally missed it. 

now should all be fixed :)

**Comment by jfdoming** [comment]
> > > > Thanks for the icon refactor! Looks pretty good now. However, I noticed that the lock icon button is smaller than the other button right next to it (23x23 vs 26x26), and the icon itself is smaller (13x13 vs 14x14). For visual consistency, mind making them the same?
> > > 
> > > 
> > > yes will do... sorry for the mistake
> > 
> > 
> > Absolutely no worries, just trying to make sure the submission is the best it can be! Looks much better now.
> > One thing I noticed is that the button is visible on the "All accounts" and "For budget" top-level pages, and crashes the app if clicked there. Is there any way we can hide the button on those pages? I think _maybe_ we could just test for the presence of a valid account ID.
> 
> sorry for this other mistake! I don't use those pages often and totally missed it.
> 
> now should all be fixed :)

Looks great now!

**Comment by jfdoming** [comment]
Oh, sorry one other thing I missed 😞 I think we probably want to keep the ordering of the "selected transactions" button right after the search bar, and make sure the padding is consistent. What do you think? Here's what it looks like on edge:
image

But in this PR:
image

**Review by jfdoming — APPROVED** [review]
Great! Looks good to me now, will let @youngcw take a look before we merge

**Review by youngcw — APPROVED** [review]

**Pull request merged**
