### PR TITLE
Remove `node-libofx` package and replace it with `ofx-js`

### PR DESCRIPTION
**Pull request by TomAFrench**
Supercedes #98 

This PR replaces the use of `node-libofx` in `loot-core` with a drop in replacement `ofx-js`.

This allows us to delete `node-libofx` completely and remove most of the code in the monorepo.

All the snapshots for the parser tests are still satisfied.

### CODE REVIEW

**Comment by jlongster** [comment]
I hate to reject work that you've done, but I'm very nervous about doing this. I spent a _lot_ of time vetting the OFX/QFX parsing and the C++ library was the only one that actually handled edge cases properly. At this point Actual handles OFX/QFX very well and I believe this is because we are using the tried and true library that is actually used in all kinds of other apps. I personally don't trust ofx-js because I don't know how well it's used. It only has 883 downloads in the last 30 days so it's obviously not a very well-used library.

I think this would be a detriment to Actual; as annoying as it is to have a C++ lib compiled to WASM, importing QFX/OFX files is a critical workflow because we don't have bank syncing so it's really important that we make sure that it works very well

**Comment by TomAFrench** [comment]
That's fair enough, I imagined there was a good reason for things being as they are.

Agreed on tx import being critical enough for swapping out the importer being a pretty high risk action. However it would be good to be able to collect a number of these pathological OFX files so we can be confident for any future switch.

**Comment by jlongster** [comment]
There's really _so_ many bad parts of OFX that I don't think it's worth our time building up a test suite to cover them all. `libofx` is already a well-tested library so I'm not convinced we need to do that. Perhaps I'm not understanding the motivation to switch; it's a dependency that doesn't require much maintenance (there's a _small_ chance you have to rebuild the C++ source if you want to change something, but that probably won't happen. if it does it'll be just one more time in the next many years)

**Comment by TomAFrench** [comment]
It's a mixture of wanting to reduce the size of the OFX parser along with an irrational dislike of having such a large fraction of the monorepo (by LOC) being a dependency which we don't actively maintain (I assume that you haven't made any changes other than the glue code to wasm-ify it).

If that would result in degrading functionality then I'm onboard with leaving things as they are.

**Pull request closed without merging**
