### PR TITLE
Custom reports header fix

### PR DESCRIPTION
**Pull request by carkom**
Realign and fix header/totals row from table graph in custom reports.

### CODE REVIEW

**Comment by MatissJanis** [comment]
👋 

Code: although very brittle - is OK

But there is a small bug - the `category` label overlays the totals label when scrolling on smaller screens

Screenshot 2023-12-23 at 11 43 46

**Comment by carkom** [comment]
> 👋 
> 
> Code: although very brittle - is OK
> 
> But there is a small bug - the `category` label overlays the totals label when scrolling on smaller screens
> 
> Screenshot 2023-12-23 at 11 43 46
> 

Okay. Any suggestions on how to strengthen the code?

**Comment by MatissJanis** [comment]
> Okay. Any suggestions on how to strengthen the code?

There are couple of options. The simplest being: removing the sticky headers and using static ones (much simpler implementation, but _slightly_ worse UX). Personally I would just go for that.

Some other solutions:
1. using off-the-shelf lib for tables (though then we should consider switching all of them)
2. css sticky headers: https://css-tricks.com/position-sticky-and-table-headers/
3. move the brittle logic to a hook/component that abstracts away the complxity

**Comment by carkom** [comment]
> > Okay. Any suggestions on how to strengthen the code?
> 
> There are couple of options. The simplest being: removing the sticky headers and using static ones (much simpler implementation, but _slightly_ worse UX). Personally I would just go for that.
> 
> Some other solutions:
> 1. using off-the-shelf lib for tables (though then we should consider switching all of them)
> 2. css sticky headers: https://css-tricks.com/position-sticky-and-table-headers/
> 3. move the brittle logic to a hook/component that abstracts away the complxity

Sticky headers are used for all tables in the app. I think it would feel a bit strange for this to be the only one without them. Plus the UX is much nicer. 

I like the idea of pre-made tables being used across the app. I'd say best to tackle that in a separate PR if that's okay?

**Comment by MatissJanis** [comment]
> Sticky headers are used for all tables in the app. I think it would feel a bit strange for this to be the only one without them. Plus the UX is much nicer.
> 
> I like the idea of pre-made tables being used across the app. I'd say best to tackle that in a separate PR if that's okay?

For transaction table it makes sense to have them (since there are so many transactions to look through). Whereas here I would not expect anyone to have hundreds of categories, so it's not as important of a feature. Definitely still nice to have.. but if the trade-off is a lot of additional complexity: perhaps not worth it?

Yea, don't feel like this is a blocker for you. I'm totally OK with your current implementation as long as we get the one bug fixed :)

**Comment by carkom** [comment]
@MatissJanis, the overlay bug is fixed. Cheers!

**Review by MatissJanis — APPROVED** [review]

**Pull request merged**
