### PR TITLE
Use desktop colors for mobile autocomplete modals

### PR DESCRIPTION
**Pull request by joel-jeremy**
Closes https://github.com/actualbudget/actual/issues/2574

This also lessens the pain of managing different color schemes for desktop and mobile auto complete components.

### CODE REVIEW

**Comment by shall0pass** [comment]
It looks a lot better.  In light mode, the close button must have a color that is the same as the background.  Dark and midnight both show it clearly.

Screenshot_20240411-055856-938~2

**Comment by joel-jeremy** [comment]
@shall0pass should be fixed now :) However, I'd like to get this PR (https://github.com/actualbudget/actual/pull/2491) merged first before merging this one to minimize merge work that I have to do.

**Review by shall0pass — DISMISSED** [review]
LGTM!

**Comment by joel-jeremy** [comment]
@shall0pass Thanks for checking the other PR! I have rebased this to fix merge conflicts :)

**Review by shall0pass — APPROVED** [review]

**Pull request merged**
