### PR TITLE
Mobile create account

### PR DESCRIPTION
**Pull request by joel-jeremy**

### CODE REVIEW

**Comment by youngcw** [comment]
Functionally this seems to be working great.  I cant help with testing goCardless sadly.

**Comment by carkom** [comment]
So local account creation works fine. Found a couple bugs in the GoCardless and server sync process.

- When setting up a new server you get an error about mobile account creation when adding your first account. Then you get stuck on this page since you can't go back and use "don't use server" button anymore. The server/add file workflow is not at all accessible from mobile from what I can tell.
image

- If using existing server and adding a Go Cardless account (not the first account) using the new "+" button. All works fine until the end of the flow. In desktop a new window is open to step through GoCardless process. Upon completion you get redirected to actual app but no new account is added. You have to close this new window to see the "add new account" process you were going through in the original window this is the same in desktop app (not a great experience, but also not part of this PR). The button on this window gets cut off in the table of this flow. This whole table needs adjusting in mobile.
image

- When you click to "create new account" in the drop down of the above SS the account gets added successfully. I didn't have any errors in this process so I'm not sure how those might look.

**Comment by joel-jeremy** [comment]
@carkom Thank you for testing out the go cardless functionality! I have addressed the first bullet - adding accounts should now work when there no existing accounts yet. I think we should address the other bullet in a different PR. If you have time, could you create an issue for it?

**Comment by shall0pass** [comment]
In the mobile transaction entry page, we bring up a numeric keyboard for entries. Could we bring up the same numeric keyboard for the initial account balance box here when on mobile?

**Comment by carkom** [comment]
> @carkom Thank you for testing out the go cardless functionality! I have addressed the first bullet - adding accounts should now work when there are no existing accounts yet. I think we should address the other bullet in a different PR. If you have time, could you create an issue for it?

#1894

**Comment by joel-jeremy** [comment]
Thank you! Is the current implementation usable / good to go or do you think there are issues that needs to be fixed first before this gets merged?

**Review by youngcw — APPROVED** [review]

**Pull request merged**
