### PR TITLE
Marked files for translation

### PR DESCRIPTION
**Pull request by awaisalee**
Marked files for translation:

- packages/desktop-client/src/components/modals/EnvelopeBalanceMenuModal.tsx
- packages/desktop-client/src/components/modals/EnvelopeBudgetMenuModal.tsx
- packages/desktop-client/src/components/modals/EnvelopeBudgetMonthMenuModal.tsx
- packages/desktop-client/src/components/modals/EnvelopeBudgetSummaryModal.tsx
- packages/desktop-client/src/components/modals/LoadBackupModal.tsx
- packages/desktop-client/src/components/modals/TrackingBalanceMenuModal.tsx
- packages/desktop-client/src/components/modals/TrackingBudgetMenuModal.tsx
- packages/desktop-client/src/components/modals/TrackingBudgetMonthMenuModal.tsx
- packages/desktop-client/src/components/modals/TrackingBudgetSummaryModal.tsx
- packages/desktop-client/src/components/reports/Header.tsx
- packages/desktop-client/src/components/reports/reports/NetWorth.tsx
- packages/desktop-client/src/components/select/RecurringSchedulePicker.tsx

### CODE REVIEW

**Comment by awaisalee** [comment]
@youngcw @MikesGlitch, Could you please review PR?

**Review by MikesGlitch — APPROVED** [review]
Nice!

**Comment by tlesicka** [comment]
@awaisalee I know I'm a little late to this, but didn't look at this until I was syncing my PR's with the master.  No problems, just a question.
Why did you use the t function ```{t('text')}``` instead using the Trans tag ```<Trans>text</Trans>```?
Not saying you did anything wrong, I'm just curious.  In my PR (#3689) I had used ```<Trans>``` tags in ```LoadBackupModal.tsx``` and had quite a few merge errors to resolve.

Again, no issues, just curious as to which way I should code things in the future.  I have another PR that I'm working on that will create a couple new modals and want to have consistency with what is already established.

@MikesGlitch or @youngcw if either of you have any thoughts, let me know.

**Comment by MikesGlitch** [comment]
My only thoughts about it are we can't enforce a code styling rule if it's not in lint.

**Pull request merged**
