### PR TITLE
Goals: add flag to percent goals to use previous month income instead of this months

### PR DESCRIPTION
**Pull request by youngcw**
This is a more elegant way of implementing a month ahead version of the percent goals.  To use it add the `previous` flag to the percent goal, ex `#template 10% of previous Paycheck`.

### CODE REVIEW

**Review by shall0pass — APPROVED** [review]
It behaves exactly as described :)

**Comment by shall0pass** [comment]
One thought.  Should we use 'previous' instead of 'prev'?  The other templates use full words in the syntax that resembles a sentence.

**Comment by youngcw** [comment]
> Should we use 'previous' instead of 'prev'? The other templates use full words in the syntax that resembles a sentence.

probably.  Ill do that

**Comment by shall0pass** [comment]
`#template 10% of previous available funds` returns the same value as `#template 10% of previous available funds`.  I don't think it should have returned anything, right?

**Comment by youngcw** [comment]
I left the available funds unchanged.  So yes, having the flag there does nothing different

**Comment by shall0pass** [comment]
👍

**Comment by j-f1** [comment]
@shall0pass feel free to merge if you’re happy with the PR!

**Pull request merged**
