### PR TITLE
[Mobile] Budget file quick switch

### PR DESCRIPTION
**Pull request by joel-jeremy**
On top of https://github.com/actualbudget/actual/pull/2501.

Added:
- Quickly switch to another budget file without needing to close current one

### CODE REVIEW

**Comment by youngcw** [comment]
Is there anything needed aside from updating the branch?  I tried the netlify build and it seems to work great

**Comment by youngcw** [comment]
The file list modal isn't rendering for me

**Comment by joel-jeremy** [comment]
@youngcw Should be fixed now :)

**Comment by youngcw** [comment]
The regular file picker is now not showing anything.  This is after connecting to my server.  There should be 3 files shown

**Comment by joel-jeremy** [comment]
@youngcw Remote files should now show up

**Review by youngcw — APPROVED** [review]

**Pull request merged**
