### PR TITLE
Center name in mobile account page

### PR DESCRIPTION
**Pull request by joel-jeremy**

### CODE REVIEW

**Comment by MatissJanis** [comment]
Would you mind posting a before & after screenshot? I'm not sure where to look.

**Comment by joel-jeremy** [comment]
I'm on mobile right now, but you can try creating an account with a long name and open the account details. Without this change, the long account name will be left aligned.

**Comment by MatissJanis** [comment]
Ok, I see now. Hmm.. I wonder if it would be better to truncate it with an ellipsis instead.

Screenshot 2023-11-04 at 15 43 46

**Comment by joel-jeremy** [comment]
That's also possible. Maybe truncate after 2 lines, just like the category names in the mobile budget page?

**Comment by MatissJanis** [comment]
> That's also possible. Maybe truncate after 2 lines, just like the category names in the mobile budget page?

I'm not a big fan of how we handle category names currently in the budget page.

For example:

Screenshot 2023-11-05 at 14 58 34

Personally I think just allowing a single line and truncating with an ellipsis makes for the most aesthetically pleasing interface, but I don't want to impose my view on this too much. Happy to go with the 2-line approach too :)

**Comment by joel-jeremy** [comment]
I'm also good with truncating a single line but we need to add a way for users to view the entire account name. Any ideas?

**Comment by MatissJanis** [comment]
> I'm also good with truncating a single line but we need to add a way for users to view the entire account name. Any ideas?

Maybe opening a tooltip or modal on long click? Though maybe that's an overkill.. 

https://minwork.gitbook.io/long-press-hook/

**Comment by joel-jeremy** [comment]
A modal could work. We could also extend it to show/edit the notes and rename the account.

**Review by carkom — APPROVED** [review]
All good!

**Pull request closed without merging**
