### PR TITLE
Cleanup tool group enhancement

### PR DESCRIPTION
**Pull request by shall0pass**
This PR adds new ways to use the cleanup templates.

Group names can now be used to target specific categories.  

Examples:

```
1st category (contributes 50):   #cleanup MyFirstGroup source 
2nd category (contributes 100):   #cleanup MyFirstGroup source 
3rd category (receives 100):   #cleanup MyFirstGroup sink 2 
4th category (receives 50):   #cleanup MyFirstGroup sink
5th category (overspent): #cleanup MyFirstGroup

6th category (contributes 300):   #cleanup My Second Group source 
7th category (receives 200):   #cleanup My Second Group sink 2 
8th category (receives 100):   #cleanup My Second Group sink
9th category (overspent): #cleanup My Second Group

10th category (contributes 700):   #cleanup source
11th category (receives 700):   #cleanup sink
```
**MyFirstGroup**
In this example, all source funds from MyFirstGroup will only be distributed within MyFirstGroup.  The 5th category also belongs to the group, which is neither a source nor a sink category, will be filled if it is overspent/under funded.  The sink categories will then be funded based on the weight given.

**My Second Group**
All source funds from 'My Second Group' will be distributed to 'My Second Group'.  They work independently of one another.  The 9th category, which is part of 'My Second Group' will be funded before anything is distributed if it is overspent/under funded and then the funds from 'My Second Group' will be distributed to the sink categories based on weight.

**Global**
The group disbursements are calculated first (MyFirstGroup and My Second Group).  
No source or sink templates that have a group defined will be used in the 'global' portion of the script.  Any underfunded category will continue to be funded first (including the categories in groups), as long as the rollover carryover is not present.

After all groups are considered, the script runs as before and distributes the 'global' funds. 

 If a 'group sink' category is wished to be included in the 'global sink' calculation, a second line of ```#cleanup sink ``` needs to be added to the category notes.

If anyone has any feedback on the order of operations here, I'm open.
Currently it's:
1. Find groups
2. Run groups (source and sink)
3. Find 'global' source funds and return to 'To Budget'
4. Fund underfunded categories
5. Fill sinking funds

I could see a case for moving (2) after (5) in order to fill underfunded categories first and then distribute the groups.

### CODE REVIEW

**Comment by youngcw** [comment]
I'm seeing that the global sources don't get their goal reset so the balance is colored yellow.

**Comment by shall0pass** [comment]
> I'm seeing that the global sources don't get their goal reset so the balance is colored yellow.

I think the balances are being reset, but maybe the original methodology was wrong?  I'm seeing the same behavior in the original PR to this one.  The goal is being set to the current months spending, so if the category balance is zeroed out and a negative budgeted amount is entered, it won't reach the threshold of the goal.  

To turn a 'source' category green, maybe using the formula  (budgeted-balance), which would set the budgeted amount to the same amount required to zero the category, should be used.

**Comment by shall0pass** [comment]
This latest commit is quite a big change.  I've updated the syntax, added a step to cover overspent categories within groups, and added the ability to add a category to a group that is neither a sink or source category.

The use case I've envisioned with the neither sink nor source category.
1.  Reimbursement holding fund -> ability to only affect covering categories meant to be reimbursed
2. Utilities -> Possible to fund water, electricity, gas, etc and have utility categories cover overspending in other utility categories.

**Comment by shall0pass** [comment]
@youngcw I see I inadvertently left the calculation for setting the goal indicator to 'budgeted - balance'.  Take the opportunity to see if it is working better now.  I'll revert it if it's still not what's expected.

**Comment by shall0pass** [comment]
> Could you change the message for the global pass to include that its part of that group in some way?

I'm not sure what you mean.  Are you referring to ```#cleanup source``` and ```#cleanup sink```?

**Comment by shall0pass** [comment]
I added ```Global: ``` in front of the global warnings.  I'm not sure this is the most concise way to express it, but I'm coming up blank on alternatives.  Open to suggestions.

**Review by youngcw — APPROVED** [review]

**Review by youngcw — APPROVED** [review]

**Pull request merged**
