### PR TITLE
[Features] Togglable category width

### PR DESCRIPTION
**Pull request by Miodec**
Added a button that toggles the category width between 150px and 250px.

**NOTE: I have changed the deafult wdith from 200 to 150, if the maintainers think this is too narrow, i can revert it back and make the wide option be 250px or 300px.**

https://github.com/actualbudget/actual/assets/13181393/23bfc230-389d-458f-beb2-40de9691ea39

### CODE REVIEW

**Comment by MatissJanis** [comment]
👋 Thanks for your contribution! Before I do a proper review: two points I'd like to clarify.

1. Why? It feels like I'm missing some context here. Why would we want to add this additional complexity here? What problem does it solve?
2. (if we decide to go ahead with this): the expanded/collapsed state should be persisted in user prefs; it's very annoying if refreshing the page causes the state to reset back

**Comment by Miodec** [comment]
> 👋 Thanks for your contribution! Before I do a proper review: two points I'd like to clarify.
> 
> 1. Why? It feels like I'm missing some context here. Why would we want to add this additional complexity here? What problem does it solve?
> 2. (if we decide to go ahead with this): the expanded/collapsed state should be persisted in user prefs; it's very annoying if refreshing the page causes the state to reset back

1. I saw a few people mention that they wish they could change the width of the categories column, I thought that this change is not really complex, so might as well add it. Also gives a bit more space for the numbers, which is kind of related to #93.
2. Sure thing.

**Comment by youngcw** [comment]
I think that 150px is going to be too small for most people.  I have a few categories that already take up the current 200px wide column, and almost all of my categories are filling 150px. Personally I think 200px looks more balanced as well.  

I do like the wide or narrow option more than a fully adjustable width though.

**Comment by MatissJanis** [comment]
> 1. I saw a few people mention that they wish they could change the width of the categories column, I thought that this change is not really complex, so might as well add it. Also gives a bit more space for the numbers, which is kind of related to [[Feature request] Resizable columns #93](https://github.com/actualbudget/actual/issues/93).

The linked ticket talks about transaction table, not the budget table. It totally makes sense to have resizable columns in transaction table, but I'm still not sold on the idea of having resizable columns for budget categories.

Let me explain why:

Each small feature/enhancement/button we add to the UI adds to the complexity. If we continue adding buttons for each small edge-case - we'll end up with a cluttered UI. We don't want that. One of the selling points for Actual is the sleek UI that is not cluttered with unnecessary stuff.

So let me ask the same question again: what problem does this solve? Is this _really_ a problem?

**Comment by urhovaldeko** [comment]
I was the latest one to ask about this option on Discord. What I personally needed was a wider column there. I'd be ok with the button (or even manually having the width option somewhere).

What this really solves is the issue that adding notes to a category takes away visible text space to fit the note icon there. It is rather narrow anyway.

**Comment by rich-howell** [comment]
I want to throw a curve ball into the mix here, to me this seems like a very user specific requirement, there would only be a need to expand the cat sidebar in certain situations, forgetting about the complexity this adds to the code base for a moment although that is another cause of concern, should this not be a user preference set in the settings? 

A user could set a wider category layout or a slimmed down layout which would be persistent like every other setting, I am not sure that having a "toggle" on the budget sheet is a wise move, it adds in my opinion unnecessary confusion and noise to the UI.

**Comment by Miodec** [comment]
Some people dont need wide categories. I use emojis in my category names, which means i can distinguish different categories without even seeing their full names. This also means that more space is available for the numbers. Other people might want wider categories to see the full text at all times.

Im not sure if an invisible button adds much clutter. The only more subtle way would be to add a width field to the settings page.

I thought it would be a nice thing to have. Feel free to close.

**Comment by rich-howell** [comment]
> Some people dont need wide categories. I use emojis in my category names, which means i can distinguish different categories without even seeing their full names. 

So this is a really good argument for the toggle being user specific, right? 

I also don't think this should be closed - having a good healthy discussion about developments isn't about negatively bashing developments submitted by contributors but talking them through to ensure they fit with the vision for Actual. 

I for one am extremely grateful for the work and effort you have put in to development(s) recently.

**Comment by MatissJanis** [comment]
Sorry, but I dislike the idea of adding a new setting too. I don't want the settings page to get cluttered with a toggle/input box for every little thing in the UI.

What if we made the left side of the categories menu a draggable element? So people could hover over it - drag it to the width they want - and release the cursor. After which the width would be stored in user prefs.

I do realize this is a much more complex task to accomplish.. so @Miodec please don't feel pressured to do it. And apologies for all these long discussions we've had for such a seemingly small feature. We want to keep the Actual UI clean and clutter-free. I know how frustrating that can be. Your contributions are still very much valued and I hope to see more from you :)

**Comment by Miodec** [comment]
Yeah my React abilitites are definitely not good enough to add a draggable element like this, but it would probably be the best solution.

**Comment by rich-howell** [comment]
> Sorry, but I dislike the idea of adding a new setting too. I don't want the settings page to get cluttered with a toggle/input box for every little thing in the UI.
> 
> What if we made the left side of the categories menu a draggable element? So people could hover over it - drag it to the width they want - and release the cursor. After which the width would be stored in user prefs.
> 
> I do realize this is a much more complex task to accomplish.. so @Miodec please don't feel pressured to do it. And apologies for all these long discussions we've had for such a seemingly small feature. We want to keep the Actual UI clean and clutter-free. I know how frustrating that can be. Your contributions are still very much valued and I hope to see more from you :)

Unfortunately @MatissJanis it isn't just your decision. It is the decision of the community, that is why this is an open source project, if there is a discrepancy between what the community wants and what the maintainers are happy to merge or feel just to merge this should be pushed back to the community to decide upon unless there is a detrimental impact or reason why this can't be added.

**Comment by trevdor** [comment]
Directionally, I agree this doesn’t warrant adding a setting. Especially in a community project, there will be many opinions and differing use cases. 

I had the thought of a draggable width setting independently, so I’m a fan of Matiss’ suggestion. A setting without a setting. 

It would add complexity to our responsive logic. For instance, we auto-hide the sidebar when there’s just enough room for the budget table.

**Comment by j-f1** [comment]
> Directionally, I agree this doesn’t warrant adding a setting. Especially in a community project, there will be many opinions and differing use cases.

I’m a strong agree on this. I think we should do our best to keep the settings screen pretty simple and try to find another way to express the setting in context if we add it at all.

**Comment by MatissJanis** [comment]
👋 So it seems we have a consensus here: the feature could be significantly simplified from a UI perspective (though the implementation might not be that straight-forward).

Is this something you would like to look into @Miodec as part of this PR? If not - I think we can close this one off?

Let me know what you think!

**Comment by Miodec** [comment]
I don't think my React skills are up to the task just yet, so I think I'll just close it for now.

**Pull request closed without merging**
