### PR TITLE
Allow libofx to handle decoding imported files

### LINKED ISSUE #189: Is charset/encoding supported when importing qfx files?
I have qfx files with `CHARSET:8859-1` with transactions having accentuated characters and I think it's not importing correctly.

### PR DESCRIPTION
**Pull request by j-f1**
This avoids assuming that imported OFX files are UTF-8 and defers to libofx, which handles reading the `CHARSET` header in the file and using that encoding to read its content. Fixes #189. (Tested with the provided file and it works fine!)

### CODE REVIEW

**Comment by MatissJanis** [comment]
How do I test this? I tried importing the given file, but I keep getting an error
Screenshot 2023-01-31 at 20 43 58

**Comment by j-f1** [comment]
Weird, it works fine for me. Did you uncompress the downloaded GZIP file first? Once I do that I’m able to view the `relve.qfx` file as a text file or import it into the app.

**Comment by MatissJanis** [comment]
No, I didn't uncompress it. I actually can't do it on OSX (Ventura 13.1).

Screenshot 2023-01-31 at 22 52 26

**Comment by MatissJanis** [comment]
Yeah, I can't seem to get the file open on OSX. So can someone else on a Win/Linux machine test the change and let me know if it works as expected?

I can then do the code review.

**Comment by j-f1** [comment]
@MatissJanis Can you try with https://raw.githubusercontent.com/actualbudget/actual/b84c58ad0bf1db194ad954b995b8ff6d65d496e1/packages/loot-core/src/mocks/files/8859-1.qfx? That’s the uncompressed version of the file that was shared with us. (I was able to decompress using `gunzip` and [BetterZip](https://macitbetter.com) on my Mac, not sure why Archive Utility fails)

**Review by MatissJanis — APPROVED** [review]
Thanks @j-f1 ! Was able to reproduce the issue and then also reproduce the fix in the preview deployment.

LGTM

**Pull request merged**
