### PR TITLE
Goals: Check template action

### LINKED ISSUE #1100: [Bug]: Goal Templates: Error in number of templates reported when finished.
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If you are using multiple template lines in a single category, the green box at the end reports the number of templates processed as the number of categories.

EX.  3 categories with templates but one of those has 2 lines.  The box at the end will say "Successfully applied templates to 4 categories".

The successful return should probably report the number of templates and number of categories, or just number of successful templates.

### What error did you receive?

NA

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Linux

### PR DESCRIPTION
**Pull request by youngcw**
This adds an option to the month drop down to check all the template lines.  If there are errors the offending line is shown with its category.

I also modified the wording on the regular template return to be more accurate. Fixes #1100

### CODE REVIEW

**Comment by rich-howell** [comment]
This feature is still very much experimental but I personally am a bit concerned it is bleeding out into the UI, this drop down is getting increasingly large now if goals is turned on, if goals is turned off there is only 3 options here. 

image

I think if Goals are sticking around we need to think about a design for the UI and how this should look in a more perm position that means something to the user.

**Comment by youngcw** [comment]
I agree that menu is getting busy, and that something better needs put together.  To stir the pot some more, should that menu exist at all?  It makes sense to be there with the 3 non-experimental options, but not as much once templates are added.  I don't think it would be bad to make a combined view for all these budget filler options like is being discussed in #1006.  That way anything that isn't manual budgeting gets its own view.

But that's a ways off.  I'm open to suggestions of a better placement for the time being.

**Comment by rich-howell** [comment]
At the moment we have options all over the place!

I would suggest that the option you added in this particular PR gets moved into here

image

It is a check of the templates in the categories, it isn't doing anything to the budget itself which is what the other menu (below)

image

Seems to be for...

The top menu, seems to be for options that affect the budget and the second menu is for options that affect categories, as the templates we are checking are in category notes, maybe it should be there?

**Comment by youngcw** [comment]
Would it be confusing to have the template actions be in two different places?

**Review by j-f1 — APPROVED** [review]
I'm personally fine with merging this now and discussing UI improvements separately, since this feature is still experimental. @rich-howell any objections to that?

**Pull request merged**
