### PR TITLE
Added date to export file name

### PR DESCRIPTION
**Pull request by rich-howell**
Added the date to the file name of the zip file.

**Current Behaviour**

image

**New Behaviour**

image

### CODE REVIEW

**Review by MatissJanis — APPROVED** [review]
LGTM!

**Comment by j-f1** [comment]
IMO this should use `YYYY-MM-DD` like ISO8601 (since that format isn’t confusable by Americans/Europeans like 04-01-2023 is, and because it sorts chronologically by default).

**Comment by MatissJanis** [comment]
> IMO this should use `YYYY-MM-DD` like ISO8601 (since that format isn’t confusable by Americans/Europeans like 04-01-2023 is, and because it sorts chronologically by default).

It currently is `yyyyMMdd`. So basically what you're suggesting minus the dashes.

**Comment by j-f1** [comment]
Yep, you’re right. Must have read the diff wrong. I’d prefer the dashes but it’s also fine to merge as-is IMO

**Comment by rich-howell** [comment]
> IMO this should use `YYYY-MM-DD` like ISO8601 (since that format isn’t confusable by Americans/Europeans like 04-01-2023 is, and because it sorts chronologically by default).

Added the dashes back in :)

**Review by j-f1 — APPROVED** [review]
This is great, LGTM!

**Comment by TechwizEE** [comment]
This works fantastic.  Love the change.  Tried out the Netifly and it works as described.

**Pull request merged**
