### PR TITLE
Adds ability to resize sidebar

### PR DESCRIPTION
**Pull request by YusefOuda**
**Relevant issue:** N/A

**Description:** This PR adds the ability to resize the sidebar using [re-resizable](https://github.com/bokuweb/re-resizable) on the sidebar component. It adds a new local pref to save the width so that it is persisted, with a minimum width of `200px` and a maximum of `viewport width / 3`. The sidebar animation is also updated to use a percentage for `translateX` to accommodate the varying possible sizes

### CODE REVIEW

**Comment by MatissJanis** [comment]
👋 How can I resize the sidebar? I'm trying to click & drag on the border, but the size isn't changing. Is there a different way to resize it?

**Comment by YusefOuda** [comment]
@MatissJanis You click and drag on the bottom right corner where you see the little icon

**Comment by MatissJanis** [comment]
Ah.. that's quite easy to miss. Could we make the entire right side of the side-nav a drag-handler? That would make it much more discoverable.

Some more issues:
- [ ] the min width should be increased to 200px - things get real weird if the size is smaller
- [ ] why did the VRT tests change? Is the default side nav width now _slightly_ different? Ideally the VRT tests should have no changes from this PR

Apart from that - really exciting to see this feature. Hoping to get it in the next release! 🤞

**Comment by YusefOuda** [comment]
So I implemented resize using [CSS resize](https://developer.mozilla.org/en-US/docs/Web/CSS/resize), which unfortunately doesn't have a way to change the handler position or style (at least easily).

That is also why the VRT tests changed (because of that little handler in the sidebar)

I'll do a little digging to see how I can implement this some other way (I see we use react-dnd for drag-and-drop, but I'm not sure how well that will work with resizing.)

**Comment by YusefOuda** [comment]
I refactored this to use [re-resizable](https://github.com/bokuweb/re-resizable)

I also fixed the VRT and updated the minimum width. Let me know your thoughts, thanks!

**Review by MatissJanis — APPROVED** [review]
Great! Thanks for adding this improvement!

(I won't merge just yet in case any other maintainer wants to review)

**Comment by youngcw** [comment]
This is much better than when I originally tested it.  Thanks!

**Pull request merged**
