### PR TITLE
:bug:  allow deleting both transfer transactions at the same time

### LINKED ISSUE #487: [Bug]: Deleting both entries of an account transfer at the same time results in error
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

I ran actual-server via yarn and am running the 23.1.12 build.

I tried deleting multiple transactions from the All Accounts screen and an error was thrown.  Here is a visual history of how I can reproduce this behavior.

I created 3 scheduled transactions for tomorrow.
image

I see all of my scheduled transactions in the accounts page.
image

I post all upcoming transactions.
image

I select all of the recently posted transactions and delete.
image

The progress spinner just spins.
image

### What error did you receive?

The popup error shows.
image

The Console log shows.
image

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #487

Reproduction steps best explained in the linked issue ticket. But TLDR:

1. create a transfer transaction from account A to B
2. open "all accounts" view
3. select both transfer transactions
4. click delete
5. before: error appears; after: no error, both transactions deleted

### CODE REVIEW

**Comment by biohzrddd** [comment]
While testing this PR I ran into a possibly related issue. On a new transfer transaction, changing the notes on the transaction on account A also changes the note on account B and vice versa. Going into All accounts view, you can change the notes on one and it won't change on the other. I'll raise another issue after testing the current one!

**Comment by biohzrddd** [comment]
While testing I'm still getting an error notice in app and browser dev console on delete. 

Code I ran to test (in case I'm not doing it correctly):
`biohzrddd@Maincomp:~/dev/actual$ git branch
* (HEAD detached at origin/matiss/fix-487)
  jlongster-api-deps
  master
  matiss/fix-487`

`biohzrddd@Maincomp:~/dev/actual$ nvm use 16.18.1; corepack enable; yarn install; yarn start:browser-frontend`

In All accounts view, on select of the two transactions I get one error and on delete I get another.

`index.js:1451 
        
       Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Menu`. See https://fb.me/react-warning-keys for more information.
    in Text (at common.js:581)
    in Menu (at table.js:789)
    in div (at tooltips.js:317)
    in div (at tooltips.js:315)
    in Tooltip (at table.js:783)
    in div (at View.js:13)
    in View (at table.js:770)
    in SelectedItemsButton (at Account.js:493)
    in SelectedTransactionsButton (at Account.js:823)
    in div (at View.js:13)
    in View (at Stack.js:37)
    in ForwardRef (at Account.js:740)
    in div (at View.js:13)
    in View (at Account.js:663)
    in Unknown (at Account.js:1674)
    in div (at View.js:13)
    in View (at Account.js:1673)
    in SelectedProvider (at useSelected.js:268)
    in SelectedProviderWithItems (at Account.js:1667)
    in AllTransactions (at Account.js:1661)
    in AccountInternal (at Account.js:1795)
    in AccountHack (at Account.js:1857)
    in SplitsExpandedProvider (at Account.js:1854)
    in SchedulesProvider (at Account.js:1853)
    in Account (created by Context.Consumer)
    in Route (at FinancesApp.js:113)
    in Route (at FinancesApp.js:80)
    in Switch (at FinancesApp.js:79)
    in Routes (at FinancesApp.js:138)
    in ActiveLocationProvider (at FinancesApp.js:137)
    in StackedRoutes (at FinancesApp.js:322)
    in div (at FinancesApp.js:312)
    in div (at FinancesApp.js:290)
    in div (at View.js:13)
    in View (at FinancesApp.js:287)
    in div (at View.js:13)
    in View (at FinancesApp.js:284)
    in RenderedRoute (created by Routes)
    in Routes (created by CompatRouter)
    in Router (created by CompatRouter)
    in CompatRouter (at FinancesApp.js:283)
    in Router (at FinancesApp.js:282)
    in FinancesApp (at FinancesApp.js:343)
    in Unknown (at FinancesApp.js:352)
    in AccountsProvider (at FinancesApp.js:351)
    in PayeesProvider (at FinancesApp.js:350)
    in BudgetMonthCountProvider (at FinancesApp.js:349)
    in SidebarProvider (at FinancesApp.js:348)
    in TitlebarProvider (at FinancesApp.js:347)
    in SpreadsheetProvider (at FinancesApp.js:346)
    in FinancesAppWithContext (created by ConnectFunction)
    in ConnectFunction (at App.js:114)
    in div (at App.js:92)
    in App (created by ConnectFunction)
    in ConnectFunction (at src/index.js:74)
    in Provider (at src/index.js:73)
console.<computed> @ index.js:1451
printWarning @ react.development.js:312
error @ react.development.js:284
validateExplicitKey @ react.development.js:1601
validateChildKeys @ react.development.js:1626
createElementWithValidation @ react.development.js:1775
Menu @ common.js:565
renderWithHooks @ react-dom.development.js:14796
mountIndeterminateComponent @ react-dom.development.js:17408
beginWork @ react-dom.development.js:18486
beginWork$1 @ react-dom.development.js:23028
performUnitOfWork @ react-dom.development.js:22016
workLoopSync @ react-dom.development.js:21992
performSyncWorkOnRoot @ react-dom.development.js:21610
(anonymous) @ react-dom.development.js:11130
unstable_runWithPriority @ scheduler.development.js:656
runWithPriority$1 @ react-dom.development.js:11076
flushSyncCallbackQueueImpl @ react-dom.development.js:11125
flushSyncCallbackQueue @ react-dom.development.js:11113
discreteUpdates$1 @ react-dom.development.js:21749
discreteUpdates @ react-dom.development.js:811
dispatchDiscreteEvent @ react-dom.development.js:4210
index.web.js:4 [Exception] TypeError: Cannot read properties of undefined (reading 'is_child')
    at removeTransfer (transfer.js:98:21)
    at async Module.onDelete (transfer.js:144:5)
    at async Promise.all (:3001/index 0)
    at async transactions.js:124:5
    at async batchMessages (index.js:441:5)
    at async batchUpdateTransactions (transactions.js:116:3)
    at async main.js:120:18`

**Comment by MatissJanis** [comment]
@biohzrddd feel free to run your manual tests by using netlify preview deployment: https://deploy-preview-491--actualbudget.netlify.app/

It will be much simpler for you that way :)

**Comment by tjfinlinson** [comment]
Tested this with the Brave Browser on Windows Desktop and I didn't receive any errors when deleting each side of the transfer in the All Accounts screen when selecting both of them.

**Pull request merged**
