### PR TITLE
Fix Issue 3331, sort favorite payees before other frequently used payees

### LINKED ISSUE #3331: [Bug]: Payees should sort favorite payees before other suggested payees.
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Right now, payees are sorted in three groups, suggested payees, payees and transfers. All are sorted alphabetically. Suggested payees draws from two different sources though, users can either mark payees as favorites, or the most frequently used payees in the past 12 weeks, if users haven't marked at least five payees as favorites. 

Since users have specifically marked favorites as desired payees, they should be shown in the suggested payees first. Then common payees should be added. Both subsections should remain otherwise unmarked and be sorted alphabetically.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

_No response_

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by qedi-r**
This fixes #3331. It changes the Suggested Payees section from
* Alice
  Bob
* Charlie 
 Dave
 Ernie

to 
* Alice
* Charlie
Bob
Dave 
Ernie

in cases where there are fewer than five favorites in the system.

It also adds tests, I could separate the tests from the bugfix, if people want to discuss the tests more.

### CODE REVIEW

**Comment by youngcw** [comment]
Functionally it looks good.  Can you update the branch and fix the failed checks?

**Comment by qedi-r** [comment]
Ok, test inconsistencies are addressed.

**Comment by MikesGlitch** [comment]
@coderabbitai review

**Comment by matt-fidd** [comment]
Hi @qedi-r, it looks like VRT is still failing. Could you update the branch and see if it clears please?

**Review by youngcw — APPROVED** [review]

**Pull request merged**
