### PR TITLE
♻️ (tooltip) refactoring to react-aria (vol.7)

### PR DESCRIPTION
**Pull request by MatissJanis**
Refactoring custom reports usages of the old `Tooltip` component to `react-aria`.

### CODE REVIEW

**Comment by carkom** [comment]
A couple regressions that need fixed:

- Small nit - the buttons used to highlight even while the menu was open.
- The bottom border of the "Options" button gets covered by the menu (didn't used to)
- "Choose Graph" option in the main menu needs padding
image

**Comment by MatissJanis** [comment]
> "Choose Graph" option in the main menu needs padding

Good catch! This one is now patched: https://github.com/actualbudget/actual/pull/2778/commits/6ac0c4c218fe37be33a4f28cadd2d59de8b426df

> Small nit - the buttons used to highlight even while the menu was open.

Yea, there is a small visual difference between the old implementation and the new one we have.

> The bottom border of the "Options" button gets covered by the menu (didn't used to)

Not quite sure what you mean.

| Edge | PR |
|--------|--------|
| Screenshot 2024-05-18 at 21 46 16 | Screenshot 2024-05-18 at 21 46 13 |

**Comment by carkom** [comment]
I guess it's only visible in dark modes
PR
image

Edge
image

**Comment by MatissJanis** [comment]
Interesting.. 🤔 

| Edge | PR |
|--------|--------|
|  Screenshot 2024-05-18 at 22 24 49 | Screenshot 2024-05-18 at 22 24 52 |

**Comment by MatissJanis** [comment]
Added 1px offset. Though this will affect all the popovers.

**Review by carkom — APPROVED** [review]
LGTM!

**Comment by carkom** [comment]
@MatissJanis I've just noticed that this has broken the ReportCard menus. It only applies the popover menu to the last card. I assume this is because it's using just one trigger ref for potentionally 20+ cards? I'm not really sure how this works and I've been unable to fix it with my tinkering. Can you have a look?

**Pull request merged**
