### PR TITLE
Unflag custom reports

### PR DESCRIPTION
**Pull request by carkom**
Removing custom reports from feature flag "experimental" state.

### CODE REVIEW

**Comment by carkom** [comment]
I think I'm ready to remove custom reports from experimental. It's fairly stable at this point. It has most everything I planned to add to it. Still plenty more to add and a couple things to fix but I don't think they are big issues that should stop it from going "live". Please share your thoughts.

**Comment by youngcw** [comment]
I think my main hangup would be that live date ranges don't update for dashboard cards without going in and updating the report.  Its not a big deal since work will still go on.

**Comment by carkom** [comment]
> I think my main hangup would be that live date ranges don't update for dashboard cards without going in and updating the report. Its not a big deal since work will still go on.

Yea, it's at the top of my list right now. I'll try to put in a PR this weekend to fix that.

**Comment by MatissJanis** [comment]
I'd recommend not rushing into this prematurely. The feature still seems quite unstable (judging from the amount of bug reports coming in). Could we hold off a bit more to gather some more feedback before calling it a **stable** feature?

**Comment by carkom** [comment]
> I'd recommend not rushing into this prematurely. The feature still seems quite unstable (judging from the amount of bug reports coming in). Could we hold off a bit more to gather some more feedback before calling it a **stable** feature?

Heya, I know this comment is 2 months old but the bug reports you mention were very small issues that were directly related to newer features and were fixed quite easily. The only reason I said stable is that we've gone several months without any major issues with the feature.

Fast forward to today - since opening this PR, I've requested feedback on the stability of the feature and fixed all (very minor, most visual) issues reported. I've also converted 100% of the code to strict TS and submitted several code hardening PRs to make this feature ready for release.

If there are any further concerns I'm happy to address them. I am currently very confident in propsing this feature is removed from experimental for the next release (v24.7).

**Comment by MatissJanis** [comment]
Sounds like a good plan!

**Review by youngcw — DISMISSED** [review]

**Comment by carkom** [comment]
Yep, it's time...

**Comment by youngcw** [comment]
Are you wanting to unflag even without the net additions?

**Review by youngcw — APPROVED** [review]

**Comment by carkom** [comment]
> Are you wanting to unflag even without the net additions?

I don't think the changes to net is a blocker for this PR. I see the net additions as a good enhancement but not imperitive for release. I'm also happy to discuss this view if anyone disagrees.

**Pull request merged**
