### PR TITLE
Apply Template to All Categories in Group for Mobile

### PR DESCRIPTION
**Pull request by Dreptschar**
Adds Feature from https://github.com/actualbudget/actual/issues/3040 and expands https://github.com/actualbudget/actual/pull/3666

### CODE REVIEW

**Comment by Dreptschar** [comment]
Ive add a new menu to groups. Idk if thats a good solution would love to hear some opinions

**Comment by youngcw** [comment]
I don't love that its in a new modal vs one of the existing ones

**Comment by Dreptschar** [comment]
Agreed. But I couldn't think of a way to put the new button in one of the existing menus. It's to big of a word for the remove Menu and when I add a third button to the one below the notes it looks awful. I could adjust the width of the buttons so three can fit in one row. 
One the other hand, I always thought it's weird that you can't click the budget of a group idk 😅

**Comment by Dreptschar** [comment]
How should i proceed ?

**Comment by youngcw** [comment]
First off this will need to be updated and conflicts fixed.  I would look at adding the action to the existing group modal since you aren't budgeting a group, you are budgeting categories, it doesn't make sense to click on the group budget total.  The other modals have a few different options for actions to look at.

**Comment by joel-jeremy** [comment]
I agree that this should not be in a new modal. The button is also not obvious that it can be clicked. We can instead add this on the existing category group modal but have a collapsible `Actions` section. Please see the existing month menu modal:
image
image

**Pull request closed without merging**
