### PR TITLE
Add plugin for offline PWA support

### PR DESCRIPTION
**Pull request by jfdoming**
This PR adds a vite plugin for offline PWA support, so that you can install the app as a PWA and then use it offline.

It worked well in my brief testing (both in dev and after installing), but would love other folks to try it out and let me know their thoughts.

### CODE REVIEW

**Comment by shall0pass** [comment]
The app gets further than before🚀.  I'm getting these errors in the Dev console as the status circle spins.
image

**Comment by youngcw** [comment]
I don't know if it's just the netlify deply, but with Brave on Android I just get an endless spinner when offline. Still an improvement though

**Comment by jfdoming** [comment]
> I don't know if it's just the netlify deply, but with Brave on Android I just get an endless spinner when offline. Still an improvement though

Yep, sorry, I should have opened this in draft first 😄 working through some issues locally

**Comment by jfdoming** [comment]
Alright, I believe I've fixed the errors you previously encountered! Let me know how your testing goes.

**Comment by youngcw** [comment]
Nice!  It seems to be working both on my phone (brave android) and my desktop (brave linux).

One thing that I noticed on my desktop is that the fonts are different when offline.

**Comment by jfdoming** [comment]
> Nice! It seems to be working both on my phone (brave android) and my desktop (brave linux).
> 
> One thing that I noticed on my desktop is that the fonts are different when offline.

Oh hmm, I think I know why that is. Let me go play around with the regex a bit

**Comment by shall0pass** [comment]
It appears to be working for me as well! Fantastic!

**Comment by youngcw** [comment]
something about that change made it so the installed app wont open for me on desktop anymore

**Comment by jfdoming** [comment]
Hmm, yeah I think there's something I'm not understanding about how fonts are served. I'm going to continue looking into it

**Comment by jfdoming** [comment]
Alright @youngcw could you check again? I believe I fixed the fonts issue

**Comment by youngcw** [comment]
All seems good now!  Thanks for doing this.  Its been a long time needed.

**Review by youngcw — APPROVED** [review]

**Pull request merged**
