### PR TITLE
Force the sidebar to always float when the window is narrow

### PR DESCRIPTION
**Pull request by j-f1**
This improves usability of narrow screen widths, and also prepares for further optimizations that would allow us to use the sidebar largely as-is on mobile, instead of having to have a tab bar.

### CODE REVIEW

**Review by MatissJanis — COMMENTED** [review]
Small bug:

On desktop devices that have small screen size and are touch-friendly the side menu floats away. When you click the hamburger menu - it floats back in. But if you click it again - nothing happens. There is no way to hide the floating menu on touch desktop devices.

**Review by MatissJanis — APPROVED** [review]
Nice!

**Comment by Kidglove57** [comment]
An observation from using this update on my iPhone 13 Pro on 2023-04-0. I used Safari. 

1) I reduced the display size to 50% so that I could see my Payee and Category columns in portrait mode. The side bar would not remain floating.

2) I increased the display to 75% (mobile Safari does not offer anything in between). The sidebar now floats at all times.

**Comment by j-f1** [comment]
Tested it out on the same device, and I think that’s the best we can do — the screen width at 50% zoom is a reasonable one for a desktop so it makes sense to allow the sidebar to not float, and at 75% that is not the case. (You can always switch the sidebar to floating mode at 50% if you want to)

**Comment by Kidglove57** [comment]
Thanks for testing and explaining! Much appreciated.

**Pull request merged**
