### PR TITLE
Add yearly to custom reports

### PR DESCRIPTION
**Pull request by carkom**
Enable "yearly" interval. Also sets-up groudwork for adding weekly/daily in the near future.

### CODE REVIEW

**Comment by carkom** [comment]
Base functionality should work fine for anyone who wants to test it.

Still need to clean up the variable names a bit and fix the disabled/default lists for things like "dateRange".

**Comment by Teprifer** [comment]
Intervals are a cool idea, had a dabble around and look forward to testing it out properly when you've worked through the bits you already know about.

**Comment by carkom** [comment]
This is ready for review.

**Comment by youngcw** [comment]
Im getting this error when opening one of my files
```
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'map')
    at m8 (ReportTableTotals.tsx:88:31)
    at l1 (react-dom.production.min.js:167:137)
    at TI (react-dom.production.min.js:290:337)
    at wI (react-dom.production.min.js:280:389)
    at lL (react-dom.production.min.js:280:320)
    at Wh (react-dom.production.min.js:280:180)
    at Q0 (react-dom.production.min.js:271:88)
    at vI (react-dom.production.min.js:268:429)
    at E (scheduler.production.min.js:13:203)
    at MessagePort.H (scheduler.production.min.js:14:128)
```

**Comment by Kidglove57** [comment]
Same here, Actusk crashing when selecting Reports tab - but I do have a lot of saved reports in my file. In case it is relevant, some of these saved reports are based on saved searches made with the filter tool.

**Comment by carkom** [comment]
I'd venture the say this happens on edge as well? Culprit is a previous merge that needed to be done to make intervals possible. All saved reports will need to be remade. Cheers!

**Comment by carkom** [comment]
Thanks both. Put in a fix for this crashing issue due to change in report function backend.

#2492

**Review by youngcw — APPROVED** [review]

**Pull request merged**
