### PR TITLE
Create an artifact with the built web UI for each commit

### PR DESCRIPTION
**Pull request by j-f1**
Part of fixing the horrendously slow Docker build for the server edge images.

### CODE REVIEW

**Comment by j-f1** [comment]
I’m not sure what the best name here is — I’m currently calling the zip `desktop-client` but there is probably a better choice.

**Comment by MatissJanis** [comment]
How will this make the Docker builds faster?

**Comment by j-f1** [comment]
Instead of downloading deps + building the frontend separately in emulated VMs multiple times (for each combination of OS + architecture) we can just download the ZIP from the latest build on `master` and attach it to the image.

**Comment by j-f1** [comment]
This PR just uploads the artifact, https://github.com/actualbudget/actual-server/pull/147 downloads them

**Review by MatissJanis — APPROVED** [review]
The artifacts have a retention period of 90 days. This doesn't really change anything right now as we are actively working on Actual, but I wonder what the future holds.. perhaps worth adding a scheduled upload action just in case?

**Comment by j-f1** [comment]
I think it’s fine since people will always be able to grab the latest image from GitHub/Docker Hub even if new builds are failing, and stable images don’t use the artifacts.

**Pull request merged**
