### PR TITLE
add descriptive colors for available funds

### PR DESCRIPTION
**Pull request by edmonday**
Issue: #2934 

### Description:

Add green colour to non-zero values for expense balances. If a budget template is applied and your available balance is zero, apply grey colour.

Screenshot 2024-07-13 at 5 18 50 PM

### CODE REVIEW

**Comment by edmonday** [comment]
E2E Tests / Visual regressions tests failing. Probably because the snapshots look different.

**Comment by MatissJanis** [comment]
👋 Hi! I agree that it makes sense to use these colors in the context of goals, but for folks not using goals feature - I don't think they are applicable.

Here are the states for the colors:
- red: things are bad, you should work on addressing a problem with this category
- green: goal is met
- yellow: goal is not met, but you're still OK (I think that's what yellow means?)

With the change - the intent of green would be two different states - "goal is met" and "balance is positive". There would be no way to distinguish between the two states unless you know the logic behind "yellow" (which I would argue - users do not need to know).

**Comment by edmonday** [comment]
@MatissJanis thanks for the comment.

Totally open to another solution that could quickly help a user identify what they have funds available. At the moment it looks no different to the budgeted and spent values. 

My interpretations of the colours would be.

- red: things are bad, you should work on addressing a problem with this category
- yellow: there's something off here, but not critical (currently only applicable to goal not being met)
- green: we're in the green! 🥳 (there's available funds or goals have been met)

Maybe it's worth adding a little something to make the balances look abit different? Maybe a bump in font weight or even using the pill styling we see from mobile?

**Comment by MatissJanis** [comment]
I'm quite confused as to what problem you are trying to solve here. Is it purely aesthetics and you wanting more color in the app? Color-blindness is definitely worth solving, but arguably the introduction of the color scheme here actually goes against the objective there.

Personally:

1. I don't see the value add here
2. I think this color logic conflicts with goal template indicator colors
3. I'm not a fan of having rainbow colors all over the product as it that just creates signal fatigue

**Comment by edmonday** [comment]
Sorry if I wasn't clear. The objective is mainly to make the balance stand out a bit more. I thought maybe some colour would help. It would mainly be an aesthetic thing.

Totally respect where you are coming from ☺️ and happy for this to be closed. Thanks for making the time to review and explaining all of this to me.

Will be interested to do some thinking around the colour-blindness ticket and give that a crack.

**Comment by atgrey24** [comment]
Sounds like you were trying to emulate YNAB's behavior with colors, where green=funded and red=overspent even when no targets are enabled, and yellow=underfunded (when there is a target).

I get why this doesn't meet Actual's design philosophy, but I do think something to improve legibility and draw the eye to the balances is worth exploring, like the line weight/pill ideas you mentioned.

**Pull request closed without merging**
