### PR TITLE
Allow goal template 'by' matches to compound

### PR DESCRIPTION
**Pull request by shall0pass**
I believe this change allows for having multiple 'by' rules in the same category.  It seems to be working well for my purposes, but I would appreciate further testing to assure there aren't regressions.

Example:

#template 300 by 2023-06
#template 3000 by 2023-08

Before this PR, having these two lines in the notes would only budget funds for the earliest of the two strings and ignore the 3000 funding target.  With this PR, the sum of the two funding targets will be respected.

### CODE REVIEW

**Review by j-f1 — APPROVED** [review]
LGTM!

**Comment by Kidglove57** [comment]
I have carried on with some additional ad hoc testing. When I start with a clean sheet in a category, the compounding works really well (thank you!). However, if I already have some funds accumulated in a category from previous months things don't seem to work out quite the same:
**Example:**
#template 600 by 2023-10 repeat every year
_(should be 100 funding in May)_
#template 1200 by 2024-04 repeat every year
_(should be 100 funding in May)_
#template 1200 by 2023-10 repeat every year
_(should be 200 funding in May)_
If I have nothing in that category and I fill the budget in may this correctly gives me a budget fill of 400 and 400 available in the category.
**HOWEVER:**
Say I already have 200 in that category in April. I now do a fill in May using the templates. For some reason this gives a very different result:
Budget Fill: 316.67. Total now available in the category 516.67 (instead of the 400 needed)

Have I missed something obvious?

**Comment by Kidglove57** [comment]
Here is a different example using a complete 12 month period to fund two identical templates over:
_#template 1200 by 2024-04 repeat every year
#template 1200 by 2024-04 repeat every year_
So the funding should be 200 pm from May on?

But what I get by way of monthly funding is:
May 200, June 181.82, July 163.64 and so on.

By contrast, if I enter just one template line for the same target date ie:
_#template 1200 by 2024-04 repeat every year_
This correctly fills my budget at exactly 100 per month.

**Comment by shall0pass** [comment]
You're right.  For the dual lines with a target of 1000 in the same month, it isn't making it to 2000 by the target date.  It only makes to 1000 by the target date. This definitely needs looked at further.

**Comment by Kidglove57** [comment]
Thanks for the follow up!
I just amended my example to:
#template 1200 by 2024-04
#template 600 by 2024-04

The resultant fills were then:
May £150 (correct)
June £136.36
July £122.72
And so on, reducing, but staying at 83.77 from Oct onwards...

Giving me 1200 in April 2024 rather than 1800

So just as you said.

**Comment by shall0pass** [comment]
It seems that the math currently looks like this:
((TARGET_1 - CATEGORY_BALANCE) / MONTHS_TO_TERM) + ((TARGET_2 - CATEGORY_BALANCE) / MONTHS_TO_TERM)

and instead it should look like this:

(TARGET_1 + TARGET_2 - CATEGORY_BALANCE) / MONTHS_TO_TERM

**Comment by shall0pass** [comment]
That's a good point.  We'll probably need to use a fraction of the category balance in the first equation.  I can see why projects are having trouble with this.

**Comment by shall0pass** [comment]
I've been playing in Excel and one observation I'll comment on when we get this logic sorted:  If you have multiple 'by' strings with different completion months, you need to be diligent in moving or spending the money from the category with a completed target before running the goals again.  If you fail to do this, the balance in the category is going to throw off the calculation for upcoming targets because the balance could be higher than the sum of upcoming targets. 

I've been working with examples of:
#template 1000 (for 10 months)
#template 900 (for 9 months)
#template 800 (for 8 months)

Each template should contribute 100 to the budgeted amount.  As you can see, once you get to month 9, there should be 200 budgeted but because the (8 month) category balance would be 2400, that is more than the 1900 target for the two remaining templates for the remaining two months so the math used to get to month 8 breaks at month 9 unless that money is moved.  The same thing happens at month 10 unless the target funds from month 9 is used or spent.

I'm not sure how to overcome this without a more complex approach of 'earmarking' money for a target inside of a category which would basically be categories inside categories.  It now seems to me the best approach is probably separate categories for each 'funding by' target.

🤷‍♂️

**Comment by Kidglove57** [comment]
I think I am correct recalling when using nYNAB that they had not cracked this and I had to have separate categories/category goals for each future spend. I raised it with them as a feature request but I think it was in the too difficult pile.

A couple of Mac apps I looked at before Actual (Banktivity and Moneywell) offered multiple goals in one category but the fills were never what I was expecting! I think Banktivity worked sequentially - fill the first and then start accumulating for the second etc.

Thanks so much for having a go at it!

**Comment by shall0pass** [comment]
This PR removed the sequential method.  Do you think it should be reverted to be sequential again so it is predictable?

**Comment by Kidglove57** [comment]
I'm tempted to dodge this one for now and ask others to also give their views!!

I think what you have established is that this is a very hard nut to crack - even assuming there is a viable solution. Personally I may stick to multiple categories/templates since that is what I have set up already (for example multiple software sub categories within an Annual Subscriptions group). But yes, otherwise sequentially I guess.

**Comment by shall0pass** [comment]
OK.  I think I have the math worked out now (besides having the issue of accounting for the money if it isn't moved or spent from completed targets.)  If this isn't reverted, we should at a minimum try to accomplish this formula.  I've tested this in Excel using the 3 templates I mentioned earlier.
Target for each template -> T[]
Remaining months for each template -> M[]
Number of active templates (array size) -> N
 (T[1] + T[2] + T[3] + T[N]) / (M[1] + M[2} + M[3] + M[N]) * N

This gives me predictable results as long as the funds are spent at the end of the target date.  I'm not sure I'll be able to figure out how to implement this with the current code, so any help would be highly appreciated.  Again, this is assuming we don't just revert back to a sequential method.

**Pull request merged**
