### PR TITLE
Append, Prepend, or Replace notes in bulk actions

### PR DESCRIPTION
**Pull request by shall0pass**
This adds the ability to prepend or append a note to a batch of transactions without overwriting the current notes.  It also retains the ability to set a batch of transactions with the same note as the default.

Will resolve: https://github.com/actualbudget/actual/issues/667

Updated view:
appendNotes

### CODE REVIEW

**Comment by Teprifer** [comment]
Just had a go with this one in chrome(reset all browser data) and Firefox (incognito mode) and none of the buttons changed the notes. :(

Console log only showed:
(Chrome)
image

(Firefox)
image

**Comment by shall0pass** [comment]
> Just had a go with this one in chrome(reset all browser data) and Firefox (incognito mode) and none of the buttons changed the notes. :(

The buttons are intended to be a toggle between options and not an "apply" action.  To get it to work, click on the method, then enter the note and press the enter button.  I thought I might have forgotten a commit where it was working, but it appears to be working on both chrome an firefox for me.  Admittedly, the UI interaction is terrible.  The console output was for debugging purposes to make sure the buttons were doing what I had hoped.  That'll be removed.

**Comment by Teprifer** [comment]
oh! Well, in that case it works. :)
The console comment was just me looking for debug info.

Not sure about the auto-inserting of a comma though, if someone doesn't want it, they'd have to go back to editing the notes manually. It seems that for prepend to add space after, and append a space before, makes sense though. 🤷

Either way, I think it needs a check to ensure you don't end up with a double comma or double space in the note, and it doesn't make sense to do either if the note was blank originally in a transaction.

I'd suggest either:

1) moving the buttons to the top(my preferred) so the work flow is: 
   * Set Mode 
   * Set Text 
   * Tap Enter 

2)  Or have a separate apply button underneath.
     * Or return input back to the text box after selecting the method so the user can just hit enter.

3) Or the button applies the action

And for 1 and 2, indicate the buttons are toggles by setting the selected as having the purple background, and the non-selected the current white.

I found an anomaly, the behaviour is a bit squirrrely in trying to reproduce which exact steps would trigger the insertion of null.
Some combos it would insert 'null' other times it wouldn't. If you can't reproduce let me know what screen recording is useful and I'll do that.

1. All Accounts screen (edit, tested on a regular account screen and reproduced too)
2. Select two transactions
3. Use pre-pend or append
4. Result, the note has additional text and 'null'
image

Selected these two:
image
Clicked prepend
image
image

**Comment by shall0pass** [comment]
Seeing as that I'm not particularly skilled at UI development, my request for help was primarily targeted in that area.

**Comment by shall0pass** [comment]
There are still some issues with the button colors, but it's better.  Used copilot for help.

image

It looks better in dark and midnight color themes.
image
image

**Review by youngcw — APPROVED** [review]
Looks good

**Review by youngcw — APPROVED** [review]

**Pull request merged**
