### PR TITLE
[WIP] Exclude future transactions

### PR DESCRIPTION
**Pull request by javripley**
This is an attempt to implement #2354

Please refer to that issue and [related Discord thread](https://discord.com/channels/937901803608096828/1027831756545609789/1208693552075251782) for more context.

### CODE REVIEW

**Comment by Teprifer** [comment]
I'm still very firmly of thew view that exempted transactions need to be visually separate from all other transactions so I hope that's upcoming.

In the meantime I took a poke around, it looks like you're excluding the value from the budgeted 'spent' value as expected, however when you click on the 'spent' value, the resulting page includes future transactions so the maths no longer adds up. In my view that query would also need amending as it's explicitly a past tense 'these are the transactions that give you this total'. I.e. a change from  from 'this month' to 'up until today's date in this month', or have the same visual affect applied to it,

**Comment by javripley** [comment]
> I'm still very firmly of the view that exempted transactions need to be visually separate from all other transactions so I hope that's upcoming.

I agree. Just not sure how to do that. Could be a collapsible group, like in nYNAB, or something more akin to the UI/UX used for scheduled transactions. I was thinking the "cleared" icon, for instance, should probably be disabled and blurred as well (like things are in the "privacy" mode).

> In the meantime I took a poke around, it looks like you're excluding the value from the budgeted 'spent' value as expected, however when you click on the 'spent' value, the resulting page includes future transactions so the maths no longer adds up. In my view that query would also need amending as it's explicitly a past tense 'these are the transactions that give you this total'. I.e. a change from from 'this month' to 'up until today's date in this month', or have the same visual affect applied to it,

There were bugs in the code that I hope to have fixed. Could you please try again?

**Comment by Teprifer** [comment]
I think there's a bit of leeway in how the separation is implemented as long as it follow these 3 considerations (my opinion only).
I agree it makes sense not to have the cleared flag even show, seems by definition something in the future can't be cleared. Using the calendar icon the same as scheduled makes sense. 

* The separation is clear and easily understood (e.g. some combination of: spacing from regular transactions, colour, text formatting, explicit messaging etc.)
* Actual's visual aesthetics are followed (simple, themed, etc.)
* It doesn't clash with scheduled transactions

Was off work today so had some time to poke around again:

Private window
Add future transaction, account balance goes down as expected etc.
Enable feature flag
Side bar bank balance didn't update
Account view itself did
Budget table didn't update
Transaction is visible when clicking on spent
--Refresh the page and the side bar and budget table updated to exclude it as expected. (Forgot to check clicking on spent here soz!)


Close and reopen private window
Enable feature flag
Add future transaction - bank balance unchanged
Side bar balance changed (shouldn't)
Budget table unchanged
- Spent filter still includes it
Refresh and side bar updates to exclude

**Comment by Teprifer** [comment]
Looks like adding a future transaction is taking effect on the budget table, and spent click through list, even when the feature flag hasn't been enabled yet.

image
image
image
image
image

On the earlier points, toggling the feature flag on updated the side bar and account as you're intending.

Toggling it off again sets side bar and account to include the future transaction, but for the budget table, see above issue. :)

**Comment by Teprifer** [comment]
Adding future transaction, enabled feature.
Side bar updated.
Budget table spent figure is including the future transaction value. - You may need to amend this specifically after all?
Er... then I disabled the feature and the transaction disappeared from the budget table, and the sidebar updated to include it again. Playing with toggling it some more, yup, a bit of hinkyness here - I'll let you have a play with that. :)

On the grouping and separation of the future transactions, I do have opinions hah, but think it'd be good for you to get some feedback from the maintainers/others on this before I add my presentation thoughts here :) then the presentation can be refined (although I have some points in earlier comments).

My 2 cents is that this would be worth adding even if I wouldn't get much out of it, as a bonus it would also enhance expanding out the time period for scheduled transactions as they'd no longer clutter the accounts page. 
Done right, I think it'd be something that would just be on(akin to YNAB iirc), rather than an option. But maybe some people rely on future transactions counting for their work flow. 🤷

**Comment by javripley** [comment]
Made some progress, but need help with CSS.

Loading icon while processing the budget cache reset:
image

Collapsible group of future transactions (collapsed by default):
image
image

> Should probably find a way to sort the scheduled transactions (rule based) together with the future transactions (already entered)

Upcoming transactions tooltip (the idea is to place it by the "Balance" amount):
image

> This needs lots of CSS work...

**Comment by Teprifer** [comment]
Took a poke while on mobile, app crashes after enabling this feature and returning to the budget page.

**Pull request closed without merging**
