### PR TITLE
Nordigen integration - account sync

### PR DESCRIPTION
**Pull request by fstybel**
This PR integrates the app with [Nordigen](https://nordigen.com/en/) to allow account sync with banks - balance, account info, transfers.

Related backend PR: https://github.com/actualbudget/actual-server/pull/74

Discord thread 🧵 : https://discord.com/channels/937901803608096828/1017092225122967622

## Todo:

- [ ] Set the` sort_order` flag for imported transactions based on the order of the transaction
- [x] Move normalization of data to the backend side
- [ ] Fetch integrated banks from the backend
- [ ] Design: Modal with bank selection
- [ ] Design: Fix modal with accounts linking
- [ ] Fix tests

## Demo

https://user-images.githubusercontent.com/8612503/189112287-ac8f70ac-3e6f-4586-b6c2-99cda514db46.mov

## How to setup

1. Create a Nordigen account and generate API credentials
2. Launch backend from the [PR](https://github.com/actualbudget/actual-server/pull/74) with Nordigen API credentials `SECRET_ID=xxx SECRET_KEY=xxxx  yarn start`
3. Launch frontend: `yarn start:browser`

### CODE REVIEW

**Comment by MatissJanis** [comment]
👋 Just wanted to check-in here: what's the status here? Are you still actively working on this? Is it waiting for a full review? 

Let me know how I can help.

**Comment by MatissJanis** [comment]
👋 I'll close this PR for now to clean up PR backlog, but please, please, please - feel free to re-open it back up and continue working here. I would be more than happy to see bank-sync integration in the next release!

**Comment by fstybel** [comment]
Sorry I missed your previous message. I reopened PR - #457

I'm working on it, but very slowly. At this moment I'm focused on the backend. Later I will back to the frontend part but would be nice if anyone has the possibility to help me with the frontend. I'm mostly a backend guy ;)

**Comment by MatissJanis** [comment]
> Sorry I missed your previous message. I reopened PR - #457
> 
> I'm working on it, but very slowly. At this moment I'm focused on the backend. Later I will back to the frontend part but would be nice if anyone has the possibility to help me with the frontend. I'm mostly a backend guy ;)

Great to hear that progress is being made here! And sorry for closing the PR :)

I'll post a message on discord that you're looking for frontend support and hopefully we find someone 🤞

**Pull request closed without merging**
