### PR TITLE
RFC: Codesigning windows builds

### PR DESCRIPTION
**Pull request by Shazib**
Sorry I accidentally closed the PR so opening again.

### Changes Made
Adding code-signing to windows builds.

This is all handled by [electron-builder](https://www.electron.build/code-signing.html) so all we need to do is supply it with the certificate details. There are two new github org secrets that need to be set before it will work. I am just using a locally generated certificate for now.

The new secrets are WIN_CERT_BASE64 and WIN_CERT_PASS

I will remove the `workflow_dispatch:` before this PR is merged, its just there for testing atm.

Slightly related, the version number in `desktop-electron/package.json` is out of sync, so whatever process updates this perhaps needs a review.

### Getting a Certificate
Option 1: Generate our own certificate. 
- Free adn easy but won't be recognised by windows

Option 2: Purchase a Certificate
- Will be recognised by windows
- More complicated

Steps:

1. We need to set up a cloud based HSM (hardware security module) to store the cert. This requirement came into force May of this year as far as I can tell and cert authorities will only send youa cert on a hardware token or add it to your HSM.
2. Buy a cert. There are lots of websites that sell codesigning certs, the cheapest i've seen is [here](https://cheapsslsecurity.com/fastssl/code-signing-certificate.html?gad=1) for $149/year. 

- We can use a cloud based HSM, for example [Azure Key Vault](https://azure.microsoft.com/en-gb/products/key-vault)
- Azure offers $200 in free credit. I'm not sure how long this would last. Presumably we can use an unverified cert for dev builds and only fetch the offical one for release builds.
- You upload and store the certificate in azure and its accessed via this [github action](https://github.com/Azure/cli) 

One thing i'm a little unclear about is how we would tranfer the certificate from the seller to the HSM, given they won't just send you the file. I have seen [this](https://learn.microsoft.com/en-us/azure/key-vault/certificates/certificate-scenarios#creating-a-certificate-with-a-ca-not-partnered-with-key-vault) but I can't test it without actually buying a cert. Azure is partnered with digicert etc for eliminating this issue but the certificates from them are much more expensive.

I am currently deploying an azure keyvault to try it out and will report back...There is also an AWS HSM.

In terms of financing this, I have not seen any links for donating etc, but would be happy to contribute.

### Windows Store
I _think_ none of the above is needed if we publish directly to the microsoft store, as they re-sign things with a microsoft certificate, we just have to sign with _a_ cert, that we upload to our MS Developer account so they can verify who submitted the app.

I can't test this thoroughly because whilst I have a MS Dev account you need to provide a url to a website, a url to the exe, a privacy policy, etc, so I dont have a good 'test' app to run through the process.

I can try actually deploying the current actualbudget there if people want.

This does have the caveat that people downloading directly from the github release won't get the 'officially' signed version.

image

### CODE REVIEW

**Comment by MatissJanis** [comment]
👋 Thanks for this!

Lets keep this in a "do not merge" state for now. We (the core maintainers) still need to figure out how we can absorb the costs this would pertain. So there's quite a bit more process & documentation we must put in place before doing this.

In the meantime - we can definitely focus on generating unsigned releases.

**Comment by Shazib** [comment]
> 👋 Thanks for this!
> 
> Lets keep this in a "do not merge" state for now. We (the core maintainers) still need to figure out how we can absorb the costs this would pertain. So there's quite a bit more process & documentation we must put in place before doing this.
> 
> In the meantime - we can definitely focus on generating unsigned releases.

👍 Ok.

Would we be better off for now just signing with a self-created cert (given the 0 cost)? That way we at least have the basic workflow in place and builds don't show as totally unsigned?

Thanks

**Comment by MatissJanis** [comment]
That would be better - I agree. But we still have to solve problems such as: where do we store the cert? Is it only in Github env variables? What if someone accidentally deletes it? Should we store it in a vault too? Where? Who should have access to it? etc. We must have a documented process in place before we can jump in and just do it.

We have started internal discussions about funding. Once we have concluded those, the next natural target is: certificates. It takes a bit of time and I understand how frustrating that can be.. but we're stretched pretty thin.

**Comment by Shazib** [comment]
> That would be better - I agree. But we still have to solve problems such as: where do we store the cert? Is it only in Github env variables? What if someone accidentally deletes it? Should we store it in a vault too? Where? Who should have access to it? etc. We must have a documented process in place before we can jump in and just do it.
> 
> We have started internal discussions about funding. Once we have concluded those, the next natural target is: certificates. It takes a bit of time and I understand how frustrating that can be.. but we're stretched pretty thin.

Totally understand, thanks for the reply!

**Pull request closed without merging**
