### PR TITLE
comments added to Update budget.test.js

### PR DESCRIPTION
**Pull request by Gordiancyber**
---
category: Comments
authors: Gordiancyber
---
The comments provide an overview of the purpose and flow of the test suite and individual test cases

### CODE REVIEW

**Comment by Gordiancyber** [comment]
> ### 👷 Deploy Preview for _actualbudget_ processing.
> Name	Link
> 🔨 Latest commit	[690ca13](https://github.com/actualbudget/actual/commit/690ca1328532ae99967d6b9bdaac1aafd792e86f)
> 🔍 Latest deploy log	https://app.netlify.com/sites/actualbudget/deploys/653df663bea73f0008eace31



> ### 👷 Deploy Preview for _actualbudget_ processing.
> Name	Link
> 🔨 Latest commit	[690ca13](https://github.com/actualbudget/actual/commit/690ca1328532ae99967d6b9bdaac1aafd792e86f)
> 🔍 Latest deploy log	https://app.netlify.com/sites/actualbudget/deploys/653df663bea73f0008eace31
---
category: Comments
authors: Gordiancyber
---
The comments provide an overview of the purpose and flow of the test suite and individual test cases

**Comment by rich-howell** [comment]
Would this not be better placed in the documentation? Additionally some of them comments are just replication of the test name.

**Comment by Shazib** [comment]
Numbering comments is usually a bad idea (imo) because as soon as you insert or delete an entry the numbering is off.

most of the comments feels fairly redundant to me in any case

**Comment by MatissJanis** [comment]
👋 Hiya! I'm very happy to see a new contributor to Actual.

But sadly as @Shazib already mentioned: these comments are quite redundant. Ideally the test description should be in the `describe` or `it/test` blocks instead of comments. i.e. `it("this is the description", ...)`.

**Pull request closed without merging**
