### PR TITLE
Simplify the settings layout and merge everything onto one page

### PR DESCRIPTION
**Pull request by j-f1**
- move everything onto one page for simplicity, clarify that the tracking setting applies to all files
- align the labels/select boxes in the formatting section
- standardize the layout into components to reduce custom styling

<details><summary>Outdated screenshot</summary>

</details>

### CODE REVIEW

**Comment by rich-howell** [comment]
@j-f1 I think privacy can actually be removed, I don't think it works anymore - was for the hosted version.

**Comment by j-f1** [comment]
Cool, what about auto-update and the documents folder?

**Comment by rich-howell** [comment]
> Cool, what about auto-update and the documents folder?

Same, I don't think there is auto updates anymore, not sure what the documents folder is though...

**Comment by j-f1** [comment]
> not sure what the documents folder is though

The Electron app has to put its data in a folder on disk somewhere, if we still want to support building for Electron we should keep it.

**Comment by rich-howell** [comment]
> > not sure what the documents folder is though
> 
> 
> 
> The Electron app has to put its data in a folder on disk somewhere, if we still want to support building for Electron we should keep it.

Sorry, I wasn't thinking of the electron app, checked the web and couldn't see a docs folder. 

Does the electron app work with the open source version?

**Comment by j-f1** [comment]
> Does the electron app work with the open source version?

I haven’t been able to get it to build, and the currently shipping Electron app doesn’t support the open source version.

**Comment by rich-howell** [comment]
> > Does the electron app work with the open source version?
> 
> I haven’t been able to get it to build, and the currently shipping Electron app doesn’t support the open source version.

I have seen lots of people struggling with the desktop app, not sure if long term it is going to be maintained. Would be good to get an answer from @jlongster on this one before removing it from the settings I think.

**Comment by jlongster** [comment]
Sorry for the delay. We definitely want to support the electron app, but we need to figure out code signing... it's a lot simpler if we accept that users will get a warning on Windows and ditch it there. Code signing for windows is expensive, really annoying to do, and all the setup work has to be done every single year (unless you by longer certs like 3 years, but those are much much more expensive)

macOS code signing isn't too bad so we can support it there. But we should keep it around and work towards it.

I'm fully sure I agree with the changes in this PR to be honest:

* The tracking section can be removed. We don't track anything anymore
* We also don't have automatic updating in the way this suggests. It's for the desktop app. We can remove it from the UI, but just comment it out in code and redo the settings when we get electron working.
* The alignment of the formatting fields feels off. I personally prefer the current layout, but I'd be OK if the labels for the fields both left-aligned while keeping the selects aligned
* I really like Advanced being collapsible, and collapsed by default
* The box styling was only for settings inside the advanced section to explain them. The encryption is the only place you've applied it here, but I'm not sure it's worth it (we want to add more and more settings, and I don't want them all to be in boxes)
* Sync id is very internal and I like the current design better where it's smaller and grayed out. The budget id is way more important and commonly used, and this is confusing because people will ask which ID they need

Sorry, I've long wanted to overhaul settings and have worked on designs for it before but never finished them and implemented :)

**Comment by jlongster** [comment]
I meant to also say:

* Where the files are stored is also only for the electron version. So you're right that the whole "global" section can go away for now. But I'd prefer to keep the current design of the File section for the most part (and get rid of the toggle at the top)

**Review by MatissJanis — APPROVED** [review]
Thanks for your contribution!

**Review by trevdor — APPROVED** [review]
The reuseable Section component is great. And nice to have the Global side of things gone since it's not applicable now. Thanks for your work on this, @j-f1!

It's very much personal taste, but I'd like to see us sharpen the styling of the bits above "Formatting" in the future. For now, though, we'll merge as-is.

**Comment by j-f1** [comment]
I agree that the about and formatting sections could be nicer but I'm not sure what would be a better design :) hence the smaller number of changes there.

**Pull request merged**
