### PR TITLE
Fix a navigation bug and a crash from the account pages

### LINKED ISSUE #3922: [Bug]: Back button broken on mobile when editing transaction from "uncategorized" account
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When going back from editing a uncategorized transaction on mobile, it should go back to the uncategorized account.

Instead it goes back to the account the transaction belongs to.

Regression occurred in this PR: https://github.com/actualbudget/actual/pull/3905

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

### LINKED ISSUE #3927: [Bug]: Crash on mobile "Uncategorized transactions" page after adding a new transaction from that page
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Steps:
1. Make an uncategorized transaction
2. From the budget page, click the "Uncategorized transactions" button
3. Click the plus in the top right and add a new transaction, but don't set the account.
4. Click "Add transaction" and observe the error.

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

_No response_

### Operating System

None

### PR DESCRIPTION
**Pull request by jfdoming**
Fixes #3922
Fixes #3927

### CODE REVIEW

**Comment by joel-jeremy** [comment]
This issue is tricky because we have to take in consideration the workflow of adding transactions straight from the budget page (through the `+ Transaction` nav button). This PR breaks that workflow.

Steps to test:
1. Go to Budget page
2. Click on Transaction nav button
3. Add a transaction to an account

Expected: The app should take you to the account where you added the transaction
Actual: The app takes you back to the budget page

**Comment by joel-jeremy** [comment]
I'm also fine with the app just taking me back to the budget page vs the current behavior. But in that case, we should also remove the  `useNavigate` hook entirely since there's no longer a need for it I believe - but that can be always be done in a separate PR.

**Comment by jfdoming** [comment]
> I'm also fine with the app just taking me back to the budget page vs the current behavior. But in that case, we should also remove the `useNavigate` hook entirely since there's no longer a need for it I believe - but that can be always be done in a separate PR.

Thanks for the feedback! Was hoping to get this into the current release so I think let's defer that to a future PR. I do think just going back is more intuitive (vs opening the account page) as then the transaction page acts just like a modal.

**Review by matt-fidd — APPROVED** [review]
LGTM!

**Pull request merged**
