### PR TITLE
Adding docker-compose file

### PR DESCRIPTION
**Pull request by cuken**
Adds a very basic docker-compose file using Kovah's docker image of the server. Persists data via the volume mounting on `$DOCKERDIR/actual/data:/data`.

User should define $DOCKERDIR or set it to a relative path on the docker server.

### CODE REVIEW

**Comment by boushley** [comment]
Seems like if we're going to add a docker-compose file we should first have a Dockerfile and use that inside the compose file. Right?

**Comment by boushley** [comment]
Actually I see now that the actual-server project has a Dockerfile. It still seems like the docker-compose we add in here should be using an official Docker image that's controlled by the maintainers of this repo.

**Comment by cuken** [comment]
@boushley Agreed, I do not believe there is an "officially" supported docker image maintained by the repo.

**Comment by boushley** [comment]
That's definitely the way it looks currently. We should look at getting setup as an open source project on Docker Hub: https://www.docker.com/community/open-source/application/

**Comment by jlongster** [comment]
To be honest I'm a little confused. The artifacts of building this is two things: a JS bundle meant to be included as a web worker for the backend, and a JS bundle for the frontend. We publish those through npm: `@actual-app/api` and `@actual-app/web`. npm is meant to be the distribution mechanism. There is no server component here. Why do we need docker?

**Comment by jlongster** [comment]
This uses the port 5006, which makes me believe you really wanted https://github.com/actualbudget/actual-server

Or a separate project is that just a server that serves up the app without a syncing server?

**Comment by cuken** [comment]
@jlongster  I think the confusion was around the actual-server repo referenced in the documentation versus this. Many people will land at this main repo and not make the connection to the actual-server repo (which this docker-compose serves up).

**Comment by TomAFrench** [comment]
I think we can close this PR. It's had a lot of my PRs merged into it so it's doing a lot of things other than adding a docker-compose file anyway.

**Comment by jlongster** [comment]
Sorry for the delay here y'all -- I'm cleaning up PRs now

Agree, let's close this and please re-open with fresh changes if there's anything here. This isn't the right repo for docker settings, `actual-server` is

**Pull request closed without merging**
