### PR TITLE
:bug:  fix nordigen sync bug

### PR DESCRIPTION
**Pull request by MatissJanis**

### CODE REVIEW

**Comment by MatissJanis** [comment]
Extracted the fixes from: https://github.com/actualbudget/actual/pull/1282

So we could apply a few more fixes before pushing out the release v23.7.1

**Review by j-f1 — APPROVED** [review]
Looks like this also fixes the drag and drop issue perhaps — worth updating the comment for the release notes / splitting up?

**Comment by youngcw** [comment]
When I try this I cant reorder categories UNLESS I reorder the accounts first then category reorder works.  Thats the same as current release.

**Comment by MatissJanis** [comment]
Damn.. that is weird. Still better than before, but we definitely need to properly fix it. Interested to give it a try?

**Comment by youngcw** [comment]
> Interested to give it a try?

I would break more than was fixed. So Ill stick to testing help

**Pull request merged**
