### PR TITLE
Use GoCardless remittanceInformationStructured for notes if available

### LINKED ISSUE #2759: [Feature] Read out what's entered as remittanceInformationStructured when syncing your bank transactions with GoCardless so that it can be imported into the "Notes" section in Actual
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently, Actual doesn't look at remittanceInformationStructured at any point during bank sync, so it isn't used as part of the notes. At the moment AB only looks at remittanceInformationUnstructured and remittanceInformationUnstructuredArray. 
Some banks like the Berliner Sparkasse, a regional Bank in Germany which is part of the nationwide Sparkassen-Finanzgruppe, 
will transmit the reason for payment as remittanceInformationStructured. 

### Describe your ideal solution to this problem

Ideally, Actual would look at remittanceInformationStructured as well when looking for things to be imported as notes for a transaction. 

### Teaching and learning

_No response_

### PR DESCRIPTION
**Pull request by matt-fidd**
Closes #2759

Following a discussion in Discord it looks like `BELADEBEXXX` does not provide `remittanceInformationUnstructured` at all and just returns `remittanceInformationStructured`. The notes field should pick this up if it exists.

The GoCardless docs are vague on what this field contains and I can't seem to find the structure mentioned in them but (at least in this case) the data appears similar or the same to what we'd normally see in the unstructured version.

image

If #2721 and actualbudget/actual-server#353 are merged there's probably another conversation to be had regarding whether it's worth moving this over to `actual-server` too.

### CODE REVIEW

**Comment by matt-fidd** [comment]
I wonder if we should be using this as a backup for payeeName too as `Unstructured` is.

**Comment by MatissJanis** [comment]
Lets put this one on hold until we get to an agreement in https://github.com/actualbudget/actual-server/pull/353.

I'll try to review it soon™️.

**Comment by Peccadilloz** [comment]
As suggested by @kyrias on the Discord support channel I instead added the integration for this bank using the bank integration support. It's in the PR [#358](https://github.com/actualbudget/actual-server/pull/358) over on the actual-server repo.

**Comment by matt-fidd** [comment]
No problem, will close this one off

**Comment by matt-fidd** [comment]
@MatissJanis looks like this field might not be what I thought it was. It's still possible we might want to use this as a fallback though, I've closed it off for now but let me know if you'd like it reopened.

**Pull request closed without merging**
