### PR TITLE
🐛 (imports) ability to toggle on/off OFX import fallback payee

### LINKED ISSUE #1524: [Bug]: OFX Import "Notes" & "Payee" Fields Switched
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I have been happily using Actual for the last 8 months, and the OFX import tool has worked beautifully until now (first attempt in the last 3-4 weeks, so I'm assuming it's the new OFX importer).

Basically, the "Notes" and "Payee" fields have all been swapped, which is immensely painful and makes the import tool basically unusable. Below is an example of what I am seeing now, with all the purchase details in the payee field instead of notes. This means that every new transaction imported has a new payee, as every payment description is unique.

image

#521 seems like a related problem but I'm unsure what ended up happening.

FWIW I attempted to re-import some old OFX files that worked beautifully several months ago, and they're all exhibiting the same behaviour. This leads me to believe its not an issue with my bank's OFX export tool.

I'm currently running 23.8.1 using Docker and Google Chrome.

### What error did you receive?

_No response_

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

### PR DESCRIPTION
**Pull request by MatissJanis**
Closes #1524 
Screenshot 2023-09-01 at 18 59 22

Demo OFX: https://github.com/actualbudget/actual/issues/1524#issuecomment-1678100476

### CODE REVIEW

**Comment by trevdor** [comment]
To me, the implementation in code is great, but I have some questions/concerns around how we surface it to the user. 

I oughta be sleeping, so will write those up in the morning. 

But don't let me hold up your release prep--any suggestion that might come from my thoughts here can be a separate enhancement.

**Comment by trevdor** [comment]
Not an OFX import user, so apologies if I've misunderstood anything. Here were those thoughts:

It wasn't clear to me from the UI that it's a per-account pref. `Fallback missing payee to memo field` might mean for each transaction missing a payee.

But since it is per-account, it strikes me as odd that we are saying, essentially, we're going to fall back *if we find out* the payee isn't populated. Don't we know at the time we're offering the override, since we're showing preview transactions? And if we know, shouldn't the user be offered a direct choice of payee or memo?

In the case we detect an empty Payee, could we prompt the user "For imports in \<Name of Account\>, do you want to use Memo for Payee since Payee is empty?" 
Then the override option shown reflects that choice (including defaulting to the last chosen pref). 
Something like: "[ ] Use Memo for Payee"

**Comment by MatissJanis** [comment]
To clarify: are you suggesting just changing the label? That sounds fine to
me.
Also I think it makes more sense to make this configuration on a
per-transaction basis, not per-account. I’ll change that.

**Comment by trevdor** [comment]
If it's not per-account, but a global "whenever we detect a missing Payee, go grab Memo", then yeah, I have no change suggestion for the workflow. 

I do think the label could be clearer. Perhaps `Use Memo as a fallback for empty Payees`? (hmm, don't LOVE that either)

**Comment by trevdor** [comment]
I'm good with whatever you go with, for the checkbox text. 

If the preview updates immediately to show the result, that will make clear what's being chosen.

**Comment by MatissJanis** [comment]
Feedback addressed :)

**Review by trevdor — APPROVED** [review]

**Comment by themadman0980** [comment]
Just tested this fix and it works beautifully. 

Some quick feedback based on using it just now. 

1. The import preview doesn't update in real-time when you change the checkbox selection, which is quite disconcerting and makes it slightly more difficult to tell what effect it actually has. 
2. The description for the checkbox refers to "Memo" while the preview table uses the column heading "Notes" which can perhaps make it a little harder to decipher. This probably wouldn't matter if real-time updates were implemented, as this would make the function of the checkbox quite clear.

Both of these are really one-time issues though, as most users can set and forget it after the first import I imagine.

**Comment by MatissJanis** [comment]
@themadman0980 it used to update in real time. If it doesn't anymore - that would be a bug.

Could you open an issue please?

**Pull request merged**
